
ECHO ***************** Adding Secondry Zone %7
SET PRIMARY_SERVER_NAME=%1
SET PRIMARY_DOMAIN=%2
SET PRIMARY_IP=%3
SET SECONDRY_SERVER_NAME=%4
SET SECONDRY_DOMAIN=%5
SET SECONDRY_IP=%6
SET DOMAIN_NAME=%7

dnscmd %SECONDRY_SERVER_NAME% /zonedelete %DOMAIN_NAME% /f
dnscmd %SECONDRY_SERVER_NAME% /zoneadd %DOMAIN_NAME% /secondary %PRIMARY_IP% /file %DOMAIN_NAME%.dns
