
SET PRIMARY_SERVER_NAME=extra
SET PRIMARY_DOMAIN=ns1.cambro.net
SET PRIMARY_IP=84.45.14.40
SET SECONDRY_SERVER_NAME=mace
SET SECONDRY_DOMAIN=ns2.cambro.net
SET SECONDRY_IP=84.45.14.41
SET SOA_EMAIL=hostmaster.cambro.net

: Add simple alias domains for dontstayin
CALL Add-DontStayIn-Aliases                 %PRIMARY_SERVER_NAME% %PRIMARY_DOMAIN% %PRIMARY_IP% %SECONDRY_SERVER_NAME% %SECONDRY_DOMAIN% %SECONDRY_IP% %SOA_EMAIL%
