//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
//mappings.Add("Spotted.CustomControls.InlineScript", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using jQueryApi;
using Js.Library;

namespace Js.Controls.ThreadControl
{
	public partial class View
	{
		public string clientId;
		public View(string clientId)
		{
			this.clientId = clientId;
		}
		public Js.Controls.CommentsDisplay.Controller uiCommentsDisplay {get {return (Js.Controls.CommentsDisplay.Controller) Script.Eval(clientId + "_uiCommentsDisplayController");}}
		public DivElement PostCommentPanel {get {if (_PostCommentPanel == null) {_PostCommentPanel = (DivElement)Document.GetElementById(clientId + "_PostCommentPanel");}; return _PostCommentPanel;}} private DivElement _PostCommentPanel;
		public jQueryObject PostCommentPanelJ {get {if (_PostCommentPanelJ == null) {_PostCommentPanelJ = jQuery.Select("#" + clientId + "_PostCommentPanel");}; return _PostCommentPanelJ;}} private jQueryObject _PostCommentPanelJ;
		public Element H1 {get {if (_H1 == null) {_H1 = (Element)Document.GetElementById(clientId + "_H1");}; return _H1;}} private Element _H1;
		public jQueryObject H1J {get {if (_H1J == null) {_H1J = jQuery.Select("#" + clientId + "_H1");}; return _H1J;}} private jQueryObject _H1J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element ThreadWatchButtonHolder {get {if (_ThreadWatchButtonHolder == null) {_ThreadWatchButtonHolder = (Element)Document.GetElementById(clientId + "_ThreadWatchButtonHolder");}; return _ThreadWatchButtonHolder;}} private Element _ThreadWatchButtonHolder;
		public jQueryObject ThreadWatchButtonHolderJ {get {if (_ThreadWatchButtonHolderJ == null) {_ThreadWatchButtonHolderJ = jQuery.Select("#" + clientId + "_ThreadWatchButtonHolder");}; return _ThreadWatchButtonHolderJ;}} private jQueryObject _ThreadWatchButtonHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element InlineScript3 {get {if (_InlineScript3 == null) {_InlineScript3 = (Element)Document.GetElementById(clientId + "_InlineScript3");}; return _InlineScript3;}} private Element _InlineScript3;
		public jQueryObject InlineScript3J {get {if (_InlineScript3J == null) {_InlineScript3J = jQuery.Select("#" + clientId + "_InlineScript3");}; return _InlineScript3J;}} private jQueryObject _InlineScript3J;//mappings.Add("Spotted.CustomControls.InlineScript", ElementGetter("Element"));
		public Element ThreadFavouriteButtonP {get {if (_ThreadFavouriteButtonP == null) {_ThreadFavouriteButtonP = (Element)Document.GetElementById(clientId + "_ThreadFavouriteButtonP");}; return _ThreadFavouriteButtonP;}} private Element _ThreadFavouriteButtonP;
		public jQueryObject ThreadFavouriteButtonPJ {get {if (_ThreadFavouriteButtonPJ == null) {_ThreadFavouriteButtonPJ = jQuery.Select("#" + clientId + "_ThreadFavouriteButtonP");}; return _ThreadFavouriteButtonPJ;}} private jQueryObject _ThreadFavouriteButtonPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element ThreadFavouriteButtonHolder {get {if (_ThreadFavouriteButtonHolder == null) {_ThreadFavouriteButtonHolder = (Element)Document.GetElementById(clientId + "_ThreadFavouriteButtonHolder");}; return _ThreadFavouriteButtonHolder;}} private Element _ThreadFavouriteButtonHolder;
		public jQueryObject ThreadFavouriteButtonHolderJ {get {if (_ThreadFavouriteButtonHolderJ == null) {_ThreadFavouriteButtonHolderJ = jQuery.Select("#" + clientId + "_ThreadFavouriteButtonHolder");}; return _ThreadFavouriteButtonHolderJ;}} private jQueryObject _ThreadFavouriteButtonHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element InlineScript2 {get {if (_InlineScript2 == null) {_InlineScript2 = (Element)Document.GetElementById(clientId + "_InlineScript2");}; return _InlineScript2;}} private Element _InlineScript2;
		public jQueryObject InlineScript2J {get {if (_InlineScript2J == null) {_InlineScript2J = jQuery.Select("#" + clientId + "_InlineScript2");}; return _InlineScript2J;}} private jQueryObject _InlineScript2J;//mappings.Add("Spotted.CustomControls.InlineScript", ElementGetter("Element"));
		public Element RequiredFieldValidator1 {get {if (_RequiredFieldValidator1 == null) {_RequiredFieldValidator1 = (Element)Document.GetElementById(clientId + "_RequiredFieldValidator1");}; return _RequiredFieldValidator1;}} private Element _RequiredFieldValidator1;
		public jQueryObject RequiredFieldValidator1J {get {if (_RequiredFieldValidator1J == null) {_RequiredFieldValidator1J = jQuery.Select("#" + clientId + "_RequiredFieldValidator1");}; return _RequiredFieldValidator1J;}} private jQueryObject _RequiredFieldValidator1J;//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
		public DivElement CommentGroupMemberPanel {get {if (_CommentGroupMemberPanel == null) {_CommentGroupMemberPanel = (DivElement)Document.GetElementById(clientId + "_CommentGroupMemberPanel");}; return _CommentGroupMemberPanel;}} private DivElement _CommentGroupMemberPanel;
		public jQueryObject CommentGroupMemberPanelJ {get {if (_CommentGroupMemberPanelJ == null) {_CommentGroupMemberPanelJ = jQuery.Select("#" + clientId + "_CommentGroupMemberPanel");}; return _CommentGroupMemberPanelJ;}} private jQueryObject _CommentGroupMemberPanelJ;
		public AnchorElement CommentGroupMemberAnchor {get {if (_CommentGroupMemberAnchor == null) {_CommentGroupMemberAnchor = (AnchorElement)Document.GetElementById(clientId + "_CommentGroupMemberAnchor");}; return _CommentGroupMemberAnchor;}} private AnchorElement _CommentGroupMemberAnchor;
		public jQueryObject CommentGroupMemberAnchorJ {get {if (_CommentGroupMemberAnchorJ == null) {_CommentGroupMemberAnchorJ = jQuery.Select("#" + clientId + "_CommentGroupMemberAnchor");}; return _CommentGroupMemberAnchorJ;}} private jQueryObject _CommentGroupMemberAnchorJ;
		public DivElement CommentLoginPanel {get {if (_CommentLoginPanel == null) {_CommentLoginPanel = (DivElement)Document.GetElementById(clientId + "_CommentLoginPanel");}; return _CommentLoginPanel;}} private DivElement _CommentLoginPanel;
		public jQueryObject CommentLoginPanelJ {get {if (_CommentLoginPanelJ == null) {_CommentLoginPanelJ = jQuery.Select("#" + clientId + "_CommentLoginPanel");}; return _CommentLoginPanelJ;}} private jQueryObject _CommentLoginPanelJ;
		public DivElement CommentEmailVerifyPanel {get {if (_CommentEmailVerifyPanel == null) {_CommentEmailVerifyPanel = (DivElement)Document.GetElementById(clientId + "_CommentEmailVerifyPanel");}; return _CommentEmailVerifyPanel;}} private DivElement _CommentEmailVerifyPanel;
		public jQueryObject CommentEmailVerifyPanelJ {get {if (_CommentEmailVerifyPanelJ == null) {_CommentEmailVerifyPanelJ = jQuery.Select("#" + clientId + "_CommentEmailVerifyPanel");}; return _CommentEmailVerifyPanelJ;}} private jQueryObject _CommentEmailVerifyPanelJ;
		public Js.Controls.Html.Controller CommentHtml {get {return (Js.Controls.Html.Controller) Script.Eval(clientId + "_CommentHtmlController");}}
		public Element AddThreadAdvancedCheckBoxP {get {if (_AddThreadAdvancedCheckBoxP == null) {_AddThreadAdvancedCheckBoxP = (Element)Document.GetElementById(clientId + "_AddThreadAdvancedCheckBoxP");}; return _AddThreadAdvancedCheckBoxP;}} private Element _AddThreadAdvancedCheckBoxP;
		public jQueryObject AddThreadAdvancedCheckBoxPJ {get {if (_AddThreadAdvancedCheckBoxPJ == null) {_AddThreadAdvancedCheckBoxPJ = jQuery.Select("#" + clientId + "_AddThreadAdvancedCheckBoxP");}; return _AddThreadAdvancedCheckBoxPJ;}} private jQueryObject _AddThreadAdvancedCheckBoxPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadAdvancedCheckBox {get {if (_AddThreadAdvancedCheckBox == null) {_AddThreadAdvancedCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadAdvancedCheckBox");}; return _AddThreadAdvancedCheckBox;}} private CheckBoxElement _AddThreadAdvancedCheckBox;
		public jQueryObject AddThreadAdvancedCheckBoxJ {get {if (_AddThreadAdvancedCheckBoxJ == null) {_AddThreadAdvancedCheckBoxJ = jQuery.Select("#" + clientId + "_AddThreadAdvancedCheckBox");}; return _AddThreadAdvancedCheckBoxJ;}} private jQueryObject _AddThreadAdvancedCheckBoxJ;
		public DivElement AddThreadAdvancedPanel {get {if (_AddThreadAdvancedPanel == null) {_AddThreadAdvancedPanel = (DivElement)Document.GetElementById(clientId + "_AddThreadAdvancedPanel");}; return _AddThreadAdvancedPanel;}} private DivElement _AddThreadAdvancedPanel;
		public jQueryObject AddThreadAdvancedPanelJ {get {if (_AddThreadAdvancedPanelJ == null) {_AddThreadAdvancedPanelJ = jQuery.Select("#" + clientId + "_AddThreadAdvancedPanel");}; return _AddThreadAdvancedPanelJ;}} private jQueryObject _AddThreadAdvancedPanelJ;
		public Element AddThreadPublicRadioButtonSpan {get {if (_AddThreadPublicRadioButtonSpan == null) {_AddThreadPublicRadioButtonSpan = (Element)Document.GetElementById(clientId + "_AddThreadPublicRadioButtonSpan");}; return _AddThreadPublicRadioButtonSpan;}} private Element _AddThreadPublicRadioButtonSpan;
		public jQueryObject AddThreadPublicRadioButtonSpanJ {get {if (_AddThreadPublicRadioButtonSpanJ == null) {_AddThreadPublicRadioButtonSpanJ = jQuery.Select("#" + clientId + "_AddThreadPublicRadioButtonSpan");}; return _AddThreadPublicRadioButtonSpanJ;}} private jQueryObject _AddThreadPublicRadioButtonSpanJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadPublicRadioButton {get {if (_AddThreadPublicRadioButton == null) {_AddThreadPublicRadioButton = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadPublicRadioButton");}; return _AddThreadPublicRadioButton;}} private CheckBoxElement _AddThreadPublicRadioButton;
		public jQueryObject AddThreadPublicRadioButtonJ {get {if (_AddThreadPublicRadioButtonJ == null) {_AddThreadPublicRadioButtonJ = jQuery.Select("#" + clientId + "_AddThreadPublicRadioButton");}; return _AddThreadPublicRadioButtonJ;}} private jQueryObject _AddThreadPublicRadioButtonJ;
		public Element AddThreadNewPublicRadioButtonSpan {get {if (_AddThreadNewPublicRadioButtonSpan == null) {_AddThreadNewPublicRadioButtonSpan = (Element)Document.GetElementById(clientId + "_AddThreadNewPublicRadioButtonSpan");}; return _AddThreadNewPublicRadioButtonSpan;}} private Element _AddThreadNewPublicRadioButtonSpan;
		public jQueryObject AddThreadNewPublicRadioButtonSpanJ {get {if (_AddThreadNewPublicRadioButtonSpanJ == null) {_AddThreadNewPublicRadioButtonSpanJ = jQuery.Select("#" + clientId + "_AddThreadNewPublicRadioButtonSpan");}; return _AddThreadNewPublicRadioButtonSpanJ;}} private jQueryObject _AddThreadNewPublicRadioButtonSpanJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadNewPublicRadioButton {get {if (_AddThreadNewPublicRadioButton == null) {_AddThreadNewPublicRadioButton = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadNewPublicRadioButton");}; return _AddThreadNewPublicRadioButton;}} private CheckBoxElement _AddThreadNewPublicRadioButton;
		public jQueryObject AddThreadNewPublicRadioButtonJ {get {if (_AddThreadNewPublicRadioButtonJ == null) {_AddThreadNewPublicRadioButtonJ = jQuery.Select("#" + clientId + "_AddThreadNewPublicRadioButton");}; return _AddThreadNewPublicRadioButtonJ;}} private jQueryObject _AddThreadNewPublicRadioButtonJ;
		public Element AddThreadPrivateRadioButtonSpan {get {if (_AddThreadPrivateRadioButtonSpan == null) {_AddThreadPrivateRadioButtonSpan = (Element)Document.GetElementById(clientId + "_AddThreadPrivateRadioButtonSpan");}; return _AddThreadPrivateRadioButtonSpan;}} private Element _AddThreadPrivateRadioButtonSpan;
		public jQueryObject AddThreadPrivateRadioButtonSpanJ {get {if (_AddThreadPrivateRadioButtonSpanJ == null) {_AddThreadPrivateRadioButtonSpanJ = jQuery.Select("#" + clientId + "_AddThreadPrivateRadioButtonSpan");}; return _AddThreadPrivateRadioButtonSpanJ;}} private jQueryObject _AddThreadPrivateRadioButtonSpanJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadPrivateRadioButton {get {if (_AddThreadPrivateRadioButton == null) {_AddThreadPrivateRadioButton = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadPrivateRadioButton");}; return _AddThreadPrivateRadioButton;}} private CheckBoxElement _AddThreadPrivateRadioButton;
		public jQueryObject AddThreadPrivateRadioButtonJ {get {if (_AddThreadPrivateRadioButtonJ == null) {_AddThreadPrivateRadioButtonJ = jQuery.Select("#" + clientId + "_AddThreadPrivateRadioButton");}; return _AddThreadPrivateRadioButtonJ;}} private jQueryObject _AddThreadPrivateRadioButtonJ;
		public Element AddThreadGroupRadioButtonSpan {get {if (_AddThreadGroupRadioButtonSpan == null) {_AddThreadGroupRadioButtonSpan = (Element)Document.GetElementById(clientId + "_AddThreadGroupRadioButtonSpan");}; return _AddThreadGroupRadioButtonSpan;}} private Element _AddThreadGroupRadioButtonSpan;
		public jQueryObject AddThreadGroupRadioButtonSpanJ {get {if (_AddThreadGroupRadioButtonSpanJ == null) {_AddThreadGroupRadioButtonSpanJ = jQuery.Select("#" + clientId + "_AddThreadGroupRadioButtonSpan");}; return _AddThreadGroupRadioButtonSpanJ;}} private jQueryObject _AddThreadGroupRadioButtonSpanJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadGroupRadioButton {get {if (_AddThreadGroupRadioButton == null) {_AddThreadGroupRadioButton = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadGroupRadioButton");}; return _AddThreadGroupRadioButton;}} private CheckBoxElement _AddThreadGroupRadioButton;
		public jQueryObject AddThreadGroupRadioButtonJ {get {if (_AddThreadGroupRadioButtonJ == null) {_AddThreadGroupRadioButtonJ = jQuery.Select("#" + clientId + "_AddThreadGroupRadioButton");}; return _AddThreadGroupRadioButtonJ;}} private jQueryObject _AddThreadGroupRadioButtonJ;
		public SelectElement AddThreadGroupDropDown {get {if (_AddThreadGroupDropDown == null) {_AddThreadGroupDropDown = (SelectElement)Document.GetElementById(clientId + "_AddThreadGroupDropDown");}; return _AddThreadGroupDropDown;}} private SelectElement _AddThreadGroupDropDown;
		public jQueryObject AddThreadGroupDropDownJ {get {if (_AddThreadGroupDropDownJ == null) {_AddThreadGroupDropDownJ = jQuery.Select("#" + clientId + "_AddThreadGroupDropDown");}; return _AddThreadGroupDropDownJ;}} private jQueryObject _AddThreadGroupDropDownJ;
		public Element AddThreadGroupPrivateCheckBoxSpan {get {if (_AddThreadGroupPrivateCheckBoxSpan == null) {_AddThreadGroupPrivateCheckBoxSpan = (Element)Document.GetElementById(clientId + "_AddThreadGroupPrivateCheckBoxSpan");}; return _AddThreadGroupPrivateCheckBoxSpan;}} private Element _AddThreadGroupPrivateCheckBoxSpan;
		public jQueryObject AddThreadGroupPrivateCheckBoxSpanJ {get {if (_AddThreadGroupPrivateCheckBoxSpanJ == null) {_AddThreadGroupPrivateCheckBoxSpanJ = jQuery.Select("#" + clientId + "_AddThreadGroupPrivateCheckBoxSpan");}; return _AddThreadGroupPrivateCheckBoxSpanJ;}} private jQueryObject _AddThreadGroupPrivateCheckBoxSpanJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadGroupPrivateCheckBox {get {if (_AddThreadGroupPrivateCheckBox == null) {_AddThreadGroupPrivateCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadGroupPrivateCheckBox");}; return _AddThreadGroupPrivateCheckBox;}} private CheckBoxElement _AddThreadGroupPrivateCheckBox;
		public jQueryObject AddThreadGroupPrivateCheckBoxJ {get {if (_AddThreadGroupPrivateCheckBoxJ == null) {_AddThreadGroupPrivateCheckBoxJ = jQuery.Select("#" + clientId + "_AddThreadGroupPrivateCheckBox");}; return _AddThreadGroupPrivateCheckBoxJ;}} private jQueryObject _AddThreadGroupPrivateCheckBoxJ;
		public Element AddThreadNewsCheckBoxSpan {get {if (_AddThreadNewsCheckBoxSpan == null) {_AddThreadNewsCheckBoxSpan = (Element)Document.GetElementById(clientId + "_AddThreadNewsCheckBoxSpan");}; return _AddThreadNewsCheckBoxSpan;}} private Element _AddThreadNewsCheckBoxSpan;
		public jQueryObject AddThreadNewsCheckBoxSpanJ {get {if (_AddThreadNewsCheckBoxSpanJ == null) {_AddThreadNewsCheckBoxSpanJ = jQuery.Select("#" + clientId + "_AddThreadNewsCheckBoxSpan");}; return _AddThreadNewsCheckBoxSpanJ;}} private jQueryObject _AddThreadNewsCheckBoxSpanJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadNewsCheckBox {get {if (_AddThreadNewsCheckBox == null) {_AddThreadNewsCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadNewsCheckBox");}; return _AddThreadNewsCheckBox;}} private CheckBoxElement _AddThreadNewsCheckBox;
		public jQueryObject AddThreadNewsCheckBoxJ {get {if (_AddThreadNewsCheckBoxJ == null) {_AddThreadNewsCheckBoxJ = jQuery.Select("#" + clientId + "_AddThreadNewsCheckBox");}; return _AddThreadNewsCheckBoxJ;}} private jQueryObject _AddThreadNewsCheckBoxJ;
		public Element AddThreadSealedCheckBoxSpan {get {if (_AddThreadSealedCheckBoxSpan == null) {_AddThreadSealedCheckBoxSpan = (Element)Document.GetElementById(clientId + "_AddThreadSealedCheckBoxSpan");}; return _AddThreadSealedCheckBoxSpan;}} private Element _AddThreadSealedCheckBoxSpan;
		public jQueryObject AddThreadSealedCheckBoxSpanJ {get {if (_AddThreadSealedCheckBoxSpanJ == null) {_AddThreadSealedCheckBoxSpanJ = jQuery.Select("#" + clientId + "_AddThreadSealedCheckBoxSpan");}; return _AddThreadSealedCheckBoxSpanJ;}} private jQueryObject _AddThreadSealedCheckBoxSpanJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadSealedCheckBox {get {if (_AddThreadSealedCheckBox == null) {_AddThreadSealedCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadSealedCheckBox");}; return _AddThreadSealedCheckBox;}} private CheckBoxElement _AddThreadSealedCheckBox;
		public jQueryObject AddThreadSealedCheckBoxJ {get {if (_AddThreadSealedCheckBoxJ == null) {_AddThreadSealedCheckBoxJ = jQuery.Select("#" + clientId + "_AddThreadSealedCheckBox");}; return _AddThreadSealedCheckBoxJ;}} private jQueryObject _AddThreadSealedCheckBoxJ;
		public Element AddThreadInviteCheckBoxSpan {get {if (_AddThreadInviteCheckBoxSpan == null) {_AddThreadInviteCheckBoxSpan = (Element)Document.GetElementById(clientId + "_AddThreadInviteCheckBoxSpan");}; return _AddThreadInviteCheckBoxSpan;}} private Element _AddThreadInviteCheckBoxSpan;
		public jQueryObject AddThreadInviteCheckBoxSpanJ {get {if (_AddThreadInviteCheckBoxSpanJ == null) {_AddThreadInviteCheckBoxSpanJ = jQuery.Select("#" + clientId + "_AddThreadInviteCheckBoxSpan");}; return _AddThreadInviteCheckBoxSpanJ;}} private jQueryObject _AddThreadInviteCheckBoxSpanJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement AddThreadInviteCheckBox {get {if (_AddThreadInviteCheckBox == null) {_AddThreadInviteCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_AddThreadInviteCheckBox");}; return _AddThreadInviteCheckBox;}} private CheckBoxElement _AddThreadInviteCheckBox;
		public jQueryObject AddThreadInviteCheckBoxJ {get {if (_AddThreadInviteCheckBoxJ == null) {_AddThreadInviteCheckBoxJ = jQuery.Select("#" + clientId + "_AddThreadInviteCheckBox");}; return _AddThreadInviteCheckBoxJ;}} private jQueryObject _AddThreadInviteCheckBoxJ;
		public DivElement AddThreadInvitePanel {get {if (_AddThreadInvitePanel == null) {_AddThreadInvitePanel = (DivElement)Document.GetElementById(clientId + "_AddThreadInvitePanel");}; return _AddThreadInvitePanel;}} private DivElement _AddThreadInvitePanel;
		public jQueryObject AddThreadInvitePanelJ {get {if (_AddThreadInvitePanelJ == null) {_AddThreadInvitePanelJ = jQuery.Select("#" + clientId + "_AddThreadInvitePanel");}; return _AddThreadInvitePanelJ;}} private jQueryObject _AddThreadInvitePanelJ;
		public Js.Controls.MultiBuddyChooser.Controller uiMultiBuddyChooser {get {return (Js.Controls.MultiBuddyChooser.Controller) Script.Eval(clientId + "_uiMultiBuddyChooserController");}}
		public Element InlineScript1 {get {if (_InlineScript1 == null) {_InlineScript1 = (Element)Document.GetElementById(clientId + "_InlineScript1");}; return _InlineScript1;}} private Element _InlineScript1;
		public jQueryObject InlineScript1J {get {if (_InlineScript1J == null) {_InlineScript1J = jQuery.Select("#" + clientId + "_InlineScript1");}; return _InlineScript1J;}} private jQueryObject _InlineScript1J;//mappings.Add("Spotted.CustomControls.InlineScript", ElementGetter("Element"));
		public InputElement uiThreadK {get {if (_uiThreadK == null) {_uiThreadK = (InputElement)Document.GetElementById(clientId + "_uiThreadK");}; return _uiThreadK;}} private InputElement _uiThreadK;
		public jQueryObject uiThreadKJ {get {if (_uiThreadKJ == null) {_uiThreadKJ = jQuery.Select("#" + clientId + "_uiThreadK");}; return _uiThreadKJ;}} private jQueryObject _uiThreadKJ;
		public InputElement uiParentObjectK {get {if (_uiParentObjectK == null) {_uiParentObjectK = (InputElement)Document.GetElementById(clientId + "_uiParentObjectK");}; return _uiParentObjectK;}} private InputElement _uiParentObjectK;
		public jQueryObject uiParentObjectKJ {get {if (_uiParentObjectKJ == null) {_uiParentObjectKJ = jQuery.Select("#" + clientId + "_uiParentObjectK");}; return _uiParentObjectKJ;}} private jQueryObject _uiParentObjectKJ;
		public InputElement uiParentObjectType {get {if (_uiParentObjectType == null) {_uiParentObjectType = (InputElement)Document.GetElementById(clientId + "_uiParentObjectType");}; return _uiParentObjectType;}} private InputElement _uiParentObjectType;
		public jQueryObject uiParentObjectTypeJ {get {if (_uiParentObjectTypeJ == null) {_uiParentObjectTypeJ = jQuery.Select("#" + clientId + "_uiParentObjectType");}; return _uiParentObjectTypeJ;}} private jQueryObject _uiParentObjectTypeJ;
	}
}
