
=== DbButton.js ===
l5 -> $textTrue
l38 -> $altNow
l34 -> $confirmString
l36 -> $docNode
l21 -> $initialState
l39 -> $textNow
l30 -> $imgTrue
l18 -> $confirmStringFalse
l41 -> $oldState
l10 -> $imageWidth
l40 -> $args
l6 -> $textFalse
l33 -> $newState
l14 -> $initialStateString
l28 -> $textSpan
l13 -> $functionArgs
l11 -> $imageHeight
l23 -> $initialText
l26 -> $classAttribute
l9 -> $align
l37 -> $xmlhttp
l25 -> $styleAttribute
l1 -> $imageFileNameTrue
l29 -> $buttonHtml
l19 -> $writeToElementId
l22 -> $initialAlt
l4 -> $altFalse
l42 -> $doc
l8 -> $style
l2 -> $imageFileNameFalse
l0 -> $language
l24 -> $alignAttribute
l7 -> $class
l16 -> $onReturn
l20 -> $initialiseHtml
l32 -> $state
l12 -> $functionName
l3 -> $altTrue
l17 -> $confirmStringTrue
l27 -> $mouseOverAttribute
l15 -> $id
l35 -> $xmlDom
l31 -> $imgFalse

=== DsiPage.js ===

=== Helpers.js ===
l6 -> $txt
l8 -> $range
l0 -> $firstUnreadPage
l4 -> $textBox
l2 -> $objectType
l1 -> $type
l7 -> $isIE
l5 -> $usrK
l3 -> $objectTypeString

=== HitPhoto.js ===
l3 -> $doc
l7 -> $html
l5 -> $fav
l0 -> $k
l4 -> $photoK
l2 -> $docNode
l6 -> $me
l1 -> $xmlDom

=== HtmlControl.js ===

=== LoadData.js ===
l1 -> $firstRequest
l22 -> $dateTime
l34 -> $text
l55 -> $currentRequestId
l12 -> $privateMessageAlertName
l33 -> $k
l48 -> $usrKLol
l32 -> $stmu
l54 -> $privateMessageThreadK
l23 -> $pic
l25 -> $picIsPhoto
l19 -> $newMessageLastDateTime
l13 -> $privateMessageAlertText
l30 -> $privateChatUsrK
l21 -> $type
l38 -> $nameLocal
l9 -> $gotItems
l17 -> $newMessageHtml
l43 -> $invite
l31 -> $this
l20 -> $item
l18 -> $newChatLastDateTime
l3 -> $doc
l51 -> $usrPic
l2 -> $resetRequestId
l6 -> $results
l26 -> $picIsGroup
l0 -> $str
l28 -> $usrK
l10 -> $playSound
l24 -> $picPhotoK
l37 -> $alert
l7 -> $ticks
l35 -> $subject
l8 -> $items
l27 -> $name
l52 -> $class
l53 -> $notLoggedInHtml
l49 -> $picLol
l56 -> $tmp
l15 -> $privateMessageAlertUsrK
l44 -> $pmText
l14 -> $privateMessageAlertThreadK
l4 -> $redirect
l45 -> $groupName
l11 -> $privateMessageAlert
l46 -> $groupUrl
l41 -> $url
l36 -> $shortText
l29 -> $threadK
l16 -> $newChatHtml
l42 -> $usrKLocal
l40 -> $thread
l47 -> $link
l5 -> $resetTicks
l50 -> $eventName
l39 -> $picLocal

=== sarissa.js ===

=== XmlHelpers.js ===
l7 -> $xmlNode
l1 -> $objDOM
l10 -> $lsRegExp
l5 -> $newNode
l9 -> $psEncodeString
l6 -> $parentNode
l0 -> $objXmlHttp
l4 -> $nodeData
l8 -> $docTag
l2 -> $xmlDom
l3 -> $nodeName

=== GLOBAL ===
dbc31 -> ^NewPicName
dbc19 -> ^PicDivPrivate
dbc18 -> ^CurrentPicPrivate
dbc7 -> ^GetXML
dbc10 -> ^NodeText
dbc23 -> ^MessageDiv
dbc41 -> ^CreateNode
dbc30 -> ^CurrentRequestId
dbc3 -> ^CreateXmlDom
dbc33 -> ^TextBox
dbc20 -> ^PreviousChatLastDateTime
dbc25 -> ^PrivateMessages
dbc28 -> ^LastGuidPublic
dbc22 -> ^PreviousMessageLastDateTime
dbc15 -> ^ChatDivPrivate
dbc42 -> ^AppendNode
dbc43 -> ^UrlDecode
dbc2 -> ^DbChatDoneInit
dbc29 -> ^Timer
dbc37 -> ^Opera
dbc39 -> ^IE
dbc17 -> ^PicDiv
dbc5 -> ^CreateXmlHttp
dbc34 -> ^TextBoxPrivate
dbc16 -> ^CurrentPic
dbc6 -> ^ButtonReturn
dbc36 -> ^HasFocusPrivate
dbc32 -> ^NewPicDomain
dbc4 -> ^XmlInit
dbc35 -> ^HasFocus
dbc0 -> ^ButtonState
dbc26 -> ^PrivateChatDiv
dbc40 -> ^GetResponseXML
dbc21 -> ^ChatDiv
dbc14 -> ^CurrentUsrK
dbc1 -> ^DbChatSetLanguage
dbc12 -> ^LoadData
dbc27 -> ^LastGuid
dbc38 -> ^Moz
dbc8 -> ^HitPhotoXmlHttp
dbc11 -> ^HtmlEncode
dbc13 -> ^XmlhttpRefresh
dbc24 -> ^PrivateChatSpan
dbc9 -> ^HitPhotoReturn
