//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// <auto-generated>
//     This API code was generated by the DanDoes.NET Facebook API Generator.
//     Facebook.Api.Generator v1.0.3412.20062
//     
//     The following documents were used to generate this code:
//		Facebook API Object Schema:	http://api.facebook.com/1.0/facebook.xsd
//		Facebook API Wiki:			http://wiki.developers.facebook.com/index.php/API
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facebook.Api {
    using System;
    using System.Collections.Generic;
    using System.Xml.Linq;
    using Facebook;
    
    
    [FacebookObjectAttribute("group_members")]
    public class GroupMembers : Facebook.Api.FacebookObjectBase {
        
        /// <summary>Intializes an instance of <see cref="GroupMembers" /> using the specified xml document or snippet as the data source.</summary>
        /// <param name="content">An <see cref="XElement" /> object containing xml data for the object.</param>
        public GroupMembers(System.Xml.Linq.XElement content) : 
                base(content) {
        }
        
        /// <summary>Intializes an instance of <see cref="GroupMembers" />, prefilling the internal dictionary with the specified values.</summary>
        /// <param name="dict">An <see cref="IDictionary{String, Object}" /> object containing property names and values.</param>
        public GroupMembers(System.Collections.Generic.IDictionary<string, object> dict) : 
                base(dict) {
        }
        
        /// <summary>Intializes an instance of <see cref="GroupMembers" />.</summary>
        public GroupMembers() {
        }
        
        public List<Int64> Members {
            get {
                return this.GetValueTypeCollection<Int64>("members", "uid");
            }
            set {
                this.InnerDictionary["members"] = value;
            }
        }
        
        public List<Int64> Admins {
            get {
                return this.GetValueTypeCollection<Int64>("admins", "uid");
            }
            set {
                this.InnerDictionary["admins"] = value;
            }
        }
        
        public List<Int64> Officers {
            get {
                return this.GetValueTypeCollection<Int64>("officers", "uid");
            }
            set {
                this.InnerDictionary["officers"] = value;
            }
        }
        
        public List<Int64> NotReplied {
            get {
                return this.GetValueTypeCollection<Int64>("not_replied", "uid");
            }
            set {
                this.InnerDictionary["not_replied"] = value;
            }
        }
    }
}
