//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// <auto-generated>
//     This API code was generated by the DanDoes.NET Facebook API Generator.
//     Facebook.Api.Generator v1.0.3412.20062
//     
//     The following documents were used to generate this code:
//		Facebook API Object Schema:	http://api.facebook.com/1.0/facebook.xsd
//		Facebook API Wiki:			http://wiki.developers.facebook.com/index.php/API
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facebook.Api {
    using System;
    using System.Collections.Generic;
    using System.Xml.Linq;
    using Facebook;
    
    
    [FacebookObjectAttribute("link")]
    public class Link : Facebook.Api.FacebookObjectBase {
        
        /// <summary>Intializes an instance of <see cref="Link" /> using the specified xml document or snippet as the data source.</summary>
        /// <param name="content">An <see cref="XElement" /> object containing xml data for the object.</param>
        public Link(System.Xml.Linq.XElement content) : 
                base(content) {
        }
        
        /// <summary>Intializes an instance of <see cref="Link" />, prefilling the internal dictionary with the specified values.</summary>
        /// <param name="dict">An <see cref="IDictionary{String, Object}" /> object containing property names and values.</param>
        public Link(System.Collections.Generic.IDictionary<string, object> dict) : 
                base(dict) {
        }
        
        /// <summary>Intializes an instance of <see cref="Link" />.</summary>
        public Link() {
        }
        
        public Int64 LinkId {
            get {
                return this.GetValueType<Int64>("link_id");
            }
            set {
                this.InnerDictionary["link_id"] = value;
            }
        }
        
        public Int64 Owner {
            get {
                return this.GetValueType<Int64>("owner");
            }
            set {
                this.InnerDictionary["owner"] = value;
            }
        }
        
        public String OwnerComment {
            get {
                return this.GetString("owner_comment");
            }
            set {
                this.InnerDictionary["owner_comment"] = value;
            }
        }
        
        public DateTime CreatedTime {
            get {
                return this.GetValueType<DateTime>("created_time");
            }
            set {
                this.InnerDictionary["created_time"] = value;
            }
        }
        
        public String Title {
            get {
                return this.GetString("title");
            }
            set {
                this.InnerDictionary["title"] = value;
            }
        }
        
        public String Summary {
            get {
                return this.GetString("summary");
            }
            set {
                this.InnerDictionary["summary"] = value;
            }
        }
        
        public String Url {
            get {
                return this.GetString("url");
            }
            set {
                this.InnerDictionary["url"] = value;
            }
        }
        
        public List<String> ImageUrls {
            get {
                return this.GetStringCollection("image_urls", "string");
            }
            set {
                this.InnerDictionary["image_urls"] = value;
            }
        }
    }
}
