//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// <auto-generated>
//     This API code was generated by the DanDoes.NET Facebook API Generator.
//     Facebook.Api.Generator v1.0.3412.20062
//     
//     The following documents were used to generate this code:
//		Facebook API Object Schema:	http://api.facebook.com/1.0/facebook.xsd
//		Facebook API Wiki:			http://wiki.developers.facebook.com/index.php/API
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facebook.Api {
    using System;
    using System.Collections.Generic;
    using System.Xml.Linq;
    using Facebook;
    
    
    [FacebookObjectAttribute("metrics")]
    public class Metrics : Facebook.Api.FacebookObjectBase {
        
        /// <summary>Intializes an instance of <see cref="Metrics" /> using the specified xml document or snippet as the data source.</summary>
        /// <param name="content">An <see cref="XElement" /> object containing xml data for the object.</param>
        public Metrics(System.Xml.Linq.XElement content) : 
                base(content) {
        }
        
        /// <summary>Intializes an instance of <see cref="Metrics" />, prefilling the internal dictionary with the specified values.</summary>
        /// <param name="dict">An <see cref="IDictionary{String, Object}" /> object containing property names and values.</param>
        public Metrics(System.Collections.Generic.IDictionary<string, object> dict) : 
                base(dict) {
        }
        
        /// <summary>Intializes an instance of <see cref="Metrics" />.</summary>
        public Metrics() {
        }
        
        public DateTime EndTime {
            get {
                return this.GetValueType<DateTime>("end_time");
            }
            set {
                this.InnerDictionary["end_time"] = value;
            }
        }
        
        public Int64 ActiveUsers {
            get {
                return this.GetValueType<Int64>("active_users");
            }
            set {
                this.InnerDictionary["active_users"] = value;
            }
        }
        
        public Int64 ApiCalls {
            get {
                return this.GetValueType<Int64>("api_calls");
            }
            set {
                this.InnerDictionary["api_calls"] = value;
            }
        }
        
        public Int64 UniqueApiCalls {
            get {
                return this.GetValueType<Int64>("unique_api_calls");
            }
            set {
                this.InnerDictionary["unique_api_calls"] = value;
            }
        }
        
        public Int64 CanvasPageViews {
            get {
                return this.GetValueType<Int64>("canvas_page_views");
            }
            set {
                this.InnerDictionary["canvas_page_views"] = value;
            }
        }
        
        public Int64 UniqueCanvasPageViews {
            get {
                return this.GetValueType<Int64>("unique_canvas_page_views");
            }
            set {
                this.InnerDictionary["unique_canvas_page_views"] = value;
            }
        }
        
        public Int64 CanvasHttpRequestTimeAvg {
            get {
                return this.GetValueType<Int64>("canvas_http_request_time_avg");
            }
            set {
                this.InnerDictionary["canvas_http_request_time_avg"] = value;
            }
        }
        
        public Int64 CanvasFbmlRenderTimeAvg {
            get {
                return this.GetValueType<Int64>("canvas_fbml_render_time_avg");
            }
            set {
                this.InnerDictionary["canvas_fbml_render_time_avg"] = value;
            }
        }
        
        public Int64 UniqueAdds {
            get {
                return this.GetValueType<Int64>("unique_adds");
            }
            set {
                this.InnerDictionary["unique_adds"] = value;
            }
        }
        
        public Int64 UniqueRemoves {
            get {
                return this.GetValueType<Int64>("unique_removes");
            }
            set {
                this.InnerDictionary["unique_removes"] = value;
            }
        }
        
        public Int64 UniqueBlocks {
            get {
                return this.GetValueType<Int64>("unique_blocks");
            }
            set {
                this.InnerDictionary["unique_blocks"] = value;
            }
        }
        
        public Int64 UniqueUnblocks {
            get {
                return this.GetValueType<Int64>("unique_unblocks");
            }
            set {
                this.InnerDictionary["unique_unblocks"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_0 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_0");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_0"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_100 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_100");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_100"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_200 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_200");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_200"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCodeND2 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_200ND");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_200ND"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_301 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_301");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_301"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_302 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_302");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_302"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_303 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_303");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_303"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_400 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_400");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_400"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_401 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_401");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_401"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_402 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_402");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_402"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_403 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_403");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_403"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_404 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_404");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_404"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_405 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_405");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_405"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_413 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_413");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_413"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_422 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_422");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_422"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_500 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_500");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_500"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_502 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_502");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_502"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_503 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_503");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_503"] = value;
            }
        }
        
        public Int64 CanvasPageViewsHttpCode_505 {
            get {
                return this.GetValueType<Int64>("canvas_page_views_http_code_505");
            }
            set {
                this.InnerDictionary["canvas_page_views_http_code_505"] = value;
            }
        }
    }
}
