//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// <auto-generated>
//     This API code was generated by the DanDoes.NET Facebook API Generator.
//     Facebook.Api.Generator v1.0.3412.20062
//     
//     The following documents were used to generate this code:
//		Facebook API Object Schema:	http://api.facebook.com/1.0/facebook.xsd
//		Facebook API Wiki:			http://wiki.developers.facebook.com/index.php/API
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facebook.Api {
    using System;
    using System.Collections.Generic;
    using System.Xml.Linq;
    using Facebook;
    
    
    [FacebookObjectAttribute("user_status")]
    public class UserStatus : Facebook.Api.FacebookObjectBase {
        
        /// <summary>Intializes an instance of <see cref="UserStatus" /> using the specified xml document or snippet as the data source.</summary>
        /// <param name="content">An <see cref="XElement" /> object containing xml data for the object.</param>
        public UserStatus(System.Xml.Linq.XElement content) : 
                base(content) {
        }
        
        /// <summary>Intializes an instance of <see cref="UserStatus" />, prefilling the internal dictionary with the specified values.</summary>
        /// <param name="dict">An <see cref="IDictionary{String, Object}" /> object containing property names and values.</param>
        public UserStatus(System.Collections.Generic.IDictionary<string, object> dict) : 
                base(dict) {
        }
        
        /// <summary>Intializes an instance of <see cref="UserStatus" />.</summary>
        public UserStatus() {
        }
        
        public String Message {
            get {
                return this.GetString("message");
            }
            set {
                this.InnerDictionary["message"] = value;
            }
        }
        
        public DateTime Time {
            get {
                return this.GetValueType<DateTime>("time");
            }
            set {
                this.InnerDictionary["time"] = value;
            }
        }
        
        public Int64 StatusId {
            get {
                return this.GetValueType<Int64>("status_id");
            }
            set {
                this.InnerDictionary["status_id"] = value;
            }
        }
        
        public String Source {
            get {
                return this.GetString("source");
            }
            set {
                this.InnerDictionary["source"] = value;
            }
        }
        
        public Int64 Uid {
            get {
                return this.GetValueType<Int64>("uid");
            }
            set {
                this.InnerDictionary["uid"] = value;
            }
        }
        
        public Int64 CommentCount {
            get {
                return this.GetValueType<Int64>("comment_count");
            }
            set {
                this.InnerDictionary["comment_count"] = value;
            }
        }
    }
}
