//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// <auto-generated>
//     This API code was generated by the DanDoes.NET Facebook API Generator.
//     Facebook.Api.Generator v1.0.3412.20062
//     
//     The following documents were used to generate this code:
//		Facebook API Object Schema:	http://api.facebook.com/1.0/facebook.xsd
//		Facebook API Wiki:			http://wiki.developers.facebook.com/index.php/API
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facebook.Api {
    using System;
    using System.Collections.Generic;
    using System.Xml.Linq;
    using Facebook;
    
    
    /// <summary>Represents user data returned by the Users.GetInfo() method.</summary>
    [FacebookObjectAttribute("user")]
    public class User : Facebook.Api.FacebookObjectBase {
        
        /// <summary>Intializes an instance of <see cref="User" /> using the specified xml document or snippet as the data source.</summary>
        /// <param name="content">An <see cref="XElement" /> object containing xml data for the object.</param>
        public User(System.Xml.Linq.XElement content) : 
                base(content) {
        }
        
        /// <summary>Intializes an instance of <see cref="User" />, prefilling the internal dictionary with the specified values.</summary>
        /// <param name="dict">An <see cref="IDictionary{String, Object}" /> object containing property names and values.</param>
        public User(System.Collections.Generic.IDictionary<string, object> dict) : 
                base(dict) {
        }
        
        /// <summary>Intializes an instance of <see cref="User" />.</summary>
        public User() {
        }
        
        /// <summary>Gets or sets data found in the "About Me" section of a user's profile.</summary>
        public String AboutMe {
            get {
                return this.GetString("about_me");
            }
            set {
                this.InnerDictionary["about_me"] = value;
            }
        }
        
        public String Activities {
            get {
                return this.GetString("activities");
            }
            set {
                this.InnerDictionary["activities"] = value;
            }
        }
        
        public FacebookList<Affiliation> Affiliations {
            get {
                return this.GetFacebookObjectCollection<Affiliation>("affiliations");
            }
            set {
                this.InnerDictionary["affiliations"] = value;
            }
        }
        
        public String Birthday {
            get {
                return this.GetString("birthday");
            }
            set {
                this.InnerDictionary["birthday"] = value;
            }
        }

		public String Email
		{
			get
			{
				return this.GetString("email");
			}
			set
			{
				this.InnerDictionary["email"] = value;
			}
		}

        public String Books {
            get {
                return this.GetString("books");
            }
            set {
                this.InnerDictionary["books"] = value;
            }
        }
        
        public Location CurrentLocation {
            get {
                return this.GetFacebookObject<Location>("current_location");
            }
            set {
                this.InnerDictionary["current_location"] = value;
            }
        }
        
        public FacebookList<EducationInfo> EducationHistory {
            get {
                return this.GetFacebookObjectCollection<EducationInfo>("education_history");
            }
            set {
                this.InnerDictionary["education_history"] = value;
            }
        }
        
        public String FirstName {
            get {
                return this.GetString("first_name");
            }
            set {
                this.InnerDictionary["first_name"] = value;
            }
        }
        
        public Location HometownLocation {
            get {
                return this.GetFacebookObject<Location>("hometown_location");
            }
            set {
                this.InnerDictionary["hometown_location"] = value;
            }
        }
        
        public HsInfo HsInfo {
            get {
                return this.GetFacebookObject<HsInfo>("hs_info");
            }
            set {
                this.InnerDictionary["hs_info"] = value;
            }
        }
        
        public String Interests {
            get {
                return this.GetString("interests");
            }
            set {
                this.InnerDictionary["interests"] = value;
            }
        }
        
        public Boolean IsAppUser {
            get {
                return this.GetValueType<Boolean>("is_app_user");
            }
            set {
                this.InnerDictionary["is_app_user"] = value;
            }
        }
        
        public String LastName {
            get {
                return this.GetString("last_name");
            }
            set {
                this.InnerDictionary["last_name"] = value;
            }
        }
        
        public List<String> MeetingFor {
            get {
                return this.GetStringCollection("meeting_for", "seeking");
            }
            set {
                this.InnerDictionary["meeting_for"] = value;
            }
        }
        
        public List<String> MeetingSex {
            get {
                return this.GetStringCollection("meeting_sex", "sex");
            }
            set {
                this.InnerDictionary["meeting_sex"] = value;
            }
        }
        
        public String Movies {
            get {
                return this.GetString("movies");
            }
            set {
                this.InnerDictionary["movies"] = value;
            }
        }
        
        public String Music {
            get {
                return this.GetString("music");
            }
            set {
                this.InnerDictionary["music"] = value;
            }
        }
        
        public String Name {
            get {
                return this.GetString("name");
            }
            set {
                this.InnerDictionary["name"] = value;
            }
        }
        
        public Int64 NotesCount {
            get {
                return this.GetValueType<Int64>("notes_count");
            }
            set {
                this.InnerDictionary["notes_count"] = value;
            }
        }
        
        public String Pic {
            get {
                return this.GetString("pic");
            }
            set {
                this.InnerDictionary["pic"] = value;
            }
        }
        
        public String PicBig {
            get {
                return this.GetString("pic_big");
            }
            set {
                this.InnerDictionary["pic_big"] = value;
            }
        }
        
        public String PicSmall {
            get {
                return this.GetString("pic_small");
            }
            set {
                this.InnerDictionary["pic_small"] = value;
            }
        }
        
        public String Political {
            get {
                return this.GetString("political");
            }
            set {
                this.InnerDictionary["political"] = value;
            }
        }
        
        public DateTime ProfileUpdateTime {
            get {
                return this.GetValueType<DateTime>("profile_update_time");
            }
            set {
                this.InnerDictionary["profile_update_time"] = value;
            }
        }
        
        public String Quotes {
            get {
                return this.GetString("quotes");
            }
            set {
                this.InnerDictionary["quotes"] = value;
            }
        }
        
        public String RelationshipStatus {
            get {
                return this.GetString("relationship_status");
            }
            set {
                this.InnerDictionary["relationship_status"] = value;
            }
        }
        
        public String Religion {
            get {
                return this.GetString("religion");
            }
            set {
                this.InnerDictionary["religion"] = value;
            }
        }
        
        public String Sex {
            get {
                return this.GetString("sex");
            }
            set {
                this.InnerDictionary["sex"] = value;
            }
        }
        
        public Int64 SignificantOtherId {
            get {
                return this.GetValueType<Int64>("significant_other_id");
            }
            set {
                this.InnerDictionary["significant_other_id"] = value;
            }
        }
        
        public UserStatus Status {
            get {
                return this.GetFacebookObject<UserStatus>("status");
            }
            set {
                this.InnerDictionary["status"] = value;
            }
        }
        
        public Decimal Timezone {
            get {
                return this.GetValueType<Decimal>("timezone");
            }
            set {
                this.InnerDictionary["timezone"] = value;
            }
        }
        
        public String Tv {
            get {
                return this.GetString("tv");
            }
            set {
                this.InnerDictionary["tv"] = value;
            }
        }
        
        public Int64 Uid {
            get {
                return this.GetValueType<Int64>("uid");
            }
            set {
                this.InnerDictionary["uid"] = value;
            }
        }
        
        public Int64 WallCount {
            get {
                return this.GetValueType<Int64>("wall_count");
            }
            set {
                this.InnerDictionary["wall_count"] = value;
            }
        }
        
        public FacebookList<WorkInfo> WorkHistory {
            get {
                return this.GetFacebookObjectCollection<WorkInfo>("work_history");
            }
            set {
                this.InnerDictionary["work_history"] = value;
            }
        }
        
        public String PicSquare {
            get {
                return this.GetString("pic_square");
            }
            set {
                this.InnerDictionary["pic_square"] = value;
            }
        }
        
        public Boolean HasAddedApp {
            get {
                return this.GetValueType<Boolean>("has_added_app");
            }
            set {
                this.InnerDictionary["has_added_app"] = value;
            }
        }
        
        public List<String> EmailHashes {
            get {
                return this.GetStringCollection("email_hashes", "string");
            }
            set {
                this.InnerDictionary["email_hashes"] = value;
            }
        }
        
        public String Locale {
            get {
                return this.GetString("locale");
            }
            set {
                this.InnerDictionary["locale"] = value;
            }
        }
    }
}
