//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// <auto-generated>
//     This API code was generated by the DanDoes.NET Facebook API Generator.
//     Facebook.Api.Generator v1.0.3412.20062
//     
//     The following documents were used to generate this code:
//		Facebook API Object Schema:	http://api.facebook.com/1.0/facebook.xsd
//		Facebook API Wiki:			http://wiki.developers.facebook.com/index.php/API
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facebook.Api {
    using System;
    using System.Collections.Generic;
    using System.Xml.Linq;
    using Facebook;
    
    
    [FacebookObjectAttribute("work_info")]
    public class WorkInfo : Facebook.Api.FacebookObjectBase {
        
        /// <summary>Intializes an instance of <see cref="WorkInfo" /> using the specified xml document or snippet as the data source.</summary>
        /// <param name="content">An <see cref="XElement" /> object containing xml data for the object.</param>
        public WorkInfo(System.Xml.Linq.XElement content) : 
                base(content) {
        }
        
        /// <summary>Intializes an instance of <see cref="WorkInfo" />, prefilling the internal dictionary with the specified values.</summary>
        /// <param name="dict">An <see cref="IDictionary{String, Object}" /> object containing property names and values.</param>
        public WorkInfo(System.Collections.Generic.IDictionary<string, object> dict) : 
                base(dict) {
        }
        
        /// <summary>Intializes an instance of <see cref="WorkInfo" />.</summary>
        public WorkInfo() {
        }
        
        public Location Location {
            get {
                return this.GetFacebookObject<Location>("location");
            }
            set {
                this.InnerDictionary["location"] = value;
            }
        }
        
        public String CompanyName {
            get {
                return this.GetString("company_name");
            }
            set {
                this.InnerDictionary["company_name"] = value;
            }
        }
        
        public String Position {
            get {
                return this.GetString("position");
            }
            set {
                this.InnerDictionary["position"] = value;
            }
        }
        
        public String Description {
            get {
                return this.GetString("description");
            }
            set {
                this.InnerDictionary["description"] = value;
            }
        }
        
        public DateTime StartDate {
            get {
                return this.GetValueType<DateTime>("start_date");
            }
            set {
                this.InnerDictionary["start_date"] = value;
            }
        }
        
        public DateTime EndDate {
            get {
                return this.GetValueType<DateTime>("end_date");
            }
            set {
                this.InnerDictionary["end_date"] = value;
            }
        }
    }
}
