IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Article' AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.Article ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Article', N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Brand'   AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.Brand   ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Brand',   N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Comp'    AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.Comp    ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Comp',    N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Event'   AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.Event   ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Event',   N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Group'   AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.[Group] ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Group',   N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Place'   AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.[Place] ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Place',   N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Usr'     AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.Usr     ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Usr',     N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Venue'   AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.Venue   ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Venue',   N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Para'    AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.Para    ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Para',    N'COLUMN', N'DoneAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Misc'    AND	[column].name = 'DoneAmazonPix') BEGIN ALTER TABLE dbo.Misc    ADD DoneAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file been uploaded to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Misc',    N'COLUMN', N'DoneAmazonPix' END

