IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Photo'   AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Photo   ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Photo',   N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Article' AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Article ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Article', N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Brand'   AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Brand   ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Brand',   N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Comp'    AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Comp    ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Comp',    N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Event'   AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Event   ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Event',   N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Group'   AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.[Group] ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Group',   N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Place'   AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.[Place] ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Place',   N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Usr'     AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Usr     ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Usr',     N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Venue'   AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Venue   ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Venue',   N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Para'    AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Para    ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Para',    N'COLUMN', N'FailedAmazonPix' END
IF NOT EXISTS( SELECT * FROM sys.tables [table] INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id WHERE [table].name = 'Misc'    AND	[column].name = 'FailedAmazonPix') BEGIN ALTER TABLE dbo.Misc    ADD FailedAmazonPix bit NULL EXECUTE sp_addextendedproperty N'MS_Description', N'Has the Pix file failed to upload to Amazon?', N'SCHEMA', N'dbo', N'TABLE', N'Misc',    N'COLUMN', N'FailedAmazonPix' END

