IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[Photo]') AND name = N'PhotoOfWeekUser')
CREATE NONCLUSTERED INDEX [PhotoOfWeekUser] ON [Photo] 
(
	[PhotoOfWeekUser] DESC,
	[PhotoOfWeekDateTime] DESC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
