

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/

/*
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
DROP INDEX IX_Usr_FacebookUID ON dbo.Usr
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Usr_FacebookUID ON dbo.Usr
	(
	FacebookUID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY]
GO
COMMIT
*/
