//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.Literal", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using jQueryApi;
using Js.Library;

namespace Js.Controls.BuddyImporter
{
	public partial class View
	{
		public string clientId;
		public View(string clientId)
		{
			this.clientId = clientId;
		}
		public DivElement uiEmailCredentialsPanel {get {if (_uiEmailCredentialsPanel == null) {_uiEmailCredentialsPanel = (DivElement)Document.GetElementById(clientId + "_uiEmailCredentialsPanel");}; return _uiEmailCredentialsPanel;}} private DivElement _uiEmailCredentialsPanel;
		public jQueryObject uiEmailCredentialsPanelJ {get {if (_uiEmailCredentialsPanelJ == null) {_uiEmailCredentialsPanelJ = jQuery.Select("#" + clientId + "_uiEmailCredentialsPanel");}; return _uiEmailCredentialsPanelJ;}} private jQueryObject _uiEmailCredentialsPanelJ;
		public InputElement uiEmailText {get {if (_uiEmailText == null) {_uiEmailText = (InputElement)Document.GetElementById(clientId + "_uiEmailText");}; return _uiEmailText;}} private InputElement _uiEmailText;
		public jQueryObject uiEmailTextJ {get {if (_uiEmailTextJ == null) {_uiEmailTextJ = jQuery.Select("#" + clientId + "_uiEmailText");}; return _uiEmailTextJ;}} private jQueryObject _uiEmailTextJ;
		public SelectElement uiEmailProviderDropDown {get {if (_uiEmailProviderDropDown == null) {_uiEmailProviderDropDown = (SelectElement)Document.GetElementById(clientId + "_uiEmailProviderDropDown");}; return _uiEmailProviderDropDown;}} private SelectElement _uiEmailProviderDropDown;
		public jQueryObject uiEmailProviderDropDownJ {get {if (_uiEmailProviderDropDownJ == null) {_uiEmailProviderDropDownJ = jQuery.Select("#" + clientId + "_uiEmailProviderDropDown");}; return _uiEmailProviderDropDownJ;}} private jQueryObject _uiEmailProviderDropDownJ;
		public InputElement uiPasswordText {get {if (_uiPasswordText == null) {_uiPasswordText = (InputElement)Document.GetElementById(clientId + "_uiPasswordText");}; return _uiPasswordText;}} private InputElement _uiPasswordText;
		public jQueryObject uiPasswordTextJ {get {if (_uiPasswordTextJ == null) {_uiPasswordTextJ = jQuery.Select("#" + clientId + "_uiPasswordText");}; return _uiPasswordTextJ;}} private jQueryObject _uiPasswordTextJ;
		public Element uiErrorBadCredentialsLabel {get {if (_uiErrorBadCredentialsLabel == null) {_uiErrorBadCredentialsLabel = (Element)Document.GetElementById(clientId + "_uiErrorBadCredentialsLabel");}; return _uiErrorBadCredentialsLabel;}} private Element _uiErrorBadCredentialsLabel;
		public jQueryObject uiErrorBadCredentialsLabelJ {get {if (_uiErrorBadCredentialsLabelJ == null) {_uiErrorBadCredentialsLabelJ = jQuery.Select("#" + clientId + "_uiErrorBadCredentialsLabel");}; return _uiErrorBadCredentialsLabelJ;}} private jQueryObject _uiErrorBadCredentialsLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiErrorUnknownEmailProvider {get {if (_uiErrorUnknownEmailProvider == null) {_uiErrorUnknownEmailProvider = (Element)Document.GetElementById(clientId + "_uiErrorUnknownEmailProvider");}; return _uiErrorUnknownEmailProvider;}} private Element _uiErrorUnknownEmailProvider;
		public jQueryObject uiErrorUnknownEmailProviderJ {get {if (_uiErrorUnknownEmailProviderJ == null) {_uiErrorUnknownEmailProviderJ = jQuery.Select("#" + clientId + "_uiErrorUnknownEmailProvider");}; return _uiErrorUnknownEmailProviderJ;}} private jQueryObject _uiErrorUnknownEmailProviderJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public InputElement uiGetEmailContactsButton {get {if (_uiGetEmailContactsButton == null) {_uiGetEmailContactsButton = (InputElement)Document.GetElementById(clientId + "_uiGetEmailContactsButton");}; return _uiGetEmailContactsButton;}} private InputElement _uiGetEmailContactsButton;
		public jQueryObject uiGetEmailContactsButtonJ {get {if (_uiGetEmailContactsButtonJ == null) {_uiGetEmailContactsButtonJ = jQuery.Select("#" + clientId + "_uiGetEmailContactsButton");}; return _uiGetEmailContactsButtonJ;}} private jQueryObject _uiGetEmailContactsButtonJ;
		public DivElement uiSelectContactsPanel {get {if (_uiSelectContactsPanel == null) {_uiSelectContactsPanel = (DivElement)Document.GetElementById(clientId + "_uiSelectContactsPanel");}; return _uiSelectContactsPanel;}} private DivElement _uiSelectContactsPanel;
		public jQueryObject uiSelectContactsPanelJ {get {if (_uiSelectContactsPanelJ == null) {_uiSelectContactsPanelJ = jQuery.Select("#" + clientId + "_uiSelectContactsPanel");}; return _uiSelectContactsPanelJ;}} private jQueryObject _uiSelectContactsPanelJ;
		public Element uiAlreadyBuddiesLabel {get {if (_uiAlreadyBuddiesLabel == null) {_uiAlreadyBuddiesLabel = (Element)Document.GetElementById(clientId + "_uiAlreadyBuddiesLabel");}; return _uiAlreadyBuddiesLabel;}} private Element _uiAlreadyBuddiesLabel;
		public jQueryObject uiAlreadyBuddiesLabelJ {get {if (_uiAlreadyBuddiesLabelJ == null) {_uiAlreadyBuddiesLabelJ = jQuery.Select("#" + clientId + "_uiAlreadyBuddiesLabel");}; return _uiAlreadyBuddiesLabelJ;}} private jQueryObject _uiAlreadyBuddiesLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiNonBuddyMembersLabel {get {if (_uiNonBuddyMembersLabel == null) {_uiNonBuddyMembersLabel = (Element)Document.GetElementById(clientId + "_uiNonBuddyMembersLabel");}; return _uiNonBuddyMembersLabel;}} private Element _uiNonBuddyMembersLabel;
		public jQueryObject uiNonBuddyMembersLabelJ {get {if (_uiNonBuddyMembersLabelJ == null) {_uiNonBuddyMembersLabelJ = jQuery.Select("#" + clientId + "_uiNonBuddyMembersLabel");}; return _uiNonBuddyMembersLabelJ;}} private jQueryObject _uiNonBuddyMembersLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public CheckBoxElement uiToggleSelectAllMemberContactsCheckBox {get {if (_uiToggleSelectAllMemberContactsCheckBox == null) {_uiToggleSelectAllMemberContactsCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_uiToggleSelectAllMemberContactsCheckBox");}; return _uiToggleSelectAllMemberContactsCheckBox;}} private CheckBoxElement _uiToggleSelectAllMemberContactsCheckBox;
		public jQueryObject uiToggleSelectAllMemberContactsCheckBoxJ {get {if (_uiToggleSelectAllMemberContactsCheckBoxJ == null) {_uiToggleSelectAllMemberContactsCheckBoxJ = jQuery.Select("#" + clientId + "_uiToggleSelectAllMemberContactsCheckBox");}; return _uiToggleSelectAllMemberContactsCheckBoxJ;}} private jQueryObject _uiToggleSelectAllMemberContactsCheckBoxJ;
		public Element uiSelectMemberContactsDiv {get {if (_uiSelectMemberContactsDiv == null) {_uiSelectMemberContactsDiv = (Element)Document.GetElementById(clientId + "_uiSelectMemberContactsDiv");}; return _uiSelectMemberContactsDiv;}} private Element _uiSelectMemberContactsDiv;
		public jQueryObject uiSelectMemberContactsDivJ {get {if (_uiSelectMemberContactsDivJ == null) {_uiSelectMemberContactsDivJ = jQuery.Select("#" + clientId + "_uiSelectMemberContactsDiv");}; return _uiSelectMemberContactsDivJ;}} private jQueryObject _uiSelectMemberContactsDivJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element uiSelectMemberContactsGridView {get {if (_uiSelectMemberContactsGridView == null) {_uiSelectMemberContactsGridView = (Element)Document.GetElementById(clientId + "_uiSelectMemberContactsGridView");}; return _uiSelectMemberContactsGridView;}} private Element _uiSelectMemberContactsGridView;
		public jQueryObject uiSelectMemberContactsGridViewJ {get {if (_uiSelectMemberContactsGridViewJ == null) {_uiSelectMemberContactsGridViewJ = jQuery.Select("#" + clientId + "_uiSelectMemberContactsGridView");}; return _uiSelectMemberContactsGridViewJ;}} private jQueryObject _uiSelectMemberContactsGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public Element uiNonMembersLabel {get {if (_uiNonMembersLabel == null) {_uiNonMembersLabel = (Element)Document.GetElementById(clientId + "_uiNonMembersLabel");}; return _uiNonMembersLabel;}} private Element _uiNonMembersLabel;
		public jQueryObject uiNonMembersLabelJ {get {if (_uiNonMembersLabelJ == null) {_uiNonMembersLabelJ = jQuery.Select("#" + clientId + "_uiNonMembersLabel");}; return _uiNonMembersLabelJ;}} private jQueryObject _uiNonMembersLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public CheckBoxElement uiToggleSelectAllNonMemberContactsCheckBox {get {if (_uiToggleSelectAllNonMemberContactsCheckBox == null) {_uiToggleSelectAllNonMemberContactsCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_uiToggleSelectAllNonMemberContactsCheckBox");}; return _uiToggleSelectAllNonMemberContactsCheckBox;}} private CheckBoxElement _uiToggleSelectAllNonMemberContactsCheckBox;
		public jQueryObject uiToggleSelectAllNonMemberContactsCheckBoxJ {get {if (_uiToggleSelectAllNonMemberContactsCheckBoxJ == null) {_uiToggleSelectAllNonMemberContactsCheckBoxJ = jQuery.Select("#" + clientId + "_uiToggleSelectAllNonMemberContactsCheckBox");}; return _uiToggleSelectAllNonMemberContactsCheckBoxJ;}} private jQueryObject _uiToggleSelectAllNonMemberContactsCheckBoxJ;
		public Element uiSelectNonMemberContactsDiv {get {if (_uiSelectNonMemberContactsDiv == null) {_uiSelectNonMemberContactsDiv = (Element)Document.GetElementById(clientId + "_uiSelectNonMemberContactsDiv");}; return _uiSelectNonMemberContactsDiv;}} private Element _uiSelectNonMemberContactsDiv;
		public jQueryObject uiSelectNonMemberContactsDivJ {get {if (_uiSelectNonMemberContactsDivJ == null) {_uiSelectNonMemberContactsDivJ = jQuery.Select("#" + clientId + "_uiSelectNonMemberContactsDiv");}; return _uiSelectNonMemberContactsDivJ;}} private jQueryObject _uiSelectNonMemberContactsDivJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element uiSelectNonMemberContactsGridView {get {if (_uiSelectNonMemberContactsGridView == null) {_uiSelectNonMemberContactsGridView = (Element)Document.GetElementById(clientId + "_uiSelectNonMemberContactsGridView");}; return _uiSelectNonMemberContactsGridView;}} private Element _uiSelectNonMemberContactsGridView;
		public jQueryObject uiSelectNonMemberContactsGridViewJ {get {if (_uiSelectNonMemberContactsGridViewJ == null) {_uiSelectNonMemberContactsGridViewJ = jQuery.Select("#" + clientId + "_uiSelectNonMemberContactsGridView");}; return _uiSelectNonMemberContactsGridViewJ;}} private jQueryObject _uiSelectNonMemberContactsGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public DivElement uiSuccess {get {if (_uiSuccess == null) {_uiSuccess = (DivElement)Document.GetElementById(clientId + "_uiSuccess");}; return _uiSuccess;}} private DivElement _uiSuccess;
		public jQueryObject uiSuccessJ {get {if (_uiSuccessJ == null) {_uiSuccessJ = jQuery.Select("#" + clientId + "_uiSuccess");}; return _uiSuccessJ;}} private jQueryObject _uiSuccessJ;
		public Element uiNoContactsAddedLabel {get {if (_uiNoContactsAddedLabel == null) {_uiNoContactsAddedLabel = (Element)Document.GetElementById(clientId + "_uiNoContactsAddedLabel");}; return _uiNoContactsAddedLabel;}} private Element _uiNoContactsAddedLabel;
		public jQueryObject uiNoContactsAddedLabelJ {get {if (_uiNoContactsAddedLabelJ == null) {_uiNoContactsAddedLabelJ = jQuery.Select("#" + clientId + "_uiNoContactsAddedLabel");}; return _uiNoContactsAddedLabelJ;}} private jQueryObject _uiNoContactsAddedLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiBuddiesRequestedList {get {if (_uiBuddiesRequestedList == null) {_uiBuddiesRequestedList = (Element)Document.GetElementById(clientId + "_uiBuddiesRequestedList");}; return _uiBuddiesRequestedList;}} private Element _uiBuddiesRequestedList;
		public jQueryObject uiBuddiesRequestedListJ {get {if (_uiBuddiesRequestedListJ == null) {_uiBuddiesRequestedListJ = jQuery.Select("#" + clientId + "_uiBuddiesRequestedList");}; return _uiBuddiesRequestedListJ;}} private jQueryObject _uiBuddiesRequestedListJ;//mappings.Add("System.Web.UI.WebControls.Literal", ElementGetter("Element"));
		public Element uiEmailsSentList {get {if (_uiEmailsSentList == null) {_uiEmailsSentList = (Element)Document.GetElementById(clientId + "_uiEmailsSentList");}; return _uiEmailsSentList;}} private Element _uiEmailsSentList;
		public jQueryObject uiEmailsSentListJ {get {if (_uiEmailsSentListJ == null) {_uiEmailsSentListJ = jQuery.Select("#" + clientId + "_uiEmailsSentList");}; return _uiEmailsSentListJ;}} private jQueryObject _uiEmailsSentListJ;//mappings.Add("System.Web.UI.WebControls.Literal", ElementGetter("Element"));
	}
}
