Type.registerNamespace('SpottedScript.Controls.PagedData.Display');
SpottedScript.Controls.PagedData.Display.Controller=function(view){this.$1=view;this.$1.get_uiPager().set_$4(1);this.$1.get_uiPager().$5=Function.createDelegate(this,function(){
this.displayInfoForTab();});this.$6=new SpottedScript.Utils._CachedPagedProvider(new SpottedScript.Utils._PagedProviderService(view.get_uiServicePath().value,view.get_uiServiceMethod().value,Number.parseInvariant(view.get_uiTimeout().value)));for(var $0=0;$0<this.get_$8().length;$0++){this.get_$8()[$0].set_parametersUpdated(SpottedScript.Misc.combineEventHandler(this.get_$8()[$0].get_parametersUpdated(),Function.createDelegate(this,this.$2)));}}
SpottedScript.Controls.PagedData.Display.Controller.$5=function($p0){var $0=new Array($p0.length);for(var $1=0;$1<$0.length;$1++){$0[$1]=$p0[$1].data;}return $0;}
SpottedScript.Controls.PagedData.Display.Controller.prototype={$0:null,get_updated:function(){return this.$0;},set_updated:function(value){this.$0=value;return value;},$1:null,$2:function($p0,$p1){this.displayInfoForTab();},currentData:null,$3:function($p0,$p1,$p2){this.currentData=$p0;Utils.Trace.write('MapInfoReturned');this.$1.get_uiRepeater().displayData(SpottedScript.Controls.PagedData.Display.Controller.$5(this.currentData));this.$1.get_uiPager().set_$2(($p2)?-1:Math.ceil($p1/this.get_$4()));if(this.header!=null){this.header.innerHTML='<center>'+this.$1.get_uiTabName().value+'<br>('+$p1+(($p2)?'+':'')+')'+'</center>';}if(this.get_updated()!=null){this.get_updated()(this,null);}},get_$4:function(){return Number.parseInvariant(this.$1.get_uiPageSize().value);},get_uiPanel:function(){return this.$1.get_uiPanel();},$6:null,displayInfoForTab:function(){var $0={};for(var $1=0;$1<this.get_$8().length;$1++){var $dict1=this.get_$8()[$1].get_parameters();for(var $key2 in $dict1){var $2={key:$key2,value:$dict1[$key2]};$0[$2.key]=$2.value;}}this.$6.$12(this.$1.get_uiPager().get_$4(),this.get_$4(),$0,Function.createDelegate(this,this.$9),Function.createDelegate(this,this.$A));},$7:null,get_$8:function(){if(this.$7==null){var $0=this.$1.get_uiParameterSourceNames().value.split(',');this.$7=new Array($0.length);for(var $1=0;$1<$0.length;$1++){this.$7[$1]=eval($0[$1]);}}return this.$7;},$9:function($p0,$p1,$p2){this.$3($p0,$p1,$p2);},$A:function(){this.$3(new Array(0),0,false);},header:null,setHeader:function(el){this.header=el;}}
SpottedScript.Controls.PagedData.Display.View=function(clientId){this.clientId=clientId;}
SpottedScript.Controls.PagedData.Display.View.prototype={clientId:null,get_uiHeaderControl:function(){return document.getElementById(this.clientId+'_uiHeaderControl');},get_uiPanel:function(){return document.getElementById(this.clientId+'_uiPanel');},get_uiPager:function(){return eval(this.clientId+'_uiPagerController');},get_uiRepeater:function(){return eval(this.clientId+'_uiRepeaterController');},get_uiDefaultTop:function(){return document.getElementById(this.clientId+'_uiDefaultTop');},get_uiPageSize:function(){return document.getElementById(this.clientId+'_uiPageSize');},get_uiServicePath:function(){return document.getElementById(this.clientId+'_uiServicePath');},get_uiServiceMethod:function(){return document.getElementById(this.clientId+'_uiServiceMethod');},get_uiParameterSourceNames:function(){return document.getElementById(this.clientId+'_uiParameterSourceNames');},get_uiTimeout:function(){return document.getElementById(this.clientId+'_uiTimeout');},get_uiTabName:function(){return document.getElementById(this.clientId+'_uiTabName');}}
SpottedScript.Controls.PagedData.Display.Controller.registerClass('SpottedScript.Controls.PagedData.Display.Controller',null,SpottedScript.Controls.Tabbing.Tab.ITabController);
SpottedScript.Controls.PagedData.Display.View.registerClass('SpottedScript.Controls.PagedData.Display.View');
