Type.registerNamespace('SpottedScript.MixmagVote.Entry');
function FacebookReady(){SpottedScript.MixmagVote.Entry.Controller.instance.facebookReady();}
SpottedScript.MixmagVote.Entry.Controller=function(v){this.$10={};SpottedScript.MixmagVote.Entry.Controller.instance=this;this.view=v;this.server=v.server;if(SpottedScript.Misc.get_browserIsIE()){jQuery(document.body).ready(Function.createDelegate(this,this.$3));}else{this.$3();}}
SpottedScript.MixmagVote.Entry.Controller.prototype={$0:0,$1:null,$2:0,view:null,server:null,$3:function(){$addHandler(this.view.get_entry1Button(),'click',Function.createDelegate(this,this.entry1ButtonClick));$addHandler(this.view.get_entryConfirm_YesButton(),'click',Function.createDelegate(this,this.$8));$addHandler(this.view.get_entryConfirm_NoButton(),'click',Function.createDelegate(this,this.$9));this.$0=Number.parseInvariant(this.view.get_compK().value);this.$1=this.view.get_imageUrl().value;this.$2=Number.parseInvariant(this.view.get_pageIdToLike().value);this.$4=true;this.facebookReady();},facebookReady:function(){this.debug('FacebookReady start: DoneControllerInit = '+this.$4.toString()+', DoneFbAsyncInit = '+(eval('DoneFbAsyncInit')).toString());if(this.$4&&eval('DoneFbAsyncInit')){this.debug('FacebookReady running');FB.Event.subscribe('auth.statusChange',Function.createDelegate(this,function($p1_0){
this.$1B($p1_0);}));FB.getLoginStatus(Function.createDelegate(this,function($p1_0){
this.$1B($p1_0);this.debug(ImportedUtilities.U.toString($p1_0));this.$14=this.$15;this.$18=this.$17;}));this.$5();}},$4:false,$5:function(){this.$C(this.view.get_entry1Panel());},entry1ButtonClick:function(e){e.preventDefault();this.$6();},$6:function(){this.debug('entry1ButtonClickInternal: CurrentFacebookLoggedIn = '+this.$15.toString()+', CurrentFacebookConnected = '+this.$16.toString());if(this.$15&&this.$16){this.$7();}else{var $0=this.$12('Connecting...',false,false);FB.login(Function.createDelegate(this,function($p1_0){
if(this.$13($0)){return;}if(this.$16){this.$7();}else{this.$D('Looks like Facebook had trouble getting you connected.');}}),F.d('scope','email,publish_stream'));}FB.Event.subscribe('edge.create',Function.createDelegate(this,function($p1_0){
this.debug('edge.create');}));},$7:function(){this.debug('InitialFacebookLoggedIn = '+this.$14.toString());this.debug('FacebookAccountConfirmationStepDone = '+this.$1A.toString());if(this.$14&&!this.$1A){var $0=this.$11('Loading...');FB.api('/me',Function.createDelegate(this,function($p1_0){
if(this.$13($0)){return;}this.view.get_entryConfirm_Link().innerHTML=ImportedUtilities.U.get($p1_0,'name').toString();this.view.get_entryConfirm_Link().href=ImportedUtilities.U.get($p1_0,'link').toString();this.view.get_entryConfirm_Img().src='http://graph.facebook.com/'+ImportedUtilities.U.get($p1_0,'id').toString()+'/picture';this.$C(this.view.get_entryConfirmPanel());}));}else{this.$A();}},$8:function($p0){$p0.preventDefault();this.$1A=true;this.$A();},$9:function($p0){$p0.preventDefault();this.debug('entryConfirmNoButtonClick');this.$1A=true;var $0=this.$11('Logging out...');FB.logout(Function.createDelegate(this,function($p1_0){
if(this.$13($0)){return;}this.$C(this.view.get_entry1Panel());}));},$A:function(){var $0=this.$11('Entering the competition...');this.server.enterComp(this.$0,this.$1,this.view.get_entry1FacebookMessageTextbox().value,this.view.get_entry1DailyEmailCheckbox().checked,Function.createDelegate(this,function($p1_0){
if(this.$13($0)){return;}if(ImportedUtilities.U.isTrue($p1_0,'Exception')){this.$D('Looks like we had a problem...');}else if(!ImportedUtilities.U.isTrue($p1_0,'Done')){this.$D(ImportedUtilities.U.get($p1_0,'Message').toString());}else{this.debug(ImportedUtilities.U.toString($p1_0));this.$B(ImportedUtilities.U.get($p1_0,'MixmagEntryK'));}}));},$B:function($p0){var $0=this.$11('Loading...');FB.api(F.d('method','fql.query','query','SELECT type, created_time FROM page_fan WHERE page_id=\"'+this.$2.toString()+'\" AND uid=\"'+this.$17+'\"'),Function.createDelegate(this,function($p1_0){
if(this.$13($0)){return;}this.debug(ImportedUtilities.U.toString($p1_0));if(ImportedUtilities.U.exists($p1_0,'/value/type')){this.view.get_entry2LikeButtonHolder().style.display='none';}this.$C(this.view.get_entry2Panel());this.view.get_entry2LinkTextbox().value='http://mixmag-vote.com/'+$p0.toString();}));},$C:function($p0){this.view.get_entry1Panel().style.display=($p0===this.view.get_entry1Panel())?'':'none';this.view.get_entryConfirmPanel().style.display=($p0===this.view.get_entryConfirmPanel())?'':'none';this.view.get_entry2Panel().style.display=($p0===this.view.get_entry2Panel())?'':'none';},$D:function($p0){alert($p0);this.$C(this.view.get_entry1Panel());},debug:function(txt){this.view.get_debugOutput().innerHTML=txt+'\n'+this.view.get_debugOutput().innerHTML;},$E:false,$F:0,$11:function($p0){return this.$12($p0,true,true);},$12:function($p0,$p1,$p2){this.$E=true;this.$F++;var $0=this.$F;if($p2){if($p0.length>0){this.view.get_loadingLabel().innerHTML='<p>'+$p0+'<p>';}else{this.view.get_loadingLabel().innerHTML='<p>Loading...<p>';}this.view.get_loadingLabel().style.display='';}if($p1){window.setTimeout(Function.createDelegate(this,function(){
if(this.$E&&$0===this.$F){this.view.get_loadingLabel().innerHTML='<p>This seems to be taking a long time... <button id=\"LoadingLabel_CancelLink\">Cancel</button></p>';$addHandler(document.getElementById('LoadingLabel_CancelLink'),'click',Function.createDelegate(this,function($p2_0){
$p2_0.preventDefault();this.$10[$0.toString()]=true;this.$E=false;if(this.view.get_loadingLabel()!=null){this.view.get_loadingLabel().style.display='none';}this.$5();}));}}),5000);}return $0;},$13:function($p0){if(this.$10[$p0.toString()]!=null&&this.$10[$p0.toString()]){return true;}this.$E=false;if(this.view.get_loadingLabel()!=null){this.view.get_loadingLabel().style.display='none';}return false;},$14:false,$15:false,$16:false,$17:'0',$18:'0',$19:null,$1A:false,$1B:function($p0){this.debug('START updateCurrentFacebookLoginStatus CurrentFacebookConnected = '+this.$16.toString()+', CurrentFacebookLoggedIn = '+this.$15.toString());this.$16=ImportedUtilities.U.exists($p0,'status')&&ImportedUtilities.U.get($p0,'status').toString()==='connected';this.$15=ImportedUtilities.U.exists($p0,'status')&&ImportedUtilities.U.get($p0,'status').toString()!=='unknown';this.$17=(this.$16)?ImportedUtilities.U.get($p0,'authResponse/userID').toString():'0';this.$19=(this.$16)?ImportedUtilities.U.get($p0,'authResponse'):null;this.debug('DONE updateCurrentFacebookLoginStatus CurrentFacebookConnected = '+this.$16.toString()+', CurrentFacebookLoggedIn = '+this.$15.toString());}}
SpottedScript.MixmagVote.Entry.Server=function(){}
SpottedScript.MixmagVote.Entry.Server.prototype={enterComp:function(compK,imageUrl,facebookMessage,sendEmails,response){var $0=[compK,imageUrl,facebookMessage,sendEmails];var $1=eval('PageMethods.ClientRequest');if($1!=null){try{$1('Spotted.MixmagVote.Entry, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null','EnterComp',$0,response,response);}catch($2){var $3={};$3['Exception']=true;$3['ExceptionType']='ClientException';$3['Message']=$2.message;$3['StackTrace']='';response($3);}}}}
SpottedScript.MixmagVote.Entry.View=function(clientId){SpottedScript.MixmagVote.Entry.View.initializeBase(this,[clientId]);this.clientId=clientId;this.server=new SpottedScript.MixmagVote.Entry.Server();}
SpottedScript.MixmagVote.Entry.View.prototype={clientId:null,server:null,get_loadingLabel:function(){return document.getElementById(this.clientId+'_LoadingLabel');},get_imageUrl:function(){return document.getElementById(this.clientId+'_ImageUrl');},get_pageIdToLike:function(){return document.getElementById(this.clientId+'_PageIdToLike');},get_compK:function(){return document.getElementById(this.clientId+'_CompK');},get_entryClosedPanel:function(){return document.getElementById(this.clientId+'_EntryClosedPanel');},get_entry1Panel:function(){return document.getElementById(this.clientId+'_Entry1Panel');},get_entry1Img:function(){return document.getElementById(this.clientId+'_Entry1Img');},get_entry1FacebookMessageTextbox:function(){return document.getElementById(this.clientId+'_Entry1FacebookMessageTextbox');},get_entry1DailyEmailCheckboxPara:function(){return document.getElementById(this.clientId+'_Entry1DailyEmailCheckboxPara');},get_entry1DailyEmailCheckbox:function(){return document.getElementById(this.clientId+'_Entry1DailyEmailCheckbox');},get_entry1Button:function(){return document.getElementById(this.clientId+'_Entry1Button');},get_entryConfirmPanel:function(){return document.getElementById(this.clientId+'_EntryConfirmPanel');},get_entryConfirm_Img:function(){return document.getElementById(this.clientId+'_EntryConfirm_Img');},get_entryConfirm_Link:function(){return document.getElementById(this.clientId+'_EntryConfirm_Link');},get_entryConfirm_YesButton:function(){return document.getElementById(this.clientId+'_EntryConfirm_YesButton');},get_entryConfirm_NoButton:function(){return document.getElementById(this.clientId+'_EntryConfirm_NoButton');},get_entry2Panel:function(){return document.getElementById(this.clientId+'_Entry2Panel');},get_entry2Img:function(){return document.getElementById(this.clientId+'_Entry2Img');},get_entry2LinkTextbox:function(){return document.getElementById(this.clientId+'_Entry2LinkTextbox');},get_entry2LikeButtonHolder:function(){return document.getElementById(this.clientId+'_Entry2LikeButtonHolder');},get_debugOutput:function(){return document.getElementById(this.clientId+'_DebugOutput');},get_genericContainerPage:function(){return document.getElementById(this.clientId+'_GenericContainerPage');}}
SpottedScript.MixmagVote.Entry.Controller.registerClass('SpottedScript.MixmagVote.Entry.Controller');
SpottedScript.MixmagVote.Entry.Server.registerClass('SpottedScript.MixmagVote.Entry.Server');
SpottedScript.MixmagVote.Entry.View.registerClass('SpottedScript.MixmagVote.Entry.View',SpottedScript.MixmagVoteUserControl.View);
SpottedScript.MixmagVote.Entry.Controller.instance=null;
