Type.registerNamespace('SpottedScript.Pages.Blank1');
SpottedScript.Pages.Blank1.Controller=function(v){SpottedScript.Pages.Blank1.Controller.instance=this;this.view=v;if(SpottedScript.Misc.get_browserIsIE()){jQuery(document.body).ready(Function.createDelegate(this,this.$0));}else{this.$0();}}
SpottedScript.Pages.Blank1.Controller.prototype={view:null,$0:function(){$addHandler(this.view.get_button1(),'click',Function.createDelegate(this,this.button1Click));$addHandler(this.view.get_button2(),'click',Function.createDelegate(this,this.button2Click));},$1:false,$2:false,$3:'0',$4:null,$5:function($p0){this.$2=ImportedUtilities.U.exists($p0,'status')&&ImportedUtilities.U.get($p0,'status').toString()==='connected';this.$1=ImportedUtilities.U.exists($p0,'status')&&ImportedUtilities.U.get($p0,'status').toString()!=='unknown';this.$3=(this.$2)?ImportedUtilities.U.get($p0,'session/uid').toString():'0';this.$4=(this.$2)?ImportedUtilities.U.get($p0,'session'):null;this.debug(this.$3);},button1Click:function(e){e.preventDefault();this.debug('click!');FB.getLoginStatus(Function.createDelegate(this,function($p1_0){
this.$5($p1_0);}));FB.Event.subscribe('edge.create',Function.createDelegate(this,function($p1_0){
this.debug('edge.create');}));},button2Click:function(e){e.preventDefault();FB.api(F.d('method','fql.query','query','SELECT type, created_time FROM page_fan WHERE page_id=\"18658586341\" AND uid=\"'+this.$3+'\"'),Function.createDelegate(this,function($p1_0){
this.debug(ImportedUtilities.U.toString($p1_0));}));},debug:function(txt){this.view.get_output().innerHTML=txt+'\n'+this.view.get_output().innerHTML;}}
SpottedScript.Pages.Blank1.View=function(clientId){SpottedScript.Pages.Blank1.View.initializeBase(this,[clientId]);this.clientId=clientId;}
SpottedScript.Pages.Blank1.View.prototype={clientId:null,get_button1:function(){return document.getElementById(this.clientId+'_Button1');},get_button2:function(){return document.getElementById(this.clientId+'_Button2');},get_output:function(){return document.getElementById(this.clientId+'_Output');},get_genericContainerPage:function(){return document.getElementById(this.clientId+'_GenericContainerPage');}}
SpottedScript.Pages.Blank1.Controller.registerClass('SpottedScript.Pages.Blank1.Controller');
SpottedScript.Pages.Blank1.View.registerClass('SpottedScript.Pages.Blank1.View',SpottedScript.DsiUserControl.View);
SpottedScript.Pages.Blank1.Controller.instance=null;
