Type.registerNamespace('SpottedScript.MixmagVote.Vote');
function FacebookReady(){SpottedScript.MixmagVote.Vote.Controller.instance.facebookReady();}
SpottedScript.MixmagVote.Vote.Controller=function(v){this.$1A={};SpottedScript.MixmagVote.Vote.Controller.instance=this;this.view=v;this.server=v.server;if(SpottedScript.Misc.get_browserIsIE()){jQuery(document.body).ready(Function.createDelegate(this,this.$5));}else{this.$5();}}
SpottedScript.MixmagVote.Vote.Controller.prototype={view:null,server:null,$0:0,$1:0,$2:0,$3:null,$4:false,$5:function(){this.$4=true;this.facebookReady();this.$0=Number.parseInvariant(this.view.get_pageIdToLike().value);this.$1=Number.parseInvariant(this.view.get_entryK().value);this.$2=Number.parseInvariant(this.view.get_compK().value);this.$3=this.view.get_imageUrl().value;$addHandler(this.view.get_vote1VoteButton(),'click',Function.createDelegate(this,this.$7));$addHandler(this.view.get_voteConfirm_YesButton(),'click',Function.createDelegate(this,this.$A));$addHandler(this.view.get_voteConfirm_NoButton(),'click',Function.createDelegate(this,this.$B));if(this.$2===2){$addHandler(this.view.get_armaniSubmitButton(),'click',Function.createDelegate(this,this.$F));}},facebookReady:function(){if(this.$4&&eval('DoneFbAsyncInit')){FB.Event.subscribe('auth.statusChange',Function.createDelegate(this,function($p1_0){
this.$17($p1_0);}));FB.getLoginStatus(Function.createDelegate(this,function($p1_0){
this.$17($p1_0);this.$11=this.$12;this.$15=this.$14;}));FB.Event.subscribe('edge.create',Function.createDelegate(this,function($p1_0){
this.$D();}));this.$6();}},$6:function(){this.$10(this.view.get_vote1Panel());},$7:function($p0){this.debug('vote1VoteButtonClick');$p0.preventDefault();if(this.$12&&this.$13){this.$9();}else{var $0=this.$1C('Connecting...',false,false);FB.login(Function.createDelegate(this,function($p1_0){
if(this.$1D($0)){return;}if(this.$13){this.$9();}else{this.$1E('Looks like Facebook had trouble getting you connected.');}}),F.d('scope','email,publish_stream'));}},$8:false,$9:function(){this.debug('confirmFacebookAccount');if(this.$11&&!this.$8){var $0=this.$1B('Loading...');FB.api('/me',Function.createDelegate(this,function($p1_0){
if(this.$1D($0)){return;}this.view.get_voteConfirm_Link().innerHTML=ImportedUtilities.U.get($p1_0,'name').toString();this.view.get_voteConfirm_Link().href=ImportedUtilities.U.get($p1_0,'link').toString();this.view.get_voteConfirm_Img().src='http://graph.facebook.com/'+ImportedUtilities.U.get($p1_0,'id').toString()+'/picture';this.$10(this.view.get_voteConfirmPanel());}));}else{this.$C();}},$A:function($p0){$p0.preventDefault();this.$8=true;this.$C();},$B:function($p0){$p0.preventDefault();this.$8=true;var $0=this.$1B('Logging out...');FB.logout(Function.createDelegate(this,function($p1_0){
if(this.$1D($0)){return;}this.$10(this.view.get_vote1Panel());}));},$C:function(){this.debug('showLikePanelIfNeeded');var $0=this.$1B('Loading...');FB.api(F.d('method','fql.query','query','SELECT type, created_time FROM page_fan WHERE page_id=\"'+this.$0.toString()+'\" AND uid=\"'+this.$14+'\"'),Function.createDelegate(this,function($p1_0){
if(this.$1D($0)){return;}if(ImportedUtilities.U.exists($p1_0,'/value/type')){this.$E();}else{this.$10(this.view.get_voteLikePanel());}}));},$D:function(){this.$E();},$E:function(){this.debug('voteNow');var $0=this.$1B('Voting...');this.server.voteNow(this.$1,this.$2,this.$3,Function.createDelegate(this,function($p1_0){
if(this.$1D($0)){return;}if(ImportedUtilities.U.isTrue($p1_0,'Exception')){this.$1E('Looks like we had a problem...');}else if(!ImportedUtilities.U.isTrue($p1_0,'Done')){this.$1E(ImportedUtilities.U.get($p1_0,'Message').toString());}else{this.$10(this.view.get_vote2Panel());this.view.get_armaniTextFieldPanel().style.display=(this.$2===2)?'':'none';}}));},$F:function($p0){$p0.preventDefault();var $0=this.$1B('Saving...');this.server.saveQuestion(this.$1,this.$2,this.$3,this.view.get_armaniTextField().value,Function.createDelegate(this,function($p1_0){
if(this.$1D($0)){return;}if(ImportedUtilities.U.isTrue($p1_0,'Exception')){this.$1E('Looks like we had a problem...');}else if(!ImportedUtilities.U.isTrue($p1_0,'Done')){this.$1E(ImportedUtilities.U.get($p1_0,'Message').toString());}else{this.$10(this.view.get_vote2Panel());this.view.get_armaniSavedLabel().style.display='';}}));},$10:function($p0){this.view.get_vote1Panel().style.display=($p0===this.view.get_vote1Panel())?'':'none';this.view.get_voteConfirmPanel().style.display=($p0===this.view.get_voteConfirmPanel())?'':'none';this.view.get_voteLikePanel().style.display=($p0===this.view.get_voteLikePanel())?'':'none';this.view.get_vote2Panel().style.display=($p0===this.view.get_vote2Panel())?'':'none';},$11:false,$12:false,$13:false,$14:'0',$15:'0',$16:null,$17:function($p0){this.$13=ImportedUtilities.U.exists($p0,'status')&&ImportedUtilities.U.get($p0,'status').toString()==='connected';this.$12=ImportedUtilities.U.exists($p0,'status')&&ImportedUtilities.U.get($p0,'status').toString()!=='unknown';this.$14=(this.$13)?ImportedUtilities.U.get($p0,'authResponse/userID').toString():'0';this.$16=(this.$13)?ImportedUtilities.U.get($p0,'authResponse'):null;},debug:function(txt){this.view.get_debugOutput().innerHTML=txt+'\n'+this.view.get_debugOutput().innerHTML;},$18:false,$19:0,$1B:function($p0){return this.$1C($p0,true,true);},$1C:function($p0,$p1,$p2){this.$18=true;this.$19++;var $0=this.$19;if($p2){if($p0.length>0){this.view.get_loadingLabel().innerHTML='<p>'+$p0+'<p>';}else{this.view.get_loadingLabel().innerHTML='<p>Loading...<p>';}this.view.get_loadingLabel().style.display='';}if($p1){window.setTimeout(Function.createDelegate(this,function(){
if(this.$18&&$0===this.$19){this.view.get_loadingLabel().innerHTML='<p>This seems to be taking a long time... <button id=\"LoadingLabel_CancelLink\">Cancel</button></p>';$addHandler(document.getElementById('LoadingLabel_CancelLink'),'click',Function.createDelegate(this,function($p2_0){
$p2_0.preventDefault();this.$1A[$0.toString()]=true;this.$18=false;if(this.view.get_loadingLabel()!=null){this.view.get_loadingLabel().style.display='none';}this.$6();}));}}),5000);}return $0;},$1D:function($p0){if(this.$1A[$p0.toString()]!=null&&this.$1A[$p0.toString()]){return true;}this.$18=false;if(this.view.get_loadingLabel()!=null){this.view.get_loadingLabel().style.display='none';}return false;},$1E:function($p0){alert($p0);this.$10(this.view.get_vote1Panel());}}
SpottedScript.MixmagVote.Vote.Server=function(){}
SpottedScript.MixmagVote.Vote.Server.prototype={voteNow:function(entryK,compK,imageUrl,response){var $0=[entryK,compK,imageUrl];var $1=eval('PageMethods.ClientRequest');if($1!=null){try{$1('Spotted.MixmagVote.Vote, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null','VoteNow',$0,response,response);}catch($2){var $3={};$3['Exception']=true;$3['ExceptionType']='ClientException';$3['Message']=$2.message;$3['StackTrace']='';response($3);}}},saveQuestion:function(entryK,compK,imageUrl,questionString,response){var $0=[entryK,compK,imageUrl,questionString];var $1=eval('PageMethods.ClientRequest');if($1!=null){try{$1('Spotted.MixmagVote.Vote, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null','SaveQuestion',$0,response,response);}catch($2){var $3={};$3['Exception']=true;$3['ExceptionType']='ClientException';$3['Message']=$2.message;$3['StackTrace']='';response($3);}}}}
SpottedScript.MixmagVote.Vote.View=function(clientId){SpottedScript.MixmagVote.Vote.View.initializeBase(this,[clientId]);this.clientId=clientId;this.server=new SpottedScript.MixmagVote.Vote.Server();}
SpottedScript.MixmagVote.Vote.View.prototype={clientId:null,server:null,get_compK:function(){return document.getElementById(this.clientId+'_CompK');},get_imageUrl:function(){return document.getElementById(this.clientId+'_ImageUrl');},get_entryK:function(){return document.getElementById(this.clientId+'_EntryK');},get_pageIdToLike:function(){return document.getElementById(this.clientId+'_PageIdToLike');},get_voteClosedPanel:function(){return document.getElementById(this.clientId+'_VoteClosedPanel');},get_vote1Panel:function(){return document.getElementById(this.clientId+'_Vote1Panel');},get_vote1Img:function(){return document.getElementById(this.clientId+'_Vote1Img');},get_vote1VoteButton:function(){return document.getElementById(this.clientId+'_Vote1VoteButton');},get_voteConfirmPanel:function(){return document.getElementById(this.clientId+'_VoteConfirmPanel');},get_voteConfirm_Img:function(){return document.getElementById(this.clientId+'_VoteConfirm_Img');},get_voteConfirm_Link:function(){return document.getElementById(this.clientId+'_VoteConfirm_Link');},get_voteConfirm_YesButton:function(){return document.getElementById(this.clientId+'_VoteConfirm_YesButton');},get_voteConfirm_NoButton:function(){return document.getElementById(this.clientId+'_VoteConfirm_NoButton');},get_voteLikePanel:function(){return document.getElementById(this.clientId+'_VoteLikePanel');},get_vote2Panel:function(){return document.getElementById(this.clientId+'_Vote2Panel');},get_armaniTextFieldPanel:function(){return document.getElementById(this.clientId+'_ArmaniTextFieldPanel');},get_armaniTextField:function(){return document.getElementById(this.clientId+'_ArmaniTextField');},get_armaniSubmitButton:function(){return document.getElementById(this.clientId+'_ArmaniSubmitButton');},get_armaniSavedLabel:function(){return document.getElementById(this.clientId+'_ArmaniSavedLabel');},get_debugOutput:function(){return document.getElementById(this.clientId+'_DebugOutput');},get_loadingLabel:function(){return document.getElementById(this.clientId+'_LoadingLabel');},get_genericContainerPage:function(){return document.getElementById(this.clientId+'_GenericContainerPage');}}
SpottedScript.MixmagVote.Vote.Controller.registerClass('SpottedScript.MixmagVote.Vote.Controller');
SpottedScript.MixmagVote.Vote.Server.registerClass('SpottedScript.MixmagVote.Vote.Server');
SpottedScript.MixmagVote.Vote.View.registerClass('SpottedScript.MixmagVote.Vote.View',SpottedScript.MixmagVoteUserControl.View);
SpottedScript.MixmagVote.Vote.Controller.instance=null;
