Type.registerNamespace('SpottedScript.MixmagVote.Repost');
function FacebookReady(){SpottedScript.MixmagVote.Repost.Controller.instance.facebookReady();}
SpottedScript.MixmagVote.Repost.Controller=function(v){this.$D={};SpottedScript.MixmagVote.Repost.Controller.instance=this;this.view=v;this.server=v.server;if(SpottedScript.Misc.get_browserIsIE()){jQuery(document.body).ready(Function.createDelegate(this,this.$1));}else{this.$1();}}
SpottedScript.MixmagVote.Repost.Controller.prototype={$0:0,view:null,server:null,$1:function(){$addHandler(this.view.get_repost1Button(),'click',Function.createDelegate(this,this.repost1ButtonClick));$addHandler(this.view.get_repostConfirm_YesButton(),'click',Function.createDelegate(this,this.$6));$addHandler(this.view.get_repostConfirm_NoButton(),'click',Function.createDelegate(this,this.$7));this.$0=Number.parseInvariant(this.view.get_entryK().value);this.$2=true;this.facebookReady();},facebookReady:function(){this.debug('FacebookReady start: DoneControllerInit = '+this.$2.toString()+', DoneFbAsyncInit = '+(eval('DoneFbAsyncInit')).toString());if(this.$2&&eval('DoneFbAsyncInit')){this.debug('FacebookReady running');FB.Event.subscribe('auth.statusChange',Function.createDelegate(this,function($p1_0){
this.$18($p1_0);}));FB.getLoginStatus(Function.createDelegate(this,function($p1_0){
this.$18($p1_0);this.debug(ImportedUtilities.U.toString($p1_0));this.$11=this.$12;this.$15=this.$14;}));this.$3();}},$2:false,$3:function(){this.$9(this.view.get_repost1Panel());},repost1ButtonClick:function(e){e.preventDefault();this.$4();},$4:function(){this.debug('entry1ButtonClickInternal: CurrentFacebookLoggedIn = '+this.$12.toString()+', CurrentFacebookConnected = '+this.$13.toString());if(this.$12&&this.$13){this.$5();}else{var $0=this.$F('Connecting...',false,false);FB.login(Function.createDelegate(this,function($p1_0){
if(this.$10($0)){return;}if(this.$13){this.$5();}else{this.$A('Looks like Facebook had trouble getting you connected.');}}),F.d('perms','email,publish_stream'));}FB.Event.subscribe('edge.create',Function.createDelegate(this,function($p1_0){
this.debug('edge.create');}));},$5:function(){this.debug('InitialFacebookLoggedIn = '+this.$11.toString());this.debug('FacebookAccountConfirmationStepDone = '+this.$17.toString());if(this.$11&&!this.$17){var $0=this.$E('Loading...');FB.api('/me',Function.createDelegate(this,function($p1_0){
if(this.$10($0)){return;}this.view.get_repostConfirm_Link().innerHTML=ImportedUtilities.U.get($p1_0,'name').toString();this.view.get_repostConfirm_Link().href=ImportedUtilities.U.get($p1_0,'link').toString();this.view.get_repostConfirm_Img().src='http://graph.facebook.com/'+ImportedUtilities.U.get($p1_0,'id').toString()+'/picture';this.$9(this.view.get_repostConfirmPanel());}));}else{this.$8();}},$6:function($p0){$p0.preventDefault();this.$17=true;this.$8();},$7:function($p0){$p0.preventDefault();this.debug('entryConfirmNoButtonClick');this.$17=true;var $0=this.$E('Logging out...');FB.logout(Function.createDelegate(this,function($p1_0){
if(this.$10($0)){return;}this.$9(this.view.get_repost1Panel());}));},$8:function(){var $0=this.$E('Posting your message...');this.server.repostNow(this.$0,this.view.get_repost1FacebookMessageTextbox().value,Function.createDelegate(this,function($p1_0){
if(this.$10($0)){return;}if(ImportedUtilities.U.isTrue($p1_0,'Exception')||!ImportedUtilities.U.isTrue($p1_0,'Done')){this.$A('Looks like we had a problem...');}else{this.debug(ImportedUtilities.U.toString($p1_0));this.$9(this.view.get_repost2Panel());}}));},$9:function($p0){this.view.get_repost1Panel().style.display=($p0===this.view.get_repost1Panel())?'':'none';this.view.get_repostConfirmPanel().style.display=($p0===this.view.get_repostConfirmPanel())?'':'none';this.view.get_repost2Panel().style.display=($p0===this.view.get_repost2Panel())?'':'none';},$A:function($p0){alert($p0);this.$9(this.view.get_repost1Panel());},debug:function(txt){this.view.get_debugOutput().innerHTML=txt+'\n'+this.view.get_debugOutput().innerHTML;},$B:false,$C:0,$E:function($p0){return this.$F($p0,true,true);},$F:function($p0,$p1,$p2){this.$B=true;this.$C++;var $0=this.$C;if($p2){if($p0.length>0){this.view.get_loadingLabel().innerHTML='<p>'+$p0+'<p>';}else{this.view.get_loadingLabel().innerHTML='<p>Loading...<p>';}this.view.get_loadingLabel().style.display='';}if($p1){window.setTimeout(Function.createDelegate(this,function(){
if(this.$B&&$0===this.$C){this.view.get_loadingLabel().innerHTML='<p>This seems to be taking a long time... <button id=\"LoadingLabel_CancelLink\">Cancel</button></p>';$addHandler(document.getElementById('LoadingLabel_CancelLink'),'click',Function.createDelegate(this,function($p2_0){
$p2_0.preventDefault();this.$D[$0.toString()]=true;this.$B=false;if(this.view.get_loadingLabel()!=null){this.view.get_loadingLabel().style.display='none';}this.$3();}));}}),5000);}return $0;},$10:function($p0){if(this.$D[$p0.toString()]!=null&&this.$D[$p0.toString()]){return true;}this.$B=false;if(this.view.get_loadingLabel()!=null){this.view.get_loadingLabel().style.display='none';}return false;},$11:false,$12:false,$13:false,$14:'0',$15:'0',$16:null,$17:false,$18:function($p0){this.debug('START updateCurrentFacebookLoginStatus CurrentFacebookConnected = '+this.$13.toString()+', CurrentFacebookLoggedIn = '+this.$12.toString());this.$13=ImportedUtilities.U.exists($p0,'status')&&ImportedUtilities.U.get($p0,'status').toString()==='connected';this.$12=ImportedUtilities.U.exists($p0,'status')&&ImportedUtilities.U.get($p0,'status').toString()!=='unknown';this.$14=(this.$13)?ImportedUtilities.U.get($p0,'session/uid').toString():'0';this.$16=(this.$13)?ImportedUtilities.U.get($p0,'session'):null;this.debug('DONE updateCurrentFacebookLoginStatus CurrentFacebookConnected = '+this.$13.toString()+', CurrentFacebookLoggedIn = '+this.$12.toString());}}
SpottedScript.MixmagVote.Repost.Server=function(){}
SpottedScript.MixmagVote.Repost.Server.prototype={repostNow:function(entryK,message,response){var $0=[entryK,message];var $1=eval('PageMethods.ClientRequest');if($1!=null){try{$1('Spotted.MixmagVote.Repost, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null','RepostNow',$0,response,response);}catch($2){var $3={};$3['Exception']=true;$3['ExceptionType']='ClientException';$3['Message']=$2.message;$3['StackTrace']='';response($3);}}}}
SpottedScript.MixmagVote.Repost.View=function(clientId){SpottedScript.MixmagVote.Repost.View.initializeBase(this,[clientId]);this.clientId=clientId;this.server=new SpottedScript.MixmagVote.Repost.Server();}
SpottedScript.MixmagVote.Repost.View.prototype={clientId:null,server:null,get_entryK:function(){return document.getElementById(this.clientId+'_EntryK');},get_repost1Panel:function(){return document.getElementById(this.clientId+'_Repost1Panel');},get_repost1Img:function(){return document.getElementById(this.clientId+'_Repost1Img');},get_repost1FacebookMessageTextbox:function(){return document.getElementById(this.clientId+'_Repost1FacebookMessageTextbox');},get_repost1Button:function(){return document.getElementById(this.clientId+'_Repost1Button');},get_repostConfirmPanel:function(){return document.getElementById(this.clientId+'_RepostConfirmPanel');},get_repostConfirm_Img:function(){return document.getElementById(this.clientId+'_RepostConfirm_Img');},get_repostConfirm_Link:function(){return document.getElementById(this.clientId+'_RepostConfirm_Link');},get_repostConfirm_YesButton:function(){return document.getElementById(this.clientId+'_RepostConfirm_YesButton');},get_repostConfirm_NoButton:function(){return document.getElementById(this.clientId+'_RepostConfirm_NoButton');},get_repost2Panel:function(){return document.getElementById(this.clientId+'_Repost2Panel');},get_debugOutput:function(){return document.getElementById(this.clientId+'_DebugOutput');},get_loadingLabel:function(){return document.getElementById(this.clientId+'_LoadingLabel');},get_genericContainerPage:function(){return document.getElementById(this.clientId+'_GenericContainerPage');}}
SpottedScript.MixmagVote.Repost.Controller.registerClass('SpottedScript.MixmagVote.Repost.Controller');
SpottedScript.MixmagVote.Repost.Server.registerClass('SpottedScript.MixmagVote.Repost.Server');
SpottedScript.MixmagVote.Repost.View.registerClass('SpottedScript.MixmagVote.Repost.View',SpottedScript.MixmagVoteUserControl.View);
SpottedScript.MixmagVote.Repost.Controller.instance=null;
