//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlInputButton", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.CustomValidator", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.ValidationSummary", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.RegularExpressionValidator", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.CompareValidator", ElementGetter("Element"));
//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using jQueryApi;
using Js.Library;

namespace Js.Styled.Login
{
	public partial class View
		 : Js.StyledUserControl.View
	{
		public string clientId;
		public View(string clientId)
			 : base(clientId)
		{
			this.clientId = clientId;
		}
		public Element AlreadySignedInP {get {if (_AlreadySignedInP == null) {_AlreadySignedInP = (Element)Document.GetElementById(clientId + "_AlreadySignedInP");}; return _AlreadySignedInP;}} private Element _AlreadySignedInP;
		public jQueryObject AlreadySignedInPJ {get {if (_AlreadySignedInPJ == null) {_AlreadySignedInPJ = jQuery.Select("#" + clientId + "_AlreadySignedInP");}; return _AlreadySignedInPJ;}} private jQueryObject _AlreadySignedInPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element UserFirstNameLabel {get {if (_UserFirstNameLabel == null) {_UserFirstNameLabel = (Element)Document.GetElementById(clientId + "_UserFirstNameLabel");}; return _UserFirstNameLabel;}} private Element _UserFirstNameLabel;
		public jQueryObject UserFirstNameLabelJ {get {if (_UserFirstNameLabelJ == null) {_UserFirstNameLabelJ = jQuery.Select("#" + clientId + "_UserFirstNameLabel");}; return _UserFirstNameLabelJ;}} private jQueryObject _UserFirstNameLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public InputElement ContinueButton {get {if (_ContinueButton == null) {_ContinueButton = (InputElement)Document.GetElementById(clientId + "_ContinueButton");}; return _ContinueButton;}} private InputElement _ContinueButton;
		public jQueryObject ContinueButtonJ {get {if (_ContinueButtonJ == null) {_ContinueButtonJ = jQuery.Select("#" + clientId + "_ContinueButton");}; return _ContinueButtonJ;}} private jQueryObject _ContinueButtonJ;
		public InputElement LoginEmailTextBox {get {if (_LoginEmailTextBox == null) {_LoginEmailTextBox = (InputElement)Document.GetElementById(clientId + "_LoginEmailTextBox");}; return _LoginEmailTextBox;}} private InputElement _LoginEmailTextBox;
		public jQueryObject LoginEmailTextBoxJ {get {if (_LoginEmailTextBoxJ == null) {_LoginEmailTextBoxJ = jQuery.Select("#" + clientId + "_LoginEmailTextBox");}; return _LoginEmailTextBoxJ;}} private jQueryObject _LoginEmailTextBoxJ;
		public Element LoginEmailRequiredFieldValidator {get {if (_LoginEmailRequiredFieldValidator == null) {_LoginEmailRequiredFieldValidator = (Element)Document.GetElementById(clientId + "_LoginEmailRequiredFieldValidator");}; return _LoginEmailRequiredFieldValidator;}} private Element _LoginEmailRequiredFieldValidator;
		public jQueryObject LoginEmailRequiredFieldValidatorJ {get {if (_LoginEmailRequiredFieldValidatorJ == null) {_LoginEmailRequiredFieldValidatorJ = jQuery.Select("#" + clientId + "_LoginEmailRequiredFieldValidator");}; return _LoginEmailRequiredFieldValidatorJ;}} private jQueryObject _LoginEmailRequiredFieldValidatorJ;//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
		public InputElement LoginPasswordTextBox {get {if (_LoginPasswordTextBox == null) {_LoginPasswordTextBox = (InputElement)Document.GetElementById(clientId + "_LoginPasswordTextBox");}; return _LoginPasswordTextBox;}} private InputElement _LoginPasswordTextBox;
		public jQueryObject LoginPasswordTextBoxJ {get {if (_LoginPasswordTextBoxJ == null) {_LoginPasswordTextBoxJ = jQuery.Select("#" + clientId + "_LoginPasswordTextBox");}; return _LoginPasswordTextBoxJ;}} private jQueryObject _LoginPasswordTextBoxJ;
		public Element LoginPasswordRequiredFieldValidator {get {if (_LoginPasswordRequiredFieldValidator == null) {_LoginPasswordRequiredFieldValidator = (Element)Document.GetElementById(clientId + "_LoginPasswordRequiredFieldValidator");}; return _LoginPasswordRequiredFieldValidator;}} private Element _LoginPasswordRequiredFieldValidator;
		public jQueryObject LoginPasswordRequiredFieldValidatorJ {get {if (_LoginPasswordRequiredFieldValidatorJ == null) {_LoginPasswordRequiredFieldValidatorJ = jQuery.Select("#" + clientId + "_LoginPasswordRequiredFieldValidator");}; return _LoginPasswordRequiredFieldValidatorJ;}} private jQueryObject _LoginPasswordRequiredFieldValidatorJ;//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
		public Element LoginButton {get {if (_LoginButton == null) {_LoginButton = (Element)Document.GetElementById(clientId + "_LoginButton");}; return _LoginButton;}} private Element _LoginButton;
		public jQueryObject LoginButtonJ {get {if (_LoginButtonJ == null) {_LoginButtonJ = jQuery.Select("#" + clientId + "_LoginButton");}; return _LoginButtonJ;}} private jQueryObject _LoginButtonJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlInputButton", ElementGetter("Element"));
		public Element LoginCustomValidator {get {if (_LoginCustomValidator == null) {_LoginCustomValidator = (Element)Document.GetElementById(clientId + "_LoginCustomValidator");}; return _LoginCustomValidator;}} private Element _LoginCustomValidator;
		public jQueryObject LoginCustomValidatorJ {get {if (_LoginCustomValidatorJ == null) {_LoginCustomValidatorJ = jQuery.Select("#" + clientId + "_LoginCustomValidator");}; return _LoginCustomValidatorJ;}} private jQueryObject _LoginCustomValidatorJ;//mappings.Add("System.Web.UI.WebControls.CustomValidator", ElementGetter("Element"));
		public Element LoginValidationSummary {get {if (_LoginValidationSummary == null) {_LoginValidationSummary = (Element)Document.GetElementById(clientId + "_LoginValidationSummary");}; return _LoginValidationSummary;}} private Element _LoginValidationSummary;
		public jQueryObject LoginValidationSummaryJ {get {if (_LoginValidationSummaryJ == null) {_LoginValidationSummaryJ = jQuery.Select("#" + clientId + "_LoginValidationSummary");}; return _LoginValidationSummaryJ;}} private jQueryObject _LoginValidationSummaryJ;//mappings.Add("System.Web.UI.WebControls.ValidationSummary", ElementGetter("Element"));
		public InputElement RegistrationFirstNameTextBox {get {if (_RegistrationFirstNameTextBox == null) {_RegistrationFirstNameTextBox = (InputElement)Document.GetElementById(clientId + "_RegistrationFirstNameTextBox");}; return _RegistrationFirstNameTextBox;}} private InputElement _RegistrationFirstNameTextBox;
		public jQueryObject RegistrationFirstNameTextBoxJ {get {if (_RegistrationFirstNameTextBoxJ == null) {_RegistrationFirstNameTextBoxJ = jQuery.Select("#" + clientId + "_RegistrationFirstNameTextBox");}; return _RegistrationFirstNameTextBoxJ;}} private jQueryObject _RegistrationFirstNameTextBoxJ;
		public Element RegistrationFirstNameRequiredFieldValidator {get {if (_RegistrationFirstNameRequiredFieldValidator == null) {_RegistrationFirstNameRequiredFieldValidator = (Element)Document.GetElementById(clientId + "_RegistrationFirstNameRequiredFieldValidator");}; return _RegistrationFirstNameRequiredFieldValidator;}} private Element _RegistrationFirstNameRequiredFieldValidator;
		public jQueryObject RegistrationFirstNameRequiredFieldValidatorJ {get {if (_RegistrationFirstNameRequiredFieldValidatorJ == null) {_RegistrationFirstNameRequiredFieldValidatorJ = jQuery.Select("#" + clientId + "_RegistrationFirstNameRequiredFieldValidator");}; return _RegistrationFirstNameRequiredFieldValidatorJ;}} private jQueryObject _RegistrationFirstNameRequiredFieldValidatorJ;//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
		public InputElement RegistrationLastNameTextBox {get {if (_RegistrationLastNameTextBox == null) {_RegistrationLastNameTextBox = (InputElement)Document.GetElementById(clientId + "_RegistrationLastNameTextBox");}; return _RegistrationLastNameTextBox;}} private InputElement _RegistrationLastNameTextBox;
		public jQueryObject RegistrationLastNameTextBoxJ {get {if (_RegistrationLastNameTextBoxJ == null) {_RegistrationLastNameTextBoxJ = jQuery.Select("#" + clientId + "_RegistrationLastNameTextBox");}; return _RegistrationLastNameTextBoxJ;}} private jQueryObject _RegistrationLastNameTextBoxJ;
		public Element RegistrationLastNameRequiredFieldValidator {get {if (_RegistrationLastNameRequiredFieldValidator == null) {_RegistrationLastNameRequiredFieldValidator = (Element)Document.GetElementById(clientId + "_RegistrationLastNameRequiredFieldValidator");}; return _RegistrationLastNameRequiredFieldValidator;}} private Element _RegistrationLastNameRequiredFieldValidator;
		public jQueryObject RegistrationLastNameRequiredFieldValidatorJ {get {if (_RegistrationLastNameRequiredFieldValidatorJ == null) {_RegistrationLastNameRequiredFieldValidatorJ = jQuery.Select("#" + clientId + "_RegistrationLastNameRequiredFieldValidator");}; return _RegistrationLastNameRequiredFieldValidatorJ;}} private jQueryObject _RegistrationLastNameRequiredFieldValidatorJ;//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
		public InputElement RegistrationEmailTextBox {get {if (_RegistrationEmailTextBox == null) {_RegistrationEmailTextBox = (InputElement)Document.GetElementById(clientId + "_RegistrationEmailTextBox");}; return _RegistrationEmailTextBox;}} private InputElement _RegistrationEmailTextBox;
		public jQueryObject RegistrationEmailTextBoxJ {get {if (_RegistrationEmailTextBoxJ == null) {_RegistrationEmailTextBoxJ = jQuery.Select("#" + clientId + "_RegistrationEmailTextBox");}; return _RegistrationEmailTextBoxJ;}} private jQueryObject _RegistrationEmailTextBoxJ;
		public Element RegistrationEmailRequiredFieldValidator {get {if (_RegistrationEmailRequiredFieldValidator == null) {_RegistrationEmailRequiredFieldValidator = (Element)Document.GetElementById(clientId + "_RegistrationEmailRequiredFieldValidator");}; return _RegistrationEmailRequiredFieldValidator;}} private Element _RegistrationEmailRequiredFieldValidator;
		public jQueryObject RegistrationEmailRequiredFieldValidatorJ {get {if (_RegistrationEmailRequiredFieldValidatorJ == null) {_RegistrationEmailRequiredFieldValidatorJ = jQuery.Select("#" + clientId + "_RegistrationEmailRequiredFieldValidator");}; return _RegistrationEmailRequiredFieldValidatorJ;}} private jQueryObject _RegistrationEmailRequiredFieldValidatorJ;//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
		public Element RegistrationEmailRegularExpressionValidator {get {if (_RegistrationEmailRegularExpressionValidator == null) {_RegistrationEmailRegularExpressionValidator = (Element)Document.GetElementById(clientId + "_RegistrationEmailRegularExpressionValidator");}; return _RegistrationEmailRegularExpressionValidator;}} private Element _RegistrationEmailRegularExpressionValidator;
		public jQueryObject RegistrationEmailRegularExpressionValidatorJ {get {if (_RegistrationEmailRegularExpressionValidatorJ == null) {_RegistrationEmailRegularExpressionValidatorJ = jQuery.Select("#" + clientId + "_RegistrationEmailRegularExpressionValidator");}; return _RegistrationEmailRegularExpressionValidatorJ;}} private jQueryObject _RegistrationEmailRegularExpressionValidatorJ;//mappings.Add("System.Web.UI.WebControls.RegularExpressionValidator", ElementGetter("Element"));
		public InputElement RegistrationPasswordTextBox {get {if (_RegistrationPasswordTextBox == null) {_RegistrationPasswordTextBox = (InputElement)Document.GetElementById(clientId + "_RegistrationPasswordTextBox");}; return _RegistrationPasswordTextBox;}} private InputElement _RegistrationPasswordTextBox;
		public jQueryObject RegistrationPasswordTextBoxJ {get {if (_RegistrationPasswordTextBoxJ == null) {_RegistrationPasswordTextBoxJ = jQuery.Select("#" + clientId + "_RegistrationPasswordTextBox");}; return _RegistrationPasswordTextBoxJ;}} private jQueryObject _RegistrationPasswordTextBoxJ;
		public Element RegistrationPasswordRequiredFieldValidator {get {if (_RegistrationPasswordRequiredFieldValidator == null) {_RegistrationPasswordRequiredFieldValidator = (Element)Document.GetElementById(clientId + "_RegistrationPasswordRequiredFieldValidator");}; return _RegistrationPasswordRequiredFieldValidator;}} private Element _RegistrationPasswordRequiredFieldValidator;
		public jQueryObject RegistrationPasswordRequiredFieldValidatorJ {get {if (_RegistrationPasswordRequiredFieldValidatorJ == null) {_RegistrationPasswordRequiredFieldValidatorJ = jQuery.Select("#" + clientId + "_RegistrationPasswordRequiredFieldValidator");}; return _RegistrationPasswordRequiredFieldValidatorJ;}} private jQueryObject _RegistrationPasswordRequiredFieldValidatorJ;//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
		public InputElement RegistrationConfirmPasswordTextBox {get {if (_RegistrationConfirmPasswordTextBox == null) {_RegistrationConfirmPasswordTextBox = (InputElement)Document.GetElementById(clientId + "_RegistrationConfirmPasswordTextBox");}; return _RegistrationConfirmPasswordTextBox;}} private InputElement _RegistrationConfirmPasswordTextBox;
		public jQueryObject RegistrationConfirmPasswordTextBoxJ {get {if (_RegistrationConfirmPasswordTextBoxJ == null) {_RegistrationConfirmPasswordTextBoxJ = jQuery.Select("#" + clientId + "_RegistrationConfirmPasswordTextBox");}; return _RegistrationConfirmPasswordTextBoxJ;}} private jQueryObject _RegistrationConfirmPasswordTextBoxJ;
		public Element RegistrationConfirmPasswordRequiredFieldValidator {get {if (_RegistrationConfirmPasswordRequiredFieldValidator == null) {_RegistrationConfirmPasswordRequiredFieldValidator = (Element)Document.GetElementById(clientId + "_RegistrationConfirmPasswordRequiredFieldValidator");}; return _RegistrationConfirmPasswordRequiredFieldValidator;}} private Element _RegistrationConfirmPasswordRequiredFieldValidator;
		public jQueryObject RegistrationConfirmPasswordRequiredFieldValidatorJ {get {if (_RegistrationConfirmPasswordRequiredFieldValidatorJ == null) {_RegistrationConfirmPasswordRequiredFieldValidatorJ = jQuery.Select("#" + clientId + "_RegistrationConfirmPasswordRequiredFieldValidator");}; return _RegistrationConfirmPasswordRequiredFieldValidatorJ;}} private jQueryObject _RegistrationConfirmPasswordRequiredFieldValidatorJ;//mappings.Add("System.Web.UI.WebControls.RequiredFieldValidator", ElementGetter("Element"));
		public Element RegistrationComparePasswordsValidator {get {if (_RegistrationComparePasswordsValidator == null) {_RegistrationComparePasswordsValidator = (Element)Document.GetElementById(clientId + "_RegistrationComparePasswordsValidator");}; return _RegistrationComparePasswordsValidator;}} private Element _RegistrationComparePasswordsValidator;
		public jQueryObject RegistrationComparePasswordsValidatorJ {get {if (_RegistrationComparePasswordsValidatorJ == null) {_RegistrationComparePasswordsValidatorJ = jQuery.Select("#" + clientId + "_RegistrationComparePasswordsValidator");}; return _RegistrationComparePasswordsValidatorJ;}} private jQueryObject _RegistrationComparePasswordsValidatorJ;//mappings.Add("System.Web.UI.WebControls.CompareValidator", ElementGetter("Element"));
		public CheckBoxElement TermsCheckBox {get {if (_TermsCheckBox == null) {_TermsCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_TermsCheckBox");}; return _TermsCheckBox;}} private CheckBoxElement _TermsCheckBox;
		public jQueryObject TermsCheckBoxJ {get {if (_TermsCheckBoxJ == null) {_TermsCheckBoxJ = jQuery.Select("#" + clientId + "_TermsCheckBox");}; return _TermsCheckBoxJ;}} private jQueryObject _TermsCheckBoxJ;
		public Element TermsCheckBoxCustomValidator {get {if (_TermsCheckBoxCustomValidator == null) {_TermsCheckBoxCustomValidator = (Element)Document.GetElementById(clientId + "_TermsCheckBoxCustomValidator");}; return _TermsCheckBoxCustomValidator;}} private Element _TermsCheckBoxCustomValidator;
		public jQueryObject TermsCheckBoxCustomValidatorJ {get {if (_TermsCheckBoxCustomValidatorJ == null) {_TermsCheckBoxCustomValidatorJ = jQuery.Select("#" + clientId + "_TermsCheckBoxCustomValidator");}; return _TermsCheckBoxCustomValidatorJ;}} private jQueryObject _TermsCheckBoxCustomValidatorJ;//mappings.Add("System.Web.UI.WebControls.CustomValidator", ElementGetter("Element"));
		public Element RegistrationButton {get {if (_RegistrationButton == null) {_RegistrationButton = (Element)Document.GetElementById(clientId + "_RegistrationButton");}; return _RegistrationButton;}} private Element _RegistrationButton;
		public jQueryObject RegistrationButtonJ {get {if (_RegistrationButtonJ == null) {_RegistrationButtonJ = jQuery.Select("#" + clientId + "_RegistrationButton");}; return _RegistrationButtonJ;}} private jQueryObject _RegistrationButtonJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlInputButton", ElementGetter("Element"));
		public Element RegistrationCustomValidator {get {if (_RegistrationCustomValidator == null) {_RegistrationCustomValidator = (Element)Document.GetElementById(clientId + "_RegistrationCustomValidator");}; return _RegistrationCustomValidator;}} private Element _RegistrationCustomValidator;
		public jQueryObject RegistrationCustomValidatorJ {get {if (_RegistrationCustomValidatorJ == null) {_RegistrationCustomValidatorJ = jQuery.Select("#" + clientId + "_RegistrationCustomValidator");}; return _RegistrationCustomValidatorJ;}} private jQueryObject _RegistrationCustomValidatorJ;//mappings.Add("System.Web.UI.WebControls.CustomValidator", ElementGetter("Element"));
		public Element RegistrationValidationSummary {get {if (_RegistrationValidationSummary == null) {_RegistrationValidationSummary = (Element)Document.GetElementById(clientId + "_RegistrationValidationSummary");}; return _RegistrationValidationSummary;}} private Element _RegistrationValidationSummary;
		public jQueryObject RegistrationValidationSummaryJ {get {if (_RegistrationValidationSummaryJ == null) {_RegistrationValidationSummaryJ = jQuery.Select("#" + clientId + "_RegistrationValidationSummary");}; return _RegistrationValidationSummaryJ;}} private jQueryObject _RegistrationValidationSummaryJ;//mappings.Add("System.Web.UI.WebControls.ValidationSummary", ElementGetter("Element"));
		public Element JavascriptLabel {get {if (_JavascriptLabel == null) {_JavascriptLabel = (Element)Document.GetElementById(clientId + "_JavascriptLabel");}; return _JavascriptLabel;}} private Element _JavascriptLabel;
		public jQueryObject JavascriptLabelJ {get {if (_JavascriptLabelJ == null) {_JavascriptLabelJ = jQuery.Select("#" + clientId + "_JavascriptLabel");}; return _JavascriptLabelJ;}} private jQueryObject _JavascriptLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element GenericContainerPage {get {if (_GenericContainerPage == null) {_GenericContainerPage = (Element)Document.GetElementById(clientId + "_GenericContainerPage");}; return _GenericContainerPage;}} private Element _GenericContainerPage;
		public jQueryObject GenericContainerPageJ {get {if (_GenericContainerPageJ == null) {_GenericContainerPageJ = jQuery.Select("#" + clientId + "_GenericContainerPage");}; return _GenericContainerPageJ;}} private jQueryObject _GenericContainerPageJ;//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
	}
}
