//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlInputFile", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlTable", ElementGetter("Element"));
//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using jQueryApi;
using Js.Library;

namespace Js.Pages.Promoters.StyledSetup
{
	public partial class View
		 : Js.Pages.Promoters.PromoterUserControl.View
	{
		public string clientId;
		public View(string clientId)
			 : base(clientId)
		{
			this.clientId = clientId;
		}
		public Element H1Header {get {if (_H1Header == null) {_H1Header = (Element)Document.GetElementById(clientId + "_H1Header");}; return _H1Header;}} private Element _H1Header;
		public jQueryObject H1HeaderJ {get {if (_H1HeaderJ == null) {_H1HeaderJ = jQuery.Select("#" + clientId + "_H1Header");}; return _H1HeaderJ;}} private jQueryObject _H1HeaderJ;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public DivElement CustomiseOptionsPanel {get {if (_CustomiseOptionsPanel == null) {_CustomiseOptionsPanel = (DivElement)Document.GetElementById(clientId + "_CustomiseOptionsPanel");}; return _CustomiseOptionsPanel;}} private DivElement _CustomiseOptionsPanel;
		public jQueryObject CustomiseOptionsPanelJ {get {if (_CustomiseOptionsPanelJ == null) {_CustomiseOptionsPanelJ = jQuery.Select("#" + clientId + "_CustomiseOptionsPanel");}; return _CustomiseOptionsPanelJ;}} private jQueryObject _CustomiseOptionsPanelJ;
		public SelectElement CssDropDownList {get {if (_CssDropDownList == null) {_CssDropDownList = (SelectElement)Document.GetElementById(clientId + "_CssDropDownList");}; return _CssDropDownList;}} private SelectElement _CssDropDownList;
		public jQueryObject CssDropDownListJ {get {if (_CssDropDownListJ == null) {_CssDropDownListJ = jQuery.Select("#" + clientId + "_CssDropDownList");}; return _CssDropDownListJ;}} private jQueryObject _CssDropDownListJ;
		public Element InputCssFile {get {if (_InputCssFile == null) {_InputCssFile = (Element)Document.GetElementById(clientId + "_InputCssFile");}; return _InputCssFile;}} private Element _InputCssFile;
		public jQueryObject InputCssFileJ {get {if (_InputCssFileJ == null) {_InputCssFileJ = jQuery.Select("#" + clientId + "_InputCssFile");}; return _InputCssFileJ;}} private jQueryObject _InputCssFileJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlInputFile", ElementGetter("Element"));
		public InputElement UploadCssButton {get {if (_UploadCssButton == null) {_UploadCssButton = (InputElement)Document.GetElementById(clientId + "_UploadCssButton");}; return _UploadCssButton;}} private InputElement _UploadCssButton;
		public jQueryObject UploadCssButtonJ {get {if (_UploadCssButtonJ == null) {_UploadCssButtonJ = jQuery.Select("#" + clientId + "_UploadCssButton");}; return _UploadCssButtonJ;}} private jQueryObject _UploadCssButtonJ;
		public InputElement CssUrlHiddenTextBox {get {if (_CssUrlHiddenTextBox == null) {_CssUrlHiddenTextBox = (InputElement)Document.GetElementById(clientId + "_CssUrlHiddenTextBox");}; return _CssUrlHiddenTextBox;}} private InputElement _CssUrlHiddenTextBox;
		public jQueryObject CssUrlHiddenTextBoxJ {get {if (_CssUrlHiddenTextBoxJ == null) {_CssUrlHiddenTextBoxJ = jQuery.Select("#" + clientId + "_CssUrlHiddenTextBox");}; return _CssUrlHiddenTextBoxJ;}} private jQueryObject _CssUrlHiddenTextBoxJ;
		public Element InputLogoFile {get {if (_InputLogoFile == null) {_InputLogoFile = (Element)Document.GetElementById(clientId + "_InputLogoFile");}; return _InputLogoFile;}} private Element _InputLogoFile;
		public jQueryObject InputLogoFileJ {get {if (_InputLogoFileJ == null) {_InputLogoFileJ = jQuery.Select("#" + clientId + "_InputLogoFile");}; return _InputLogoFileJ;}} private jQueryObject _InputLogoFileJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlInputFile", ElementGetter("Element"));
		public InputElement UploadLogoButton {get {if (_UploadLogoButton == null) {_UploadLogoButton = (InputElement)Document.GetElementById(clientId + "_UploadLogoButton");}; return _UploadLogoButton;}} private InputElement _UploadLogoButton;
		public jQueryObject UploadLogoButtonJ {get {if (_UploadLogoButtonJ == null) {_UploadLogoButtonJ = jQuery.Select("#" + clientId + "_UploadLogoButton");}; return _UploadLogoButtonJ;}} private jQueryObject _UploadLogoButtonJ;
		public InputElement LogoUrlHiddenTextBox {get {if (_LogoUrlHiddenTextBox == null) {_LogoUrlHiddenTextBox = (InputElement)Document.GetElementById(clientId + "_LogoUrlHiddenTextBox");}; return _LogoUrlHiddenTextBox;}} private InputElement _LogoUrlHiddenTextBox;
		public jQueryObject LogoUrlHiddenTextBoxJ {get {if (_LogoUrlHiddenTextBoxJ == null) {_LogoUrlHiddenTextBoxJ = jQuery.Select("#" + clientId + "_LogoUrlHiddenTextBox");}; return _LogoUrlHiddenTextBoxJ;}} private jQueryObject _LogoUrlHiddenTextBoxJ;
		public SelectElement LogoAlignDropDownList {get {if (_LogoAlignDropDownList == null) {_LogoAlignDropDownList = (SelectElement)Document.GetElementById(clientId + "_LogoAlignDropDownList");}; return _LogoAlignDropDownList;}} private SelectElement _LogoAlignDropDownList;
		public jQueryObject LogoAlignDropDownListJ {get {if (_LogoAlignDropDownListJ == null) {_LogoAlignDropDownListJ = jQuery.Select("#" + clientId + "_LogoAlignDropDownList");}; return _LogoAlignDropDownListJ;}} private jQueryObject _LogoAlignDropDownListJ;
		public Element InputBackgroundFile {get {if (_InputBackgroundFile == null) {_InputBackgroundFile = (Element)Document.GetElementById(clientId + "_InputBackgroundFile");}; return _InputBackgroundFile;}} private Element _InputBackgroundFile;
		public jQueryObject InputBackgroundFileJ {get {if (_InputBackgroundFileJ == null) {_InputBackgroundFileJ = jQuery.Select("#" + clientId + "_InputBackgroundFile");}; return _InputBackgroundFileJ;}} private jQueryObject _InputBackgroundFileJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlInputFile", ElementGetter("Element"));
		public InputElement UploadBackgroundButton {get {if (_UploadBackgroundButton == null) {_UploadBackgroundButton = (InputElement)Document.GetElementById(clientId + "_UploadBackgroundButton");}; return _UploadBackgroundButton;}} private InputElement _UploadBackgroundButton;
		public jQueryObject UploadBackgroundButtonJ {get {if (_UploadBackgroundButtonJ == null) {_UploadBackgroundButtonJ = jQuery.Select("#" + clientId + "_UploadBackgroundButton");}; return _UploadBackgroundButtonJ;}} private jQueryObject _UploadBackgroundButtonJ;
		public InputElement BackgroundUrlHiddenTextBox {get {if (_BackgroundUrlHiddenTextBox == null) {_BackgroundUrlHiddenTextBox = (InputElement)Document.GetElementById(clientId + "_BackgroundUrlHiddenTextBox");}; return _BackgroundUrlHiddenTextBox;}} private InputElement _BackgroundUrlHiddenTextBox;
		public jQueryObject BackgroundUrlHiddenTextBoxJ {get {if (_BackgroundUrlHiddenTextBoxJ == null) {_BackgroundUrlHiddenTextBoxJ = jQuery.Select("#" + clientId + "_BackgroundUrlHiddenTextBox");}; return _BackgroundUrlHiddenTextBoxJ;}} private jQueryObject _BackgroundUrlHiddenTextBoxJ;
		public CheckBoxElement NoRepeatBackgroundCheckBox {get {if (_NoRepeatBackgroundCheckBox == null) {_NoRepeatBackgroundCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_NoRepeatBackgroundCheckBox");}; return _NoRepeatBackgroundCheckBox;}} private CheckBoxElement _NoRepeatBackgroundCheckBox;
		public jQueryObject NoRepeatBackgroundCheckBoxJ {get {if (_NoRepeatBackgroundCheckBoxJ == null) {_NoRepeatBackgroundCheckBoxJ = jQuery.Select("#" + clientId + "_NoRepeatBackgroundCheckBox");}; return _NoRepeatBackgroundCheckBoxJ;}} private jQueryObject _NoRepeatBackgroundCheckBoxJ;
		public Element CustomiseTable {get {if (_CustomiseTable == null) {_CustomiseTable = (Element)Document.GetElementById(clientId + "_CustomiseTable");}; return _CustomiseTable;}} private Element _CustomiseTable;
		public jQueryObject CustomiseTableJ {get {if (_CustomiseTableJ == null) {_CustomiseTableJ = jQuery.Select("#" + clientId + "_CustomiseTable");}; return _CustomiseTableJ;}} private jQueryObject _CustomiseTableJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlTable", ElementGetter("Element"));
		public SelectElement FontFamilyDropDownList {get {if (_FontFamilyDropDownList == null) {_FontFamilyDropDownList = (SelectElement)Document.GetElementById(clientId + "_FontFamilyDropDownList");}; return _FontFamilyDropDownList;}} private SelectElement _FontFamilyDropDownList;
		public jQueryObject FontFamilyDropDownListJ {get {if (_FontFamilyDropDownListJ == null) {_FontFamilyDropDownListJ = jQuery.Select("#" + clientId + "_FontFamilyDropDownList");}; return _FontFamilyDropDownListJ;}} private jQueryObject _FontFamilyDropDownListJ;
		public InputElement BodyTextColourInput {get {if (_BodyTextColourInput == null) {_BodyTextColourInput = (InputElement)Document.GetElementById(clientId + "_BodyTextColourInput");}; return _BodyTextColourInput;}} private InputElement _BodyTextColourInput;
		public jQueryObject BodyTextColourInputJ {get {if (_BodyTextColourInputJ == null) {_BodyTextColourInputJ = jQuery.Select("#" + clientId + "_BodyTextColourInput");}; return _BodyTextColourInputJ;}} private jQueryObject _BodyTextColourInputJ;
		public InputElement BodyBackgroundColourInput {get {if (_BodyBackgroundColourInput == null) {_BodyBackgroundColourInput = (InputElement)Document.GetElementById(clientId + "_BodyBackgroundColourInput");}; return _BodyBackgroundColourInput;}} private InputElement _BodyBackgroundColourInput;
		public jQueryObject BodyBackgroundColourInputJ {get {if (_BodyBackgroundColourInputJ == null) {_BodyBackgroundColourInputJ = jQuery.Select("#" + clientId + "_BodyBackgroundColourInput");}; return _BodyBackgroundColourInputJ;}} private jQueryObject _BodyBackgroundColourInputJ;
		public SelectElement BodyFontSizeDropDownList {get {if (_BodyFontSizeDropDownList == null) {_BodyFontSizeDropDownList = (SelectElement)Document.GetElementById(clientId + "_BodyFontSizeDropDownList");}; return _BodyFontSizeDropDownList;}} private SelectElement _BodyFontSizeDropDownList;
		public jQueryObject BodyFontSizeDropDownListJ {get {if (_BodyFontSizeDropDownListJ == null) {_BodyFontSizeDropDownListJ = jQuery.Select("#" + clientId + "_BodyFontSizeDropDownList");}; return _BodyFontSizeDropDownListJ;}} private jQueryObject _BodyFontSizeDropDownListJ;
		public SelectElement BodyFontWeightDropDownList {get {if (_BodyFontWeightDropDownList == null) {_BodyFontWeightDropDownList = (SelectElement)Document.GetElementById(clientId + "_BodyFontWeightDropDownList");}; return _BodyFontWeightDropDownList;}} private SelectElement _BodyFontWeightDropDownList;
		public jQueryObject BodyFontWeightDropDownListJ {get {if (_BodyFontWeightDropDownListJ == null) {_BodyFontWeightDropDownListJ = jQuery.Select("#" + clientId + "_BodyFontWeightDropDownList");}; return _BodyFontWeightDropDownListJ;}} private jQueryObject _BodyFontWeightDropDownListJ;
		public SelectElement BodyTextDecorationDropDownList {get {if (_BodyTextDecorationDropDownList == null) {_BodyTextDecorationDropDownList = (SelectElement)Document.GetElementById(clientId + "_BodyTextDecorationDropDownList");}; return _BodyTextDecorationDropDownList;}} private SelectElement _BodyTextDecorationDropDownList;
		public jQueryObject BodyTextDecorationDropDownListJ {get {if (_BodyTextDecorationDropDownListJ == null) {_BodyTextDecorationDropDownListJ = jQuery.Select("#" + clientId + "_BodyTextDecorationDropDownList");}; return _BodyTextDecorationDropDownListJ;}} private jQueryObject _BodyTextDecorationDropDownListJ;
		public SelectElement BodyTextAlignDropDownList {get {if (_BodyTextAlignDropDownList == null) {_BodyTextAlignDropDownList = (SelectElement)Document.GetElementById(clientId + "_BodyTextAlignDropDownList");}; return _BodyTextAlignDropDownList;}} private SelectElement _BodyTextAlignDropDownList;
		public jQueryObject BodyTextAlignDropDownListJ {get {if (_BodyTextAlignDropDownListJ == null) {_BodyTextAlignDropDownListJ = jQuery.Select("#" + clientId + "_BodyTextAlignDropDownList");}; return _BodyTextAlignDropDownListJ;}} private jQueryObject _BodyTextAlignDropDownListJ;
		public InputElement HeaderTextColourInput {get {if (_HeaderTextColourInput == null) {_HeaderTextColourInput = (InputElement)Document.GetElementById(clientId + "_HeaderTextColourInput");}; return _HeaderTextColourInput;}} private InputElement _HeaderTextColourInput;
		public jQueryObject HeaderTextColourInputJ {get {if (_HeaderTextColourInputJ == null) {_HeaderTextColourInputJ = jQuery.Select("#" + clientId + "_HeaderTextColourInput");}; return _HeaderTextColourInputJ;}} private jQueryObject _HeaderTextColourInputJ;
		public InputElement HeaderBackgroundColourInput {get {if (_HeaderBackgroundColourInput == null) {_HeaderBackgroundColourInput = (InputElement)Document.GetElementById(clientId + "_HeaderBackgroundColourInput");}; return _HeaderBackgroundColourInput;}} private InputElement _HeaderBackgroundColourInput;
		public jQueryObject HeaderBackgroundColourInputJ {get {if (_HeaderBackgroundColourInputJ == null) {_HeaderBackgroundColourInputJ = jQuery.Select("#" + clientId + "_HeaderBackgroundColourInput");}; return _HeaderBackgroundColourInputJ;}} private jQueryObject _HeaderBackgroundColourInputJ;
		public SelectElement HeaderFontSizeDropDownList {get {if (_HeaderFontSizeDropDownList == null) {_HeaderFontSizeDropDownList = (SelectElement)Document.GetElementById(clientId + "_HeaderFontSizeDropDownList");}; return _HeaderFontSizeDropDownList;}} private SelectElement _HeaderFontSizeDropDownList;
		public jQueryObject HeaderFontSizeDropDownListJ {get {if (_HeaderFontSizeDropDownListJ == null) {_HeaderFontSizeDropDownListJ = jQuery.Select("#" + clientId + "_HeaderFontSizeDropDownList");}; return _HeaderFontSizeDropDownListJ;}} private jQueryObject _HeaderFontSizeDropDownListJ;
		public SelectElement HeaderFontWeightDropDownList {get {if (_HeaderFontWeightDropDownList == null) {_HeaderFontWeightDropDownList = (SelectElement)Document.GetElementById(clientId + "_HeaderFontWeightDropDownList");}; return _HeaderFontWeightDropDownList;}} private SelectElement _HeaderFontWeightDropDownList;
		public jQueryObject HeaderFontWeightDropDownListJ {get {if (_HeaderFontWeightDropDownListJ == null) {_HeaderFontWeightDropDownListJ = jQuery.Select("#" + clientId + "_HeaderFontWeightDropDownList");}; return _HeaderFontWeightDropDownListJ;}} private jQueryObject _HeaderFontWeightDropDownListJ;
		public SelectElement HeaderTextDecorationDropDownList {get {if (_HeaderTextDecorationDropDownList == null) {_HeaderTextDecorationDropDownList = (SelectElement)Document.GetElementById(clientId + "_HeaderTextDecorationDropDownList");}; return _HeaderTextDecorationDropDownList;}} private SelectElement _HeaderTextDecorationDropDownList;
		public jQueryObject HeaderTextDecorationDropDownListJ {get {if (_HeaderTextDecorationDropDownListJ == null) {_HeaderTextDecorationDropDownListJ = jQuery.Select("#" + clientId + "_HeaderTextDecorationDropDownList");}; return _HeaderTextDecorationDropDownListJ;}} private jQueryObject _HeaderTextDecorationDropDownListJ;
		public SelectElement HeaderTextAlignDropDownList {get {if (_HeaderTextAlignDropDownList == null) {_HeaderTextAlignDropDownList = (SelectElement)Document.GetElementById(clientId + "_HeaderTextAlignDropDownList");}; return _HeaderTextAlignDropDownList;}} private SelectElement _HeaderTextAlignDropDownList;
		public jQueryObject HeaderTextAlignDropDownListJ {get {if (_HeaderTextAlignDropDownListJ == null) {_HeaderTextAlignDropDownListJ = jQuery.Select("#" + clientId + "_HeaderTextAlignDropDownList");}; return _HeaderTextAlignDropDownListJ;}} private jQueryObject _HeaderTextAlignDropDownListJ;
		public InputElement LinksTextColourInput {get {if (_LinksTextColourInput == null) {_LinksTextColourInput = (InputElement)Document.GetElementById(clientId + "_LinksTextColourInput");}; return _LinksTextColourInput;}} private InputElement _LinksTextColourInput;
		public jQueryObject LinksTextColourInputJ {get {if (_LinksTextColourInputJ == null) {_LinksTextColourInputJ = jQuery.Select("#" + clientId + "_LinksTextColourInput");}; return _LinksTextColourInputJ;}} private jQueryObject _LinksTextColourInputJ;
		public InputElement LinksBackgroundColourInput {get {if (_LinksBackgroundColourInput == null) {_LinksBackgroundColourInput = (InputElement)Document.GetElementById(clientId + "_LinksBackgroundColourInput");}; return _LinksBackgroundColourInput;}} private InputElement _LinksBackgroundColourInput;
		public jQueryObject LinksBackgroundColourInputJ {get {if (_LinksBackgroundColourInputJ == null) {_LinksBackgroundColourInputJ = jQuery.Select("#" + clientId + "_LinksBackgroundColourInput");}; return _LinksBackgroundColourInputJ;}} private jQueryObject _LinksBackgroundColourInputJ;
		public SelectElement LinksFontSizeDropDownList {get {if (_LinksFontSizeDropDownList == null) {_LinksFontSizeDropDownList = (SelectElement)Document.GetElementById(clientId + "_LinksFontSizeDropDownList");}; return _LinksFontSizeDropDownList;}} private SelectElement _LinksFontSizeDropDownList;
		public jQueryObject LinksFontSizeDropDownListJ {get {if (_LinksFontSizeDropDownListJ == null) {_LinksFontSizeDropDownListJ = jQuery.Select("#" + clientId + "_LinksFontSizeDropDownList");}; return _LinksFontSizeDropDownListJ;}} private jQueryObject _LinksFontSizeDropDownListJ;
		public SelectElement LinksFontWeightDropDownList {get {if (_LinksFontWeightDropDownList == null) {_LinksFontWeightDropDownList = (SelectElement)Document.GetElementById(clientId + "_LinksFontWeightDropDownList");}; return _LinksFontWeightDropDownList;}} private SelectElement _LinksFontWeightDropDownList;
		public jQueryObject LinksFontWeightDropDownListJ {get {if (_LinksFontWeightDropDownListJ == null) {_LinksFontWeightDropDownListJ = jQuery.Select("#" + clientId + "_LinksFontWeightDropDownList");}; return _LinksFontWeightDropDownListJ;}} private jQueryObject _LinksFontWeightDropDownListJ;
		public SelectElement LinksTextDecorationDropDownList {get {if (_LinksTextDecorationDropDownList == null) {_LinksTextDecorationDropDownList = (SelectElement)Document.GetElementById(clientId + "_LinksTextDecorationDropDownList");}; return _LinksTextDecorationDropDownList;}} private SelectElement _LinksTextDecorationDropDownList;
		public jQueryObject LinksTextDecorationDropDownListJ {get {if (_LinksTextDecorationDropDownListJ == null) {_LinksTextDecorationDropDownListJ = jQuery.Select("#" + clientId + "_LinksTextDecorationDropDownList");}; return _LinksTextDecorationDropDownListJ;}} private jQueryObject _LinksTextDecorationDropDownListJ;
		public SelectElement LinksTextAlignDropDownList {get {if (_LinksTextAlignDropDownList == null) {_LinksTextAlignDropDownList = (SelectElement)Document.GetElementById(clientId + "_LinksTextAlignDropDownList");}; return _LinksTextAlignDropDownList;}} private SelectElement _LinksTextAlignDropDownList;
		public jQueryObject LinksTextAlignDropDownListJ {get {if (_LinksTextAlignDropDownListJ == null) {_LinksTextAlignDropDownListJ = jQuery.Select("#" + clientId + "_LinksTextAlignDropDownList");}; return _LinksTextAlignDropDownListJ;}} private jQueryObject _LinksTextAlignDropDownListJ;
		public InputElement LinksHoverTextColourInput {get {if (_LinksHoverTextColourInput == null) {_LinksHoverTextColourInput = (InputElement)Document.GetElementById(clientId + "_LinksHoverTextColourInput");}; return _LinksHoverTextColourInput;}} private InputElement _LinksHoverTextColourInput;
		public jQueryObject LinksHoverTextColourInputJ {get {if (_LinksHoverTextColourInputJ == null) {_LinksHoverTextColourInputJ = jQuery.Select("#" + clientId + "_LinksHoverTextColourInput");}; return _LinksHoverTextColourInputJ;}} private jQueryObject _LinksHoverTextColourInputJ;
		public InputElement LinksHoverBackgroundColourInput {get {if (_LinksHoverBackgroundColourInput == null) {_LinksHoverBackgroundColourInput = (InputElement)Document.GetElementById(clientId + "_LinksHoverBackgroundColourInput");}; return _LinksHoverBackgroundColourInput;}} private InputElement _LinksHoverBackgroundColourInput;
		public jQueryObject LinksHoverBackgroundColourInputJ {get {if (_LinksHoverBackgroundColourInputJ == null) {_LinksHoverBackgroundColourInputJ = jQuery.Select("#" + clientId + "_LinksHoverBackgroundColourInput");}; return _LinksHoverBackgroundColourInputJ;}} private jQueryObject _LinksHoverBackgroundColourInputJ;
		public SelectElement LinksHoverFontSizeDropDownList {get {if (_LinksHoverFontSizeDropDownList == null) {_LinksHoverFontSizeDropDownList = (SelectElement)Document.GetElementById(clientId + "_LinksHoverFontSizeDropDownList");}; return _LinksHoverFontSizeDropDownList;}} private SelectElement _LinksHoverFontSizeDropDownList;
		public jQueryObject LinksHoverFontSizeDropDownListJ {get {if (_LinksHoverFontSizeDropDownListJ == null) {_LinksHoverFontSizeDropDownListJ = jQuery.Select("#" + clientId + "_LinksHoverFontSizeDropDownList");}; return _LinksHoverFontSizeDropDownListJ;}} private jQueryObject _LinksHoverFontSizeDropDownListJ;
		public SelectElement LinksHoverFontWeightDropDownList {get {if (_LinksHoverFontWeightDropDownList == null) {_LinksHoverFontWeightDropDownList = (SelectElement)Document.GetElementById(clientId + "_LinksHoverFontWeightDropDownList");}; return _LinksHoverFontWeightDropDownList;}} private SelectElement _LinksHoverFontWeightDropDownList;
		public jQueryObject LinksHoverFontWeightDropDownListJ {get {if (_LinksHoverFontWeightDropDownListJ == null) {_LinksHoverFontWeightDropDownListJ = jQuery.Select("#" + clientId + "_LinksHoverFontWeightDropDownList");}; return _LinksHoverFontWeightDropDownListJ;}} private jQueryObject _LinksHoverFontWeightDropDownListJ;
		public SelectElement LinksHoverTextDecorationDropDownList {get {if (_LinksHoverTextDecorationDropDownList == null) {_LinksHoverTextDecorationDropDownList = (SelectElement)Document.GetElementById(clientId + "_LinksHoverTextDecorationDropDownList");}; return _LinksHoverTextDecorationDropDownList;}} private SelectElement _LinksHoverTextDecorationDropDownList;
		public jQueryObject LinksHoverTextDecorationDropDownListJ {get {if (_LinksHoverTextDecorationDropDownListJ == null) {_LinksHoverTextDecorationDropDownListJ = jQuery.Select("#" + clientId + "_LinksHoverTextDecorationDropDownList");}; return _LinksHoverTextDecorationDropDownListJ;}} private jQueryObject _LinksHoverTextDecorationDropDownListJ;
		public SelectElement LinksHoverTextAlignDropDownList {get {if (_LinksHoverTextAlignDropDownList == null) {_LinksHoverTextAlignDropDownList = (SelectElement)Document.GetElementById(clientId + "_LinksHoverTextAlignDropDownList");}; return _LinksHoverTextAlignDropDownList;}} private SelectElement _LinksHoverTextAlignDropDownList;
		public jQueryObject LinksHoverTextAlignDropDownListJ {get {if (_LinksHoverTextAlignDropDownListJ == null) {_LinksHoverTextAlignDropDownListJ = jQuery.Select("#" + clientId + "_LinksHoverTextAlignDropDownList");}; return _LinksHoverTextAlignDropDownListJ;}} private jQueryObject _LinksHoverTextAlignDropDownListJ;
		public InputElement SaveCustomStyleButton {get {if (_SaveCustomStyleButton == null) {_SaveCustomStyleButton = (InputElement)Document.GetElementById(clientId + "_SaveCustomStyleButton");}; return _SaveCustomStyleButton;}} private InputElement _SaveCustomStyleButton;
		public jQueryObject SaveCustomStyleButtonJ {get {if (_SaveCustomStyleButtonJ == null) {_SaveCustomStyleButtonJ = jQuery.Select("#" + clientId + "_SaveCustomStyleButton");}; return _SaveCustomStyleButtonJ;}} private jQueryObject _SaveCustomStyleButtonJ;
		public AnchorElement LinkToStyledPages {get {if (_LinkToStyledPages == null) {_LinkToStyledPages = (AnchorElement)Document.GetElementById(clientId + "_LinkToStyledPages");}; return _LinkToStyledPages;}} private AnchorElement _LinkToStyledPages;
		public jQueryObject LinkToStyledPagesJ {get {if (_LinkToStyledPagesJ == null) {_LinkToStyledPagesJ = jQuery.Select("#" + clientId + "_LinkToStyledPages");}; return _LinkToStyledPagesJ;}} private jQueryObject _LinkToStyledPagesJ;
		public Element GenericContainerPage {get {if (_GenericContainerPage == null) {_GenericContainerPage = (Element)Document.GetElementById(clientId + "_GenericContainerPage");}; return _GenericContainerPage;}} private Element _GenericContainerPage;
		public jQueryObject GenericContainerPageJ {get {if (_GenericContainerPageJ == null) {_GenericContainerPageJ = jQuery.Select("#" + clientId + "_GenericContainerPage");}; return _GenericContainerPageJ;}} private jQueryObject _GenericContainerPageJ;//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
	}
}
