//mappings.Add("System.Web.UI.WebControls.LinkButton", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlTextArea", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using Js.Mobile.Library;

namespace Js.Mobile.Controls.Navigation.Login
{
	public class Server {
		public Server(){}
		public void CheckEmail(System.String email, Response response) { object[] paramArr = { email }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "CheckEmail", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void NoFacebookNewAccount(Dictionary noFacebookSignupPanelData, Dictionary detailsPanelData, Dictionary captchaData, Response response) { object[] paramArr = { noFacebookSignupPanelData, detailsPanelData, captchaData }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "NoFacebookNewAccount", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void GetUniqueNickName(System.String nickname, System.Int32 usrK, Response response) { object[] paramArr = { nickname, usrK }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "GetUniqueNickName", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void NoFacebookLogin(System.String nickNameOrEmail, System.String password, Dictionary captchaData, Dictionary noFacebookSignupPanelData, Dictionary detailsPanelData, System.Boolean autoLogin, System.Int32 autoLoginUsrK, System.String autoLoginString, Response response) { object[] paramArr = { nickNameOrEmail, password, captchaData, noFacebookSignupPanelData, detailsPanelData, autoLogin, autoLoginUsrK, autoLoginString }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "NoFacebookLogin", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void SendPassword(System.String emailOrNickname, Response response) { object[] paramArr = { emailOrNickname }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "SendPassword", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void SwitchAccounts(System.String currentUIDFromFacebook, System.Int32 autoLoginUsrK, System.String autoLoginUsrLoginString, Dictionary detailsPanelData, Response response) { object[] paramArr = { currentUIDFromFacebook, autoLoginUsrK, autoLoginUsrLoginString, detailsPanelData }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "SwitchAccounts", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void CreateNewAccount(Dictionary detailsPanelData, Response response) { object[] paramArr = { detailsPanelData }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "CreateNewAccount", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void GetHomePlaceFromFacebook(Response response) { object[] paramArr = {  }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "GetHomePlaceFromFacebook", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void GetUserByFacebookUID(System.Int32 autoLoginUsrK, System.String autoLoginUsrLoginString, Response response) { object[] paramArr = { autoLoginUsrK, autoLoginUsrLoginString }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "GetUserByFacebookUID", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void AutoLinkByAutoLoginUsr(System.Int32 autoLoginUsrK, System.String autoLoginUsrLoginString, Dictionary detailsPanelData, Response response) { object[] paramArr = { autoLoginUsrK, autoLoginUsrLoginString, detailsPanelData }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "AutoLinkByAutoLoginUsr", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void AutoLinkByEmail(Dictionary detailsPanelData, Response response) { object[] paramArr = { detailsPanelData }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "AutoLinkByEmail", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void LinkAccounts(System.String nickNameOrEmail, System.String password, Dictionary detailsPanelData, Response response) { object[] paramArr = { nickNameOrEmail, password, detailsPanelData }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "LinkAccounts", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void UnlinkAccount(System.String password, Response response) { object[] paramArr = { password }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.Controls.Navigation.Login, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "UnlinkAccount", paramArr, response, response); } catch (Exception e) { Dictionary d = new Dictionary(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
	}
	public partial class View
	{
		public string clientId;
		public Server server;
		public View(string clientId)
		{
			this.clientId = clientId;
			this.server = new Server();
		}
		public Element ToggleAdminLinkButton {get {return (Element) Document.GetElementById(clientId + "_ToggleAdminLinkButton");}}//mappings.Add("System.Web.UI.WebControls.LinkButton", ElementGetter("Element"));
		public Element ConnectDialog {get {return (Element) Document.GetElementById(clientId + "_ConnectDialog");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_Inner {get {return (Element) Document.GetElementById(clientId + "_Connect_Inner");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_Note {get {return (Element) Document.GetElementById(clientId + "_Connect_Note");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_LoadingLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoadingLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_LoadingPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoadingPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_Loading_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Loading_CancelButton");}}
		public Element Connect_ConnectingPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_ConnectingPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_Connecting_PopupRetry {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Connecting_PopupRetry");}}
		public InputElement Connect_Connecting_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Connecting_BackButton");}}
		public InputElement Connect_Connecting_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Connecting_CancelButton");}}
		public Element Connect_ErrorPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_ErrorPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_Error_ErrorDescription {get {return (Element) Document.GetElementById(clientId + "_Connect_Error_ErrorDescription");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_Error_TryAgainButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Error_TryAgainButton");}}
		public InputElement Connect_Error_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Error_CancelButton");}}
		public Element Connect_LoggedOutPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOutPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_ConnectButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_ConnectButton");}}
		public InputElement Connect_LoggedOut_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_CancelButton");}}
		public InputElement Connect_LoggedOut_NoFacebookButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebookButton");}}
		public Element Connect_LoggedOut_NoFacebook_ChoosePanel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_ChoosePanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_Choose_LoginButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Choose_LoginButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_Choose_SignupButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Choose_SignupButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_Choose_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Choose_BackButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_Choose_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Choose_CancelButton");}}
		public Element Connect_LoggedOut_NoFacebook_LoginPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_LoginPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_Login_UsernameTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Login_UsernameTextbox");}}
		public InputElement Connect_LoggedOut_NoFacebook_Login_PasswordTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Login_PasswordTextbox");}}
		public Element Connect_LoggedOut_NoFacebook_Login_Error {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Login_Error");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_Login_LoginButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Login_LoginButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_Login_NoPasswordButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Login_NoPasswordButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_Login_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Login_BackButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_Login_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Login_CancelButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_Login_ForgottonPasswordButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_Login_ForgottonPasswordButton");}}
		public Element Connect_LoggedOut_NoFacebook_LoginNoPasswordPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_LoginNoPasswordPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_LoginNoPassword_TryAgainButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_LoginNoPassword_TryAgainButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_LoginNoPassword_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_LoginNoPassword_CancelButton");}}
		public Element Connect_LoggedOut_NoFacebook_PasswordResetPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_PasswordResetPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_LoggedOut_NoFacebook_PasswordReset_Title {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_PasswordReset_Title");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_PasswordReset_UsernameTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_PasswordReset_UsernameTextbox");}}
		public InputElement Connect_LoggedOut_NoFacebook_PasswordReset_SendLinkButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_PasswordReset_SendLinkButton");}}
		public Element Connect_LoggedOut_NoFacebook_PasswordReset_MessageLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_PasswordReset_MessageLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_LoggedOut_NoFacebook_PasswordReset_ErrorLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_PasswordReset_ErrorLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_PasswordReset_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_PasswordReset_BackButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_PasswordReset_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_PasswordReset_CancelButton");}}
		public Element Connect_LoggedOut_NoFacebook_SignUp1Panel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1Panel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_LoggedOut_NoFacebook_SignUp1_EmailPara {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1_EmailPara");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_SignUp1_EmailTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1_EmailTextbox");}}
		public InputElement Connect_LoggedOut_NoFacebook_SignUp1_Password1Textbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1_Password1Textbox");}}
		public InputElement Connect_LoggedOut_NoFacebook_SignUp1_Password2Textbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1_Password2Textbox");}}
		public InputElement Connect_LoggedOut_NoFacebook_SignUp1_SaveButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1_SaveButton");}}
		public Element Connect_LoggedOut_NoFacebook_SignUp1_ErrorLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1_ErrorLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_SignUp1_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1_BackButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_SignUp1_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp1_CancelButton");}}
		public Element Connect_LoggedOut_NoFacebook_SignUp2Panel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2Panel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_SignUp2_FirstNameTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_FirstNameTextbox");}}
		public InputElement Connect_LoggedOut_NoFacebook_SignUp2_LastNameTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_LastNameTextbox");}}
		public InputElement Connect_LoggedOut_NoFacebook_SignUp2_NicknameTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_NicknameTextbox");}}
		public SelectElement Connect_LoggedOut_NoFacebook_SignUp2_DateOfBirthDayDropDown {get {return (SelectElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_DateOfBirthDayDropDown");}}
		public SelectElement Connect_LoggedOut_NoFacebook_SignUp2_DateOfBirthMonthDropDown {get {return (SelectElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_DateOfBirthMonthDropDown");}}
		public SelectElement Connect_LoggedOut_NoFacebook_SignUp2_DateOfBirthYearDropDown {get {return (SelectElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_DateOfBirthYearDropDown");}}
		public CheckBoxElement Connect_LoggedOut_NoFacebook_SignUp2_SexMaleRadio {get {return (CheckBoxElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_SexMaleRadio");}}
		public CheckBoxElement Connect_LoggedOut_NoFacebook_SignUp2_SexFemaleRadio {get {return (CheckBoxElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_SexFemaleRadio");}}
		public InputElement Connect_LoggedOut_NoFacebook_SignUp2_SaveButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_SaveButton");}}
		public Element Connect_LoggedOut_NoFacebook_SignUp2_ErrorLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_ErrorLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedOut_NoFacebook_SignUp2_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_BackButton");}}
		public InputElement Connect_LoggedOut_NoFacebook_SignUp2_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedOut_NoFacebook_SignUp2_CancelButton");}}
		public Element Connect_NewAccount_ConfirmFacebookPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_ConfirmFacebookPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public ImageElement Connect_NewAccount_ConfirmFacebook_Image {get {return (ImageElement) Document.GetElementById(clientId + "_Connect_NewAccount_ConfirmFacebook_Image");}}
		public AnchorElement Connect_NewAccount_ConfirmFacebook_Link {get {return (AnchorElement) Document.GetElementById(clientId + "_Connect_NewAccount_ConfirmFacebook_Link");}}
		public InputElement Connect_NewAccount_ConfirmFacebook_YesButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ConfirmFacebook_YesButton");}}
		public InputElement Connect_NewAccount_ConfirmFacebook_NoButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ConfirmFacebook_NoButton");}}
		public InputElement Connect_NewAccount_ConfirmFacebook_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ConfirmFacebook_BackButton");}}
		public InputElement Connect_NewAccount_ConfirmFacebook_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ConfirmFacebook_CancelButton");}}
		public Element Connect_NewAccount_NoEmailMatchPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_NoEmailMatchPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_NewAccount_NoEmailMatch_NewAccountButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_NoEmailMatch_NewAccountButton");}}
		public InputElement Connect_NewAccount_NoEmailMatch_ChooseAccountButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_NoEmailMatch_ChooseAccountButton");}}
		public InputElement Connect_NewAccount_NoEmailMatch_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_NoEmailMatch_CancelButton");}}
		public InputElement Connect_NewAccount_NoEmailMatch_FacebookLogoutButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_NoEmailMatch_FacebookLogoutButton");}}
		public InputElement Connect_NewAccount_NoEmailMatch_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_NoEmailMatch_BackButton");}}
		public Element Connect_NewAccount_EmailMatchPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_EmailMatchPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_NewAccount_EmailMatch_UserLink1 {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_EmailMatch_UserLink1");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_NewAccount_EmailMatch_AutoConnectButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_EmailMatch_AutoConnectButton");}}
		public InputElement Connect_NewAccount_EmailMatch_ChooseAccountButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_EmailMatch_ChooseAccountButton");}}
		public InputElement Connect_NewAccount_EmailMatch_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_EmailMatch_CancelButton");}}
		public InputElement Connect_NewAccount_EmailMatch_FacebookLogoutButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_EmailMatch_FacebookLogoutButton");}}
		public InputElement Connect_NewAccount_EmailMatch_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_EmailMatch_BackButton");}}
		public Element Connect_NewAccount_ChooseAccountPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccountPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_NewAccount_ChooseAccount_UsernameTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccount_UsernameTextbox");}}
		public InputElement Connect_NewAccount_ChooseAccount_PasswordTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccount_PasswordTextbox");}}
		public InputElement Connect_NewAccount_ChooseAccount_LinkAccountButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccount_LinkAccountButton");}}
		public Element Connect_NewAccount_ChooseAccount_ErrorLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccount_ErrorLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_NewAccount_ChooseAccount_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccount_CancelButton");}}
		public InputElement Connect_NewAccount_ChooseAccount_FacebookLogoutButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccount_FacebookLogoutButton");}}
		public InputElement Connect_NewAccount_ChooseAccount_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccount_BackButton");}}
		public InputElement Connect_NewAccount_ChooseAccount_ForgottonPasswordButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ChooseAccount_ForgottonPasswordButton");}}
		public Element Connect_NewAccount_ForgotPasswordPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_ForgotPasswordPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_NewAccount_ForgotPassword_UsernameTextbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ForgotPassword_UsernameTextbox");}}
		public InputElement Connect_NewAccount_ForgotPassword_SendLinkButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ForgotPassword_SendLinkButton");}}
		public Element Connect_NewAccount_ForgotPassword_MessageLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_ForgotPassword_MessageLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_NewAccount_ForgotPassword_ErrorLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_NewAccount_ForgotPassword_ErrorLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_NewAccount_ForgotPassword_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ForgotPassword_CancelButton");}}
		public InputElement Connect_NewAccount_ForgotPassword_FacebookLogoutButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ForgotPassword_FacebookLogoutButton");}}
		public InputElement Connect_NewAccount_ForgotPassword_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_NewAccount_ForgotPassword_BackButton");}}
		public Element Connect_LoggedInPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedInPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_LoggedIn_LoggedInUsrLink {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedIn_LoggedInUsrLink");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedIn_CloseButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedIn_CloseButton");}}
		public InputElement Connect_LoggedIn_LogoutButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedIn_LogoutButton");}}
		public Element Connect_LoggedIn_DisconnectLinkOuter {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedIn_DisconnectLinkOuter");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement Connect_LoggedIn_DisconnectButtonShowLink {get {return (AnchorElement) Document.GetElementById(clientId + "_Connect_LoggedIn_DisconnectButtonShowLink");}}
		public Element Connect_LoggedIn_DisconnectButtonOuter {get {return (Element) Document.GetElementById(clientId + "_Connect_LoggedIn_DisconnectButtonOuter");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LoggedIn_DisconnectButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedIn_DisconnectButton");}}
		public InputElement Connect_LoggedIn_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LoggedIn_CancelButton");}}
		public Element Connect_AutoLoginMismatchPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_AutoLoginMismatchPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_AutoLoginMismatch_AutoLoginUsrLink {get {return (Element) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_AutoLoginUsrLink");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_AutoLoginMismatch_RetryButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_RetryButton");}}
		public InputElement Connect_AutoLoginMismatch_ContinueButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_ContinueButton");}}
		public Element Connect_AutoLoginMismatch_SwitchAccountsPara {get {return (Element) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_SwitchAccountsPara");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_AutoLoginMismatch_AutoLoginUsrLink2 {get {return (Element) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_AutoLoginUsrLink2");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement Connect_AutoLoginMismatch_SwitchAccountsShowLink {get {return (AnchorElement) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_SwitchAccountsShowLink");}}
		public Element Connect_AutoLoginMismatch_SwitchAccountsOuter {get {return (Element) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_SwitchAccountsOuter");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_AutoLoginMismatch_SwitchButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_SwitchButton");}}
		public InputElement Connect_AutoLoginMismatch_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_AutoLoginMismatch_CancelButton");}}
		public Element Connect_CreatePasswordPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_CreatePasswordPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_CreatePassword_Password1Textbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_CreatePassword_Password1Textbox");}}
		public InputElement Connect_CreatePassword_Password2Textbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_CreatePassword_Password2Textbox");}}
		public InputElement Connect_CreatePassword_DisconnectButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_CreatePassword_DisconnectButton");}}
		public Element Connect_CreatePassword_ErrorSpan {get {return (Element) Document.GetElementById(clientId + "_Connect_CreatePassword_ErrorSpan");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_CreatePassword_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_CreatePassword_CancelButton");}}
		public InputElement Connect_CreatePassword_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_CreatePassword_BackButton");}}
		public Element Connect_LikeButtonPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_LikeButtonPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_LikeButton_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_LikeButton_CancelButton");}}
		public Element Connect_DetailsPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_DetailsPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public SelectElement Connect_Details_MusicDropDown {get {return (SelectElement) Document.GetElementById(clientId + "_Connect_Details_MusicDropDown");}}
		public SelectElement Connect_Details_CountryDropDown {get {return (SelectElement) Document.GetElementById(clientId + "_Connect_Details_CountryDropDown");}}
		public SelectElement Connect_Details_PlaceDropDown {get {return (SelectElement) Document.GetElementById(clientId + "_Connect_Details_PlaceDropDown");}}
		public Element Connect_Details_PlaceDefaultOuterSpan {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_PlaceDefaultOuterSpan");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_Details_PlaceDefaultSpan {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_PlaceDefaultSpan");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement Connect_Details_PlaceChangeLink {get {return (AnchorElement) Document.GetElementById(clientId + "_Connect_Details_PlaceChangeLink");}}
		public Element Connect_Details_FacebookInfoPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_FacebookInfoPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_Details_WeeklyEmailInfoPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_WeeklyEmailInfoPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_Details_PartyInvitesInfoPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_PartyInvitesInfoPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public CheckBoxElement Connect_Details_FacebookCheck {get {return (CheckBoxElement) Document.GetElementById(clientId + "_Connect_Details_FacebookCheck");}}
		public Element Connect_Details_FacebookCheckLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_FacebookCheckLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement Connect_Details_FacebookInfoAnchor {get {return (AnchorElement) Document.GetElementById(clientId + "_Connect_Details_FacebookInfoAnchor");}}
		public CheckBoxElement Connect_Details_WeeklyEmailCheck {get {return (CheckBoxElement) Document.GetElementById(clientId + "_Connect_Details_WeeklyEmailCheck");}}
		public Element Connect_Details_WeeklyEmailCheckLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_WeeklyEmailCheckLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement Connect_Details_WeeklyEmailInfoAnchor {get {return (AnchorElement) Document.GetElementById(clientId + "_Connect_Details_WeeklyEmailInfoAnchor");}}
		public CheckBoxElement Connect_Details_PartyInvitesCheck {get {return (CheckBoxElement) Document.GetElementById(clientId + "_Connect_Details_PartyInvitesCheck");}}
		public Element Connect_Details_PartyInvitesCheckLabel {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_PartyInvitesCheckLabel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement Connect_Details_PartyInvitesInfoAnchor {get {return (AnchorElement) Document.GetElementById(clientId + "_Connect_Details_PartyInvitesInfoAnchor");}}
		public InputElement Connect_Details_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Details_CancelButton");}}
		public InputElement Connect_Details_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Details_BackButton");}}
		public InputElement Connect_Details_SaveButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Details_SaveButton");}}
		public Element Connect_Details_PlaceErrorSpan {get {return (Element) Document.GetElementById(clientId + "_Connect_Details_PlaceErrorSpan");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_CaptchaPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_CaptchaPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public ImageElement Connect_Captcha_Img {get {return (ImageElement) Document.GetElementById(clientId + "_Connect_Captcha_Img");}}
		public InputElement Connect_Captcha_Textbox {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Captcha_Textbox");}}
		public InputElement Connect_Captcha_SaveButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Captcha_SaveButton");}}
		public Element Connect_Captcha_Error {get {return (Element) Document.GetElementById(clientId + "_Connect_Captcha_Error");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement Connect_Captcha_BackButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Captcha_BackButton");}}
		public InputElement Connect_Captcha_CancelButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Captcha_CancelButton");}}
		public Element Connect_DebugPanel {get {return (Element) Document.GetElementById(clientId + "_Connect_DebugPanel");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element Connect_Debug_Output {get {return (Element) Document.GetElementById(clientId + "_Connect_Debug_Output");}}//mappings.Add("System.Web.UI.HtmlControls.HtmlTextArea", ElementGetter("Element"));
		public InputElement Connect_Debug_LogoutButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Debug_LogoutButton");}}
		public InputElement Connect_Debug_DisconnectButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Debug_DisconnectButton");}}
		public InputElement Connect_Debug_AuthButton {get {return (InputElement) Document.GetElementById(clientId + "_Connect_Debug_AuthButton");}}
	}
}
