//mappings.Add("Spotted.CustomControls.PromoterIntro", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
//mappings.Add("System.Web.UI.HtmlControls.HtmlTableCell", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.DataGrid", ElementGetter("Element"));
//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using jQueryApi;
using Js.Library;

namespace Js.Pages.Promoters.EventOptions
{
	public partial class View
		 : Js.Pages.Promoters.PromoterUserControl.View
	{
		public string clientId;
		public View(string clientId)
			 : base(clientId)
		{
			this.clientId = clientId;
		}
		public DivElement PanelEvent {get {if (_PanelEvent == null) {_PanelEvent = (DivElement)Document.GetElementById(clientId + "_PanelEvent");}; return _PanelEvent;}} private DivElement _PanelEvent;
		public jQueryObject PanelEventJ {get {if (_PanelEventJ == null) {_PanelEventJ = jQuery.Select("#" + clientId + "_PanelEvent");}; return _PanelEventJ;}} private jQueryObject _PanelEventJ;
		public Element PromoterIntro {get {if (_PromoterIntro == null) {_PromoterIntro = (Element)Document.GetElementById(clientId + "_PromoterIntro");}; return _PromoterIntro;}} private Element _PromoterIntro;
		public jQueryObject PromoterIntroJ {get {if (_PromoterIntroJ == null) {_PromoterIntroJ = jQuery.Select("#" + clientId + "_PromoterIntro");}; return _PromoterIntroJ;}} private jQueryObject _PromoterIntroJ;//mappings.Add("Spotted.CustomControls.PromoterIntro", ElementGetter("Element"));
		public Element EventLinksP {get {if (_EventLinksP == null) {_EventLinksP = (Element)Document.GetElementById(clientId + "_EventLinksP");}; return _EventLinksP;}} private Element _EventLinksP;
		public jQueryObject EventLinksPJ {get {if (_EventLinksPJ == null) {_EventLinksPJ = jQuery.Select("#" + clientId + "_EventLinksP");}; return _EventLinksPJ;}} private jQueryObject _EventLinksPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element EventDetailsPicCell {get {if (_EventDetailsPicCell == null) {_EventDetailsPicCell = (Element)Document.GetElementById(clientId + "_EventDetailsPicCell");}; return _EventDetailsPicCell;}} private Element _EventDetailsPicCell;
		public jQueryObject EventDetailsPicCellJ {get {if (_EventDetailsPicCellJ == null) {_EventDetailsPicCellJ = jQuery.Select("#" + clientId + "_EventDetailsPicCell");}; return _EventDetailsPicCellJ;}} private jQueryObject _EventDetailsPicCellJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlTableCell", ElementGetter("Element"));
		public DivElement BannersPanel {get {if (_BannersPanel == null) {_BannersPanel = (DivElement)Document.GetElementById(clientId + "_BannersPanel");}; return _BannersPanel;}} private DivElement _BannersPanel;
		public jQueryObject BannersPanelJ {get {if (_BannersPanelJ == null) {_BannersPanelJ = jQuery.Select("#" + clientId + "_BannersPanel");}; return _BannersPanelJ;}} private jQueryObject _BannersPanelJ;
		public DivElement NoBannersPanel {get {if (_NoBannersPanel == null) {_NoBannersPanel = (DivElement)Document.GetElementById(clientId + "_NoBannersPanel");}; return _NoBannersPanel;}} private DivElement _NoBannersPanel;
		public jQueryObject NoBannersPanelJ {get {if (_NoBannersPanelJ == null) {_NoBannersPanelJ = jQuery.Select("#" + clientId + "_NoBannersPanel");}; return _NoBannersPanelJ;}} private jQueryObject _NoBannersPanelJ;
		public AnchorElement BannerAddLink {get {if (_BannerAddLink == null) {_BannerAddLink = (AnchorElement)Document.GetElementById(clientId + "_BannerAddLink");}; return _BannerAddLink;}} private AnchorElement _BannerAddLink;
		public jQueryObject BannerAddLinkJ {get {if (_BannerAddLinkJ == null) {_BannerAddLinkJ = jQuery.Select("#" + clientId + "_BannerAddLink");}; return _BannerAddLinkJ;}} private jQueryObject _BannerAddLinkJ;
		public AnchorElement BannerAddLink1 {get {if (_BannerAddLink1 == null) {_BannerAddLink1 = (AnchorElement)Document.GetElementById(clientId + "_BannerAddLink1");}; return _BannerAddLink1;}} private AnchorElement _BannerAddLink1;
		public jQueryObject BannerAddLink1J {get {if (_BannerAddLink1J == null) {_BannerAddLink1J = jQuery.Select("#" + clientId + "_BannerAddLink1");}; return _BannerAddLink1J;}} private jQueryObject _BannerAddLink1J;
		public Element BannerDataGrid {get {if (_BannerDataGrid == null) {_BannerDataGrid = (Element)Document.GetElementById(clientId + "_BannerDataGrid");}; return _BannerDataGrid;}} private Element _BannerDataGrid;
		public jQueryObject BannerDataGridJ {get {if (_BannerDataGridJ == null) {_BannerDataGridJ = jQuery.Select("#" + clientId + "_BannerDataGrid");}; return _BannerDataGridJ;}} private jQueryObject _BannerDataGridJ;//mappings.Add("System.Web.UI.WebControls.DataGrid", ElementGetter("Element"));
		public DivElement NewsPanel {get {if (_NewsPanel == null) {_NewsPanel = (DivElement)Document.GetElementById(clientId + "_NewsPanel");}; return _NewsPanel;}} private DivElement _NewsPanel;
		public jQueryObject NewsPanelJ {get {if (_NewsPanelJ == null) {_NewsPanelJ = jQuery.Select("#" + clientId + "_NewsPanel");}; return _NewsPanelJ;}} private jQueryObject _NewsPanelJ;
		public DivElement NoNewsPanel {get {if (_NoNewsPanel == null) {_NoNewsPanel = (DivElement)Document.GetElementById(clientId + "_NoNewsPanel");}; return _NoNewsPanel;}} private DivElement _NoNewsPanel;
		public jQueryObject NoNewsPanelJ {get {if (_NoNewsPanelJ == null) {_NoNewsPanelJ = jQuery.Select("#" + clientId + "_NoNewsPanel");}; return _NoNewsPanelJ;}} private jQueryObject _NoNewsPanelJ;
		public Element NewsDataGrid {get {if (_NewsDataGrid == null) {_NewsDataGrid = (Element)Document.GetElementById(clientId + "_NewsDataGrid");}; return _NewsDataGrid;}} private Element _NewsDataGrid;
		public jQueryObject NewsDataGridJ {get {if (_NewsDataGridJ == null) {_NewsDataGridJ = jQuery.Select("#" + clientId + "_NewsDataGrid");}; return _NewsDataGridJ;}} private jQueryObject _NewsDataGridJ;//mappings.Add("System.Web.UI.WebControls.DataGrid", ElementGetter("Element"));
		public Js.Controls.AddThread.Controller NewsAddThread {get {return (Js.Controls.AddThread.Controller) Script.Eval(clientId + "_NewsAddThreadController");}}
		public Element NewsAddThreadLinkP {get {if (_NewsAddThreadLinkP == null) {_NewsAddThreadLinkP = (Element)Document.GetElementById(clientId + "_NewsAddThreadLinkP");}; return _NewsAddThreadLinkP;}} private Element _NewsAddThreadLinkP;
		public jQueryObject NewsAddThreadLinkPJ {get {if (_NewsAddThreadLinkPJ == null) {_NewsAddThreadLinkPJ = jQuery.Select("#" + clientId + "_NewsAddThreadLinkP");}; return _NewsAddThreadLinkPJ;}} private jQueryObject _NewsAddThreadLinkPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement NewsAddThreadStatusHidden {get {if (_NewsAddThreadStatusHidden == null) {_NewsAddThreadStatusHidden = (InputElement)Document.GetElementById(clientId + "_NewsAddThreadStatusHidden");}; return _NewsAddThreadStatusHidden;}} private InputElement _NewsAddThreadStatusHidden;
		public jQueryObject NewsAddThreadStatusHiddenJ {get {if (_NewsAddThreadStatusHiddenJ == null) {_NewsAddThreadStatusHiddenJ = jQuery.Select("#" + clientId + "_NewsAddThreadStatusHidden");}; return _NewsAddThreadStatusHiddenJ;}} private jQueryObject _NewsAddThreadStatusHiddenJ;
		public DivElement NewsAddThreadPanel {get {if (_NewsAddThreadPanel == null) {_NewsAddThreadPanel = (DivElement)Document.GetElementById(clientId + "_NewsAddThreadPanel");}; return _NewsAddThreadPanel;}} private DivElement _NewsAddThreadPanel;
		public jQueryObject NewsAddThreadPanelJ {get {if (_NewsAddThreadPanelJ == null) {_NewsAddThreadPanelJ = jQuery.Select("#" + clientId + "_NewsAddThreadPanel");}; return _NewsAddThreadPanelJ;}} private jQueryObject _NewsAddThreadPanelJ;
		public DivElement NewsPostPanel {get {if (_NewsPostPanel == null) {_NewsPostPanel = (DivElement)Document.GetElementById(clientId + "_NewsPostPanel");}; return _NewsPostPanel;}} private DivElement _NewsPostPanel;
		public jQueryObject NewsPostPanelJ {get {if (_NewsPostPanelJ == null) {_NewsPostPanelJ = jQuery.Select("#" + clientId + "_NewsPostPanel");}; return _NewsPostPanelJ;}} private jQueryObject _NewsPostPanelJ;
		public DivElement NoNewsPostPanel {get {if (_NoNewsPostPanel == null) {_NoNewsPostPanel = (DivElement)Document.GetElementById(clientId + "_NoNewsPostPanel");}; return _NoNewsPostPanel;}} private DivElement _NoNewsPostPanel;
		public jQueryObject NoNewsPostPanelJ {get {if (_NoNewsPostPanelJ == null) {_NoNewsPostPanelJ = jQuery.Select("#" + clientId + "_NoNewsPostPanel");}; return _NoNewsPostPanelJ;}} private jQueryObject _NoNewsPostPanelJ;
		public DivElement ArticlePanel {get {if (_ArticlePanel == null) {_ArticlePanel = (DivElement)Document.GetElementById(clientId + "_ArticlePanel");}; return _ArticlePanel;}} private DivElement _ArticlePanel;
		public jQueryObject ArticlePanelJ {get {if (_ArticlePanelJ == null) {_ArticlePanelJ = jQuery.Select("#" + clientId + "_ArticlePanel");}; return _ArticlePanelJ;}} private jQueryObject _ArticlePanelJ;
		public DivElement NoArticlePanel {get {if (_NoArticlePanel == null) {_NoArticlePanel = (DivElement)Document.GetElementById(clientId + "_NoArticlePanel");}; return _NoArticlePanel;}} private DivElement _NoArticlePanel;
		public jQueryObject NoArticlePanelJ {get {if (_NoArticlePanelJ == null) {_NoArticlePanelJ = jQuery.Select("#" + clientId + "_NoArticlePanel");}; return _NoArticlePanelJ;}} private jQueryObject _NoArticlePanelJ;
		public AnchorElement ArticleAddLink {get {if (_ArticleAddLink == null) {_ArticleAddLink = (AnchorElement)Document.GetElementById(clientId + "_ArticleAddLink");}; return _ArticleAddLink;}} private AnchorElement _ArticleAddLink;
		public jQueryObject ArticleAddLinkJ {get {if (_ArticleAddLinkJ == null) {_ArticleAddLinkJ = jQuery.Select("#" + clientId + "_ArticleAddLink");}; return _ArticleAddLinkJ;}} private jQueryObject _ArticleAddLinkJ;
		public AnchorElement ArticleAddLink1 {get {if (_ArticleAddLink1 == null) {_ArticleAddLink1 = (AnchorElement)Document.GetElementById(clientId + "_ArticleAddLink1");}; return _ArticleAddLink1;}} private AnchorElement _ArticleAddLink1;
		public jQueryObject ArticleAddLink1J {get {if (_ArticleAddLink1J == null) {_ArticleAddLink1J = jQuery.Select("#" + clientId + "_ArticleAddLink1");}; return _ArticleAddLink1J;}} private jQueryObject _ArticleAddLink1J;
		public Element ArticleDataGrid {get {if (_ArticleDataGrid == null) {_ArticleDataGrid = (Element)Document.GetElementById(clientId + "_ArticleDataGrid");}; return _ArticleDataGrid;}} private Element _ArticleDataGrid;
		public jQueryObject ArticleDataGridJ {get {if (_ArticleDataGridJ == null) {_ArticleDataGridJ = jQuery.Select("#" + clientId + "_ArticleDataGrid");}; return _ArticleDataGridJ;}} private jQueryObject _ArticleDataGridJ;//mappings.Add("System.Web.UI.WebControls.DataGrid", ElementGetter("Element"));
		public DivElement CompPanel {get {if (_CompPanel == null) {_CompPanel = (DivElement)Document.GetElementById(clientId + "_CompPanel");}; return _CompPanel;}} private DivElement _CompPanel;
		public jQueryObject CompPanelJ {get {if (_CompPanelJ == null) {_CompPanelJ = jQuery.Select("#" + clientId + "_CompPanel");}; return _CompPanelJ;}} private jQueryObject _CompPanelJ;
		public DivElement NoCompPanel {get {if (_NoCompPanel == null) {_NoCompPanel = (DivElement)Document.GetElementById(clientId + "_NoCompPanel");}; return _NoCompPanel;}} private DivElement _NoCompPanel;
		public jQueryObject NoCompPanelJ {get {if (_NoCompPanelJ == null) {_NoCompPanelJ = jQuery.Select("#" + clientId + "_NoCompPanel");}; return _NoCompPanelJ;}} private jQueryObject _NoCompPanelJ;
		public AnchorElement CompAddLink {get {if (_CompAddLink == null) {_CompAddLink = (AnchorElement)Document.GetElementById(clientId + "_CompAddLink");}; return _CompAddLink;}} private AnchorElement _CompAddLink;
		public jQueryObject CompAddLinkJ {get {if (_CompAddLinkJ == null) {_CompAddLinkJ = jQuery.Select("#" + clientId + "_CompAddLink");}; return _CompAddLinkJ;}} private jQueryObject _CompAddLinkJ;
		public AnchorElement CompAddLink1 {get {if (_CompAddLink1 == null) {_CompAddLink1 = (AnchorElement)Document.GetElementById(clientId + "_CompAddLink1");}; return _CompAddLink1;}} private AnchorElement _CompAddLink1;
		public jQueryObject CompAddLink1J {get {if (_CompAddLink1J == null) {_CompAddLink1J = jQuery.Select("#" + clientId + "_CompAddLink1");}; return _CompAddLink1J;}} private jQueryObject _CompAddLink1J;
		public Element CompDataGrid {get {if (_CompDataGrid == null) {_CompDataGrid = (Element)Document.GetElementById(clientId + "_CompDataGrid");}; return _CompDataGrid;}} private Element _CompDataGrid;
		public jQueryObject CompDataGridJ {get {if (_CompDataGridJ == null) {_CompDataGridJ = jQuery.Select("#" + clientId + "_CompDataGrid");}; return _CompDataGridJ;}} private jQueryObject _CompDataGridJ;//mappings.Add("System.Web.UI.WebControls.DataGrid", ElementGetter("Element"));
		public DivElement GuestlistPanel {get {if (_GuestlistPanel == null) {_GuestlistPanel = (DivElement)Document.GetElementById(clientId + "_GuestlistPanel");}; return _GuestlistPanel;}} private DivElement _GuestlistPanel;
		public jQueryObject GuestlistPanelJ {get {if (_GuestlistPanelJ == null) {_GuestlistPanelJ = jQuery.Select("#" + clientId + "_GuestlistPanel");}; return _GuestlistPanelJ;}} private jQueryObject _GuestlistPanelJ;
		public DivElement NoGuestlistPanel {get {if (_NoGuestlistPanel == null) {_NoGuestlistPanel = (DivElement)Document.GetElementById(clientId + "_NoGuestlistPanel");}; return _NoGuestlistPanel;}} private DivElement _NoGuestlistPanel;
		public jQueryObject NoGuestlistPanelJ {get {if (_NoGuestlistPanelJ == null) {_NoGuestlistPanelJ = jQuery.Select("#" + clientId + "_NoGuestlistPanel");}; return _NoGuestlistPanelJ;}} private jQueryObject _NoGuestlistPanelJ;
		public AnchorElement GuestlistAddLink {get {if (_GuestlistAddLink == null) {_GuestlistAddLink = (AnchorElement)Document.GetElementById(clientId + "_GuestlistAddLink");}; return _GuestlistAddLink;}} private AnchorElement _GuestlistAddLink;
		public jQueryObject GuestlistAddLinkJ {get {if (_GuestlistAddLinkJ == null) {_GuestlistAddLinkJ = jQuery.Select("#" + clientId + "_GuestlistAddLink");}; return _GuestlistAddLinkJ;}} private jQueryObject _GuestlistAddLinkJ;
		public Element GuestlistDataGrid {get {if (_GuestlistDataGrid == null) {_GuestlistDataGrid = (Element)Document.GetElementById(clientId + "_GuestlistDataGrid");}; return _GuestlistDataGrid;}} private Element _GuestlistDataGrid;
		public jQueryObject GuestlistDataGridJ {get {if (_GuestlistDataGridJ == null) {_GuestlistDataGridJ = jQuery.Select("#" + clientId + "_GuestlistDataGrid");}; return _GuestlistDataGridJ;}} private jQueryObject _GuestlistDataGridJ;//mappings.Add("System.Web.UI.WebControls.DataGrid", ElementGetter("Element"));
		public Element Header {get {if (_Header == null) {_Header = (Element)Document.GetElementById(clientId + "_Header");}; return _Header;}} private Element _Header;
		public jQueryObject HeaderJ {get {if (_HeaderJ == null) {_HeaderJ = jQuery.Select("#" + clientId + "_Header");}; return _HeaderJ;}} private jQueryObject _HeaderJ;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public DivElement SpotterRequestYesPanel {get {if (_SpotterRequestYesPanel == null) {_SpotterRequestYesPanel = (DivElement)Document.GetElementById(clientId + "_SpotterRequestYesPanel");}; return _SpotterRequestYesPanel;}} private DivElement _SpotterRequestYesPanel;
		public jQueryObject SpotterRequestYesPanelJ {get {if (_SpotterRequestYesPanelJ == null) {_SpotterRequestYesPanelJ = jQuery.Select("#" + clientId + "_SpotterRequestYesPanel");}; return _SpotterRequestYesPanelJ;}} private jQueryObject _SpotterRequestYesPanelJ;
		public Element H1 {get {if (_H1 == null) {_H1 = (Element)Document.GetElementById(clientId + "_H1");}; return _H1;}} private Element _H1;
		public jQueryObject H1J {get {if (_H1J == null) {_H1J = jQuery.Select("#" + clientId + "_H1");}; return _H1J;}} private jQueryObject _H1J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element SpotterRequestDetails {get {if (_SpotterRequestDetails == null) {_SpotterRequestDetails = (Element)Document.GetElementById(clientId + "_SpotterRequestDetails");}; return _SpotterRequestDetails;}} private Element _SpotterRequestDetails;
		public jQueryObject SpotterRequestDetailsJ {get {if (_SpotterRequestDetailsJ == null) {_SpotterRequestDetailsJ = jQuery.Select("#" + clientId + "_SpotterRequestDetails");}; return _SpotterRequestDetailsJ;}} private jQueryObject _SpotterRequestDetailsJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public AnchorElement SpotterRequestYesLink {get {if (_SpotterRequestYesLink == null) {_SpotterRequestYesLink = (AnchorElement)Document.GetElementById(clientId + "_SpotterRequestYesLink");}; return _SpotterRequestYesLink;}} private AnchorElement _SpotterRequestYesLink;
		public jQueryObject SpotterRequestYesLinkJ {get {if (_SpotterRequestYesLinkJ == null) {_SpotterRequestYesLinkJ = jQuery.Select("#" + clientId + "_SpotterRequestYesLink");}; return _SpotterRequestYesLinkJ;}} private jQueryObject _SpotterRequestYesLinkJ;
		public DivElement SpotterRequestNoPanel {get {if (_SpotterRequestNoPanel == null) {_SpotterRequestNoPanel = (DivElement)Document.GetElementById(clientId + "_SpotterRequestNoPanel");}; return _SpotterRequestNoPanel;}} private DivElement _SpotterRequestNoPanel;
		public jQueryObject SpotterRequestNoPanelJ {get {if (_SpotterRequestNoPanelJ == null) {_SpotterRequestNoPanelJ = jQuery.Select("#" + clientId + "_SpotterRequestNoPanel");}; return _SpotterRequestNoPanelJ;}} private jQueryObject _SpotterRequestNoPanelJ;
		public Element H2 {get {if (_H2 == null) {_H2 = (Element)Document.GetElementById(clientId + "_H2");}; return _H2;}} private Element _H2;
		public jQueryObject H2J {get {if (_H2J == null) {_H2J = jQuery.Select("#" + clientId + "_H2");}; return _H2J;}} private jQueryObject _H2J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public AnchorElement SpotterRequestNoLink {get {if (_SpotterRequestNoLink == null) {_SpotterRequestNoLink = (AnchorElement)Document.GetElementById(clientId + "_SpotterRequestNoLink");}; return _SpotterRequestNoLink;}} private AnchorElement _SpotterRequestNoLink;
		public jQueryObject SpotterRequestNoLinkJ {get {if (_SpotterRequestNoLinkJ == null) {_SpotterRequestNoLinkJ = jQuery.Select("#" + clientId + "_SpotterRequestNoLink");}; return _SpotterRequestNoLinkJ;}} private jQueryObject _SpotterRequestNoLinkJ;
		public DivElement TicketRunPanel {get {if (_TicketRunPanel == null) {_TicketRunPanel = (DivElement)Document.GetElementById(clientId + "_TicketRunPanel");}; return _TicketRunPanel;}} private DivElement _TicketRunPanel;
		public jQueryObject TicketRunPanelJ {get {if (_TicketRunPanelJ == null) {_TicketRunPanelJ = jQuery.Select("#" + clientId + "_TicketRunPanel");}; return _TicketRunPanelJ;}} private jQueryObject _TicketRunPanelJ;
		public Element H10 {get {if (_H10 == null) {_H10 = (Element)Document.GetElementById(clientId + "_H10");}; return _H10;}} private Element _H10;
		public jQueryObject H10J {get {if (_H10J == null) {_H10J = jQuery.Select("#" + clientId + "_H10");}; return _H10J;}} private jQueryObject _H10J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element TicketRunsGridView {get {if (_TicketRunsGridView == null) {_TicketRunsGridView = (Element)Document.GetElementById(clientId + "_TicketRunsGridView");}; return _TicketRunsGridView;}} private Element _TicketRunsGridView;
		public jQueryObject TicketRunsGridViewJ {get {if (_TicketRunsGridViewJ == null) {_TicketRunsGridViewJ = jQuery.Select("#" + clientId + "_TicketRunsGridView");}; return _TicketRunsGridViewJ;}} private jQueryObject _TicketRunsGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public Element NoTicketRunsP {get {if (_NoTicketRunsP == null) {_NoTicketRunsP = (Element)Document.GetElementById(clientId + "_NoTicketRunsP");}; return _NoTicketRunsP;}} private Element _NoTicketRunsP;
		public jQueryObject NoTicketRunsPJ {get {if (_NoTicketRunsPJ == null) {_NoTicketRunsPJ = jQuery.Select("#" + clientId + "_NoTicketRunsP");}; return _NoTicketRunsPJ;}} private jQueryObject _NoTicketRunsPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element SellTicketsP {get {if (_SellTicketsP == null) {_SellTicketsP = (Element)Document.GetElementById(clientId + "_SellTicketsP");}; return _SellTicketsP;}} private Element _SellTicketsP;
		public jQueryObject SellTicketsPJ {get {if (_SellTicketsPJ == null) {_SellTicketsPJ = jQuery.Select("#" + clientId + "_SellTicketsP");}; return _SellTicketsPJ;}} private jQueryObject _SellTicketsPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement SellTicketsLink {get {if (_SellTicketsLink == null) {_SellTicketsLink = (AnchorElement)Document.GetElementById(clientId + "_SellTicketsLink");}; return _SellTicketsLink;}} private AnchorElement _SellTicketsLink;
		public jQueryObject SellTicketsLinkJ {get {if (_SellTicketsLinkJ == null) {_SellTicketsLinkJ = jQuery.Select("#" + clientId + "_SellTicketsLink");}; return _SellTicketsLinkJ;}} private jQueryObject _SellTicketsLinkJ;
		public Element NoSellTicketsP {get {if (_NoSellTicketsP == null) {_NoSellTicketsP = (Element)Document.GetElementById(clientId + "_NoSellTicketsP");}; return _NoSellTicketsP;}} private Element _NoSellTicketsP;
		public jQueryObject NoSellTicketsPJ {get {if (_NoSellTicketsPJ == null) {_NoSellTicketsPJ = jQuery.Select("#" + clientId + "_NoSellTicketsP");}; return _NoSellTicketsPJ;}} private jQueryObject _NoSellTicketsPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element DoorlistP {get {if (_DoorlistP == null) {_DoorlistP = (Element)Document.GetElementById(clientId + "_DoorlistP");}; return _DoorlistP;}} private Element _DoorlistP;
		public jQueryObject DoorlistPJ {get {if (_DoorlistPJ == null) {_DoorlistPJ = jQuery.Select("#" + clientId + "_DoorlistP");}; return _DoorlistPJ;}} private jQueryObject _DoorlistPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement DoorlistLink {get {if (_DoorlistLink == null) {_DoorlistLink = (AnchorElement)Document.GetElementById(clientId + "_DoorlistLink");}; return _DoorlistLink;}} private AnchorElement _DoorlistLink;
		public jQueryObject DoorlistLinkJ {get {if (_DoorlistLinkJ == null) {_DoorlistLinkJ = jQuery.Select("#" + clientId + "_DoorlistLink");}; return _DoorlistLinkJ;}} private jQueryObject _DoorlistLinkJ;
		public DivElement AdminLinksPanel {get {if (_AdminLinksPanel == null) {_AdminLinksPanel = (DivElement)Document.GetElementById(clientId + "_AdminLinksPanel");}; return _AdminLinksPanel;}} private DivElement _AdminLinksPanel;
		public jQueryObject AdminLinksPanelJ {get {if (_AdminLinksPanelJ == null) {_AdminLinksPanelJ = jQuery.Select("#" + clientId + "_AdminLinksPanel");}; return _AdminLinksPanelJ;}} private jQueryObject _AdminLinksPanelJ;
		public Element H11 {get {if (_H11 == null) {_H11 = (Element)Document.GetElementById(clientId + "_H11");}; return _H11;}} private Element _H11;
		public jQueryObject H11J {get {if (_H11J == null) {_H11J = jQuery.Select("#" + clientId + "_H11");}; return _H11J;}} private jQueryObject _H11J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element H17 {get {if (_H17 == null) {_H17 = (Element)Document.GetElementById(clientId + "_H17");}; return _H17;}} private Element _H17;
		public jQueryObject H17J {get {if (_H17J == null) {_H17J = jQuery.Select("#" + clientId + "_H17");}; return _H17J;}} private jQueryObject _H17J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public DivElement EventHighlightPanel {get {if (_EventHighlightPanel == null) {_EventHighlightPanel = (DivElement)Document.GetElementById(clientId + "_EventHighlightPanel");}; return _EventHighlightPanel;}} private DivElement _EventHighlightPanel;
		public jQueryObject EventHighlightPanelJ {get {if (_EventHighlightPanelJ == null) {_EventHighlightPanelJ = jQuery.Select("#" + clientId + "_EventHighlightPanel");}; return _EventHighlightPanelJ;}} private jQueryObject _EventHighlightPanelJ;
		public Element H12a {get {if (_H12a == null) {_H12a = (Element)Document.GetElementById(clientId + "_H12a");}; return _H12a;}} private Element _H12a;
		public jQueryObject H12aJ {get {if (_H12aJ == null) {_H12aJ = jQuery.Select("#" + clientId + "_H12a");}; return _H12aJ;}} private jQueryObject _H12aJ;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public DivElement NoEventHighlightPanel {get {if (_NoEventHighlightPanel == null) {_NoEventHighlightPanel = (DivElement)Document.GetElementById(clientId + "_NoEventHighlightPanel");}; return _NoEventHighlightPanel;}} private DivElement _NoEventHighlightPanel;
		public jQueryObject NoEventHighlightPanelJ {get {if (_NoEventHighlightPanelJ == null) {_NoEventHighlightPanelJ = jQuery.Select("#" + clientId + "_NoEventHighlightPanel");}; return _NoEventHighlightPanelJ;}} private jQueryObject _NoEventHighlightPanelJ;
		public Element H12b {get {if (_H12b == null) {_H12b = (Element)Document.GetElementById(clientId + "_H12b");}; return _H12b;}} private Element _H12b;
		public jQueryObject H12bJ {get {if (_H12bJ == null) {_H12bJ = jQuery.Select("#" + clientId + "_H12b");}; return _H12bJ;}} private jQueryObject _H12bJ;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public AnchorElement EventHighlightLink {get {if (_EventHighlightLink == null) {_EventHighlightLink = (AnchorElement)Document.GetElementById(clientId + "_EventHighlightLink");}; return _EventHighlightLink;}} private AnchorElement _EventHighlightLink;
		public jQueryObject EventHighlightLinkJ {get {if (_EventHighlightLinkJ == null) {_EventHighlightLinkJ = jQuery.Select("#" + clientId + "_EventHighlightLink");}; return _EventHighlightLinkJ;}} private jQueryObject _EventHighlightLinkJ;
		public Element H12 {get {if (_H12 == null) {_H12 = (Element)Document.GetElementById(clientId + "_H12");}; return _H12;}} private Element _H12;
		public jQueryObject H12J {get {if (_H12J == null) {_H12J = jQuery.Select("#" + clientId + "_H12");}; return _H12J;}} private jQueryObject _H12J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element H110 {get {if (_H110 == null) {_H110 = (Element)Document.GetElementById(clientId + "_H110");}; return _H110;}} private Element _H110;
		public jQueryObject H110J {get {if (_H110J == null) {_H110J = jQuery.Select("#" + clientId + "_H110");}; return _H110J;}} private jQueryObject _H110J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element H111 {get {if (_H111 == null) {_H111 = (Element)Document.GetElementById(clientId + "_H111");}; return _H111;}} private Element _H111;
		public jQueryObject H111J {get {if (_H111J == null) {_H111J = jQuery.Select("#" + clientId + "_H111");}; return _H111J;}} private jQueryObject _H111J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element H13 {get {if (_H13 == null) {_H13 = (Element)Document.GetElementById(clientId + "_H13");}; return _H13;}} private Element _H13;
		public jQueryObject H13J {get {if (_H13J == null) {_H13J = jQuery.Select("#" + clientId + "_H13");}; return _H13J;}} private jQueryObject _H13J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element H19 {get {if (_H19 == null) {_H19 = (Element)Document.GetElementById(clientId + "_H19");}; return _H19;}} private Element _H19;
		public jQueryObject H19J {get {if (_H19J == null) {_H19J = jQuery.Select("#" + clientId + "_H19");}; return _H19J;}} private jQueryObject _H19J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element H14 {get {if (_H14 == null) {_H14 = (Element)Document.GetElementById(clientId + "_H14");}; return _H14;}} private Element _H14;
		public jQueryObject H14J {get {if (_H14J == null) {_H14J = jQuery.Select("#" + clientId + "_H14");}; return _H14J;}} private jQueryObject _H14J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element H112 {get {if (_H112 == null) {_H112 = (Element)Document.GetElementById(clientId + "_H112");}; return _H112;}} private Element _H112;
		public jQueryObject H112J {get {if (_H112J == null) {_H112J = jQuery.Select("#" + clientId + "_H112");}; return _H112J;}} private jQueryObject _H112J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public DivElement SpotterInvitePanel {get {if (_SpotterInvitePanel == null) {_SpotterInvitePanel = (DivElement)Document.GetElementById(clientId + "_SpotterInvitePanel");}; return _SpotterInvitePanel;}} private DivElement _SpotterInvitePanel;
		public jQueryObject SpotterInvitePanelJ {get {if (_SpotterInvitePanelJ == null) {_SpotterInvitePanelJ = jQuery.Select("#" + clientId + "_SpotterInvitePanel");}; return _SpotterInvitePanelJ;}} private jQueryObject _SpotterInvitePanelJ;
		public Element H16 {get {if (_H16 == null) {_H16 = (Element)Document.GetElementById(clientId + "_H16");}; return _H16;}} private Element _H16;
		public jQueryObject H16J {get {if (_H16J == null) {_H16J = jQuery.Select("#" + clientId + "_H16");}; return _H16J;}} private jQueryObject _H16J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element GenericContainerPage {get {if (_GenericContainerPage == null) {_GenericContainerPage = (Element)Document.GetElementById(clientId + "_GenericContainerPage");}; return _GenericContainerPage;}} private Element _GenericContainerPage;
		public jQueryObject GenericContainerPageJ {get {if (_GenericContainerPageJ == null) {_GenericContainerPageJ = jQuery.Select("#" + clientId + "_GenericContainerPage");}; return _GenericContainerPageJ;}} private jQueryObject _GenericContainerPageJ;//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
	}
}
