DECLARE @found int SET @found = 1 WHILE @found > 0 BEGIN UPDATE [XXX] SET [YYY] = ZZZ WHERE [XXX].[K] IN (SELECT TOP 1000 K FROM [XXX] WHERE NOT [YYY] = ZZZ ORDER BY [XXX].[K]) SET @found = @@ROWCOUNT END

or:

DECLARE @found int SET @found = 1 WHILE @found > 0 
BEGIN TRY 
UPDATE [XXX] SET [YYY] = ZZZ WHERE [XXX].[K] IN (SELECT TOP 1000 K FROM [XXX] WHERE NOT [YYY] = ZZZ ORDER BY [XXX].[K]) 
SET @found = @@ROWCOUNT 
END TRY
BEGIN CATCH
END CATCH

