//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotted.Blank {
    
    public partial class MailingUpload {
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Label OldPass;
        protected System.Web.UI.WebControls.TextBox Pass;
        protected System.Web.UI.WebControls.Button Button2;
    }
}
