//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotted.Blank {
    
    
    public partial class OverdueAccounts {
        
        /// <summary>
        /// LoggedInAs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LoggedInAs;
        
        /// <summary>
        /// PromoterAccountsWarningControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Spotted.Controls.Promoters.AccountsWarning PromoterAccountsWarningControl;
    }
}
