//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using jQueryApi;
using Js.Library;

namespace Js.Pages.Spam
{
	public partial class View
		 : Js.DsiUserControl.View
	{
		public string clientId;
		public View(string clientId)
			 : base(clientId)
		{
			this.clientId = clientId;
		}
		public DivElement InboxSpamPanel {get {if (_InboxSpamPanel == null) {_InboxSpamPanel = (DivElement)Document.GetElementById(clientId + "_InboxSpamPanel");}; return _InboxSpamPanel;}} private DivElement _InboxSpamPanel;
		public jQueryObject InboxSpamPanelJ {get {if (_InboxSpamPanelJ == null) {_InboxSpamPanelJ = jQuery.Select("#" + clientId + "_InboxSpamPanel");}; return _InboxSpamPanelJ;}} private jQueryObject _InboxSpamPanelJ;
		public DivElement InvitePanel {get {if (_InvitePanel == null) {_InvitePanel = (DivElement)Document.GetElementById(clientId + "_InvitePanel");}; return _InvitePanel;}} private DivElement _InvitePanel;
		public jQueryObject InvitePanelJ {get {if (_InvitePanelJ == null) {_InvitePanelJ = jQuery.Select("#" + clientId + "_InvitePanel");}; return _InvitePanelJ;}} private jQueryObject _InvitePanelJ;
		public Element InviteGridView {get {if (_InviteGridView == null) {_InviteGridView = (Element)Document.GetElementById(clientId + "_InviteGridView");}; return _InviteGridView;}} private Element _InviteGridView;
		public jQueryObject InviteGridViewJ {get {if (_InviteGridViewJ == null) {_InviteGridViewJ = jQuery.Select("#" + clientId + "_InviteGridView");}; return _InviteGridViewJ;}} private jQueryObject _InviteGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public DivElement VenueWatchPanel {get {if (_VenueWatchPanel == null) {_VenueWatchPanel = (DivElement)Document.GetElementById(clientId + "_VenueWatchPanel");}; return _VenueWatchPanel;}} private DivElement _VenueWatchPanel;
		public jQueryObject VenueWatchPanelJ {get {if (_VenueWatchPanelJ == null) {_VenueWatchPanelJ = jQuery.Select("#" + clientId + "_VenueWatchPanel");}; return _VenueWatchPanelJ;}} private jQueryObject _VenueWatchPanelJ;
		public Element VenueWatchGridView {get {if (_VenueWatchGridView == null) {_VenueWatchGridView = (Element)Document.GetElementById(clientId + "_VenueWatchGridView");}; return _VenueWatchGridView;}} private Element _VenueWatchGridView;
		public jQueryObject VenueWatchGridViewJ {get {if (_VenueWatchGridViewJ == null) {_VenueWatchGridViewJ = jQuery.Select("#" + clientId + "_VenueWatchGridView");}; return _VenueWatchGridViewJ;}} private jQueryObject _VenueWatchGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public DivElement BrandWatchPanel {get {if (_BrandWatchPanel == null) {_BrandWatchPanel = (DivElement)Document.GetElementById(clientId + "_BrandWatchPanel");}; return _BrandWatchPanel;}} private DivElement _BrandWatchPanel;
		public jQueryObject BrandWatchPanelJ {get {if (_BrandWatchPanelJ == null) {_BrandWatchPanelJ = jQuery.Select("#" + clientId + "_BrandWatchPanel");}; return _BrandWatchPanelJ;}} private jQueryObject _BrandWatchPanelJ;
		public Element BrandWatchGridView {get {if (_BrandWatchGridView == null) {_BrandWatchGridView = (Element)Document.GetElementById(clientId + "_BrandWatchGridView");}; return _BrandWatchGridView;}} private Element _BrandWatchGridView;
		public jQueryObject BrandWatchGridViewJ {get {if (_BrandWatchGridViewJ == null) {_BrandWatchGridViewJ = jQuery.Select("#" + clientId + "_BrandWatchGridView");}; return _BrandWatchGridViewJ;}} private jQueryObject _BrandWatchGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public DivElement EventWatchPanel {get {if (_EventWatchPanel == null) {_EventWatchPanel = (DivElement)Document.GetElementById(clientId + "_EventWatchPanel");}; return _EventWatchPanel;}} private DivElement _EventWatchPanel;
		public jQueryObject EventWatchPanelJ {get {if (_EventWatchPanelJ == null) {_EventWatchPanelJ = jQuery.Select("#" + clientId + "_EventWatchPanel");}; return _EventWatchPanelJ;}} private jQueryObject _EventWatchPanelJ;
		public Element EventWatchGridView {get {if (_EventWatchGridView == null) {_EventWatchGridView = (Element)Document.GetElementById(clientId + "_EventWatchGridView");}; return _EventWatchGridView;}} private Element _EventWatchGridView;
		public jQueryObject EventWatchGridViewJ {get {if (_EventWatchGridViewJ == null) {_EventWatchGridViewJ = jQuery.Select("#" + clientId + "_EventWatchGridView");}; return _EventWatchGridViewJ;}} private jQueryObject _EventWatchGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public DivElement GroupWatchPanel {get {if (_GroupWatchPanel == null) {_GroupWatchPanel = (DivElement)Document.GetElementById(clientId + "_GroupWatchPanel");}; return _GroupWatchPanel;}} private DivElement _GroupWatchPanel;
		public jQueryObject GroupWatchPanelJ {get {if (_GroupWatchPanelJ == null) {_GroupWatchPanelJ = jQuery.Select("#" + clientId + "_GroupWatchPanel");}; return _GroupWatchPanelJ;}} private jQueryObject _GroupWatchPanelJ;
		public Element GroupWatchGridView {get {if (_GroupWatchGridView == null) {_GroupWatchGridView = (Element)Document.GetElementById(clientId + "_GroupWatchGridView");}; return _GroupWatchGridView;}} private Element _GroupWatchGridView;
		public jQueryObject GroupWatchGridViewJ {get {if (_GroupWatchGridViewJ == null) {_GroupWatchGridViewJ = jQuery.Select("#" + clientId + "_GroupWatchGridView");}; return _GroupWatchGridViewJ;}} private jQueryObject _GroupWatchGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public DivElement GroupNewsPanel {get {if (_GroupNewsPanel == null) {_GroupNewsPanel = (DivElement)Document.GetElementById(clientId + "_GroupNewsPanel");}; return _GroupNewsPanel;}} private DivElement _GroupNewsPanel;
		public jQueryObject GroupNewsPanelJ {get {if (_GroupNewsPanelJ == null) {_GroupNewsPanelJ = jQuery.Select("#" + clientId + "_GroupNewsPanel");}; return _GroupNewsPanelJ;}} private jQueryObject _GroupNewsPanelJ;
		public Element GroupNewsGridView {get {if (_GroupNewsGridView == null) {_GroupNewsGridView = (Element)Document.GetElementById(clientId + "_GroupNewsGridView");}; return _GroupNewsGridView;}} private Element _GroupNewsGridView;
		public jQueryObject GroupNewsGridViewJ {get {if (_GroupNewsGridViewJ == null) {_GroupNewsGridViewJ = jQuery.Select("#" + clientId + "_GroupNewsGridView");}; return _GroupNewsGridViewJ;}} private jQueryObject _GroupNewsGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public DivElement WatchPhotoPanel {get {if (_WatchPhotoPanel == null) {_WatchPhotoPanel = (DivElement)Document.GetElementById(clientId + "_WatchPhotoPanel");}; return _WatchPhotoPanel;}} private DivElement _WatchPhotoPanel;
		public jQueryObject WatchPhotoPanelJ {get {if (_WatchPhotoPanelJ == null) {_WatchPhotoPanelJ = jQuery.Select("#" + clientId + "_WatchPhotoPanel");}; return _WatchPhotoPanelJ;}} private jQueryObject _WatchPhotoPanelJ;
		public Element NumberOfTopicsFromWatchingPhotosLabel {get {if (_NumberOfTopicsFromWatchingPhotosLabel == null) {_NumberOfTopicsFromWatchingPhotosLabel = (Element)Document.GetElementById(clientId + "_NumberOfTopicsFromWatchingPhotosLabel");}; return _NumberOfTopicsFromWatchingPhotosLabel;}} private Element _NumberOfTopicsFromWatchingPhotosLabel;
		public jQueryObject NumberOfTopicsFromWatchingPhotosLabelJ {get {if (_NumberOfTopicsFromWatchingPhotosLabelJ == null) {_NumberOfTopicsFromWatchingPhotosLabelJ = jQuery.Select("#" + clientId + "_NumberOfTopicsFromWatchingPhotosLabel");}; return _NumberOfTopicsFromWatchingPhotosLabelJ;}} private jQueryObject _NumberOfTopicsFromWatchingPhotosLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public DivElement WatchPhotoTopicOptionsPanel {get {if (_WatchPhotoTopicOptionsPanel == null) {_WatchPhotoTopicOptionsPanel = (DivElement)Document.GetElementById(clientId + "_WatchPhotoTopicOptionsPanel");}; return _WatchPhotoTopicOptionsPanel;}} private DivElement _WatchPhotoTopicOptionsPanel;
		public jQueryObject WatchPhotoTopicOptionsPanelJ {get {if (_WatchPhotoTopicOptionsPanelJ == null) {_WatchPhotoTopicOptionsPanelJ = jQuery.Select("#" + clientId + "_WatchPhotoTopicOptionsPanel");}; return _WatchPhotoTopicOptionsPanelJ;}} private jQueryObject _WatchPhotoTopicOptionsPanelJ;
		public SelectElement PhotoTopicOptionsDropDownList {get {if (_PhotoTopicOptionsDropDownList == null) {_PhotoTopicOptionsDropDownList = (SelectElement)Document.GetElementById(clientId + "_PhotoTopicOptionsDropDownList");}; return _PhotoTopicOptionsDropDownList;}} private SelectElement _PhotoTopicOptionsDropDownList;
		public jQueryObject PhotoTopicOptionsDropDownListJ {get {if (_PhotoTopicOptionsDropDownListJ == null) {_PhotoTopicOptionsDropDownListJ = jQuery.Select("#" + clientId + "_PhotoTopicOptionsDropDownList");}; return _PhotoTopicOptionsDropDownListJ;}} private jQueryObject _PhotoTopicOptionsDropDownListJ;
		public InputElement PhotoOptionsUpdateButton {get {if (_PhotoOptionsUpdateButton == null) {_PhotoOptionsUpdateButton = (InputElement)Document.GetElementById(clientId + "_PhotoOptionsUpdateButton");}; return _PhotoOptionsUpdateButton;}} private InputElement _PhotoOptionsUpdateButton;
		public jQueryObject PhotoOptionsUpdateButtonJ {get {if (_PhotoOptionsUpdateButtonJ == null) {_PhotoOptionsUpdateButtonJ = jQuery.Select("#" + clientId + "_PhotoOptionsUpdateButton");}; return _PhotoOptionsUpdateButtonJ;}} private jQueryObject _PhotoOptionsUpdateButtonJ;
		public Element WatchPhotoTopicOptionsLabel {get {if (_WatchPhotoTopicOptionsLabel == null) {_WatchPhotoTopicOptionsLabel = (Element)Document.GetElementById(clientId + "_WatchPhotoTopicOptionsLabel");}; return _WatchPhotoTopicOptionsLabel;}} private Element _WatchPhotoTopicOptionsLabel;
		public jQueryObject WatchPhotoTopicOptionsLabelJ {get {if (_WatchPhotoTopicOptionsLabelJ == null) {_WatchPhotoTopicOptionsLabelJ = jQuery.Select("#" + clientId + "_WatchPhotoTopicOptionsLabel");}; return _WatchPhotoTopicOptionsLabelJ;}} private jQueryObject _WatchPhotoTopicOptionsLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public DivElement WatchArticlePanel {get {if (_WatchArticlePanel == null) {_WatchArticlePanel = (DivElement)Document.GetElementById(clientId + "_WatchArticlePanel");}; return _WatchArticlePanel;}} private DivElement _WatchArticlePanel;
		public jQueryObject WatchArticlePanelJ {get {if (_WatchArticlePanelJ == null) {_WatchArticlePanelJ = jQuery.Select("#" + clientId + "_WatchArticlePanel");}; return _WatchArticlePanelJ;}} private jQueryObject _WatchArticlePanelJ;
		public Element NumberOfTopicsFromWatchingArticlesLabel {get {if (_NumberOfTopicsFromWatchingArticlesLabel == null) {_NumberOfTopicsFromWatchingArticlesLabel = (Element)Document.GetElementById(clientId + "_NumberOfTopicsFromWatchingArticlesLabel");}; return _NumberOfTopicsFromWatchingArticlesLabel;}} private Element _NumberOfTopicsFromWatchingArticlesLabel;
		public jQueryObject NumberOfTopicsFromWatchingArticlesLabelJ {get {if (_NumberOfTopicsFromWatchingArticlesLabelJ == null) {_NumberOfTopicsFromWatchingArticlesLabelJ = jQuery.Select("#" + clientId + "_NumberOfTopicsFromWatchingArticlesLabel");}; return _NumberOfTopicsFromWatchingArticlesLabelJ;}} private jQueryObject _NumberOfTopicsFromWatchingArticlesLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public DivElement WatchArticleTopicOptionsPanel {get {if (_WatchArticleTopicOptionsPanel == null) {_WatchArticleTopicOptionsPanel = (DivElement)Document.GetElementById(clientId + "_WatchArticleTopicOptionsPanel");}; return _WatchArticleTopicOptionsPanel;}} private DivElement _WatchArticleTopicOptionsPanel;
		public jQueryObject WatchArticleTopicOptionsPanelJ {get {if (_WatchArticleTopicOptionsPanelJ == null) {_WatchArticleTopicOptionsPanelJ = jQuery.Select("#" + clientId + "_WatchArticleTopicOptionsPanel");}; return _WatchArticleTopicOptionsPanelJ;}} private jQueryObject _WatchArticleTopicOptionsPanelJ;
		public SelectElement ArticleTopicOptionsDropDownList {get {if (_ArticleTopicOptionsDropDownList == null) {_ArticleTopicOptionsDropDownList = (SelectElement)Document.GetElementById(clientId + "_ArticleTopicOptionsDropDownList");}; return _ArticleTopicOptionsDropDownList;}} private SelectElement _ArticleTopicOptionsDropDownList;
		public jQueryObject ArticleTopicOptionsDropDownListJ {get {if (_ArticleTopicOptionsDropDownListJ == null) {_ArticleTopicOptionsDropDownListJ = jQuery.Select("#" + clientId + "_ArticleTopicOptionsDropDownList");}; return _ArticleTopicOptionsDropDownListJ;}} private jQueryObject _ArticleTopicOptionsDropDownListJ;
		public InputElement ArticleOptionsUpdateButton {get {if (_ArticleOptionsUpdateButton == null) {_ArticleOptionsUpdateButton = (InputElement)Document.GetElementById(clientId + "_ArticleOptionsUpdateButton");}; return _ArticleOptionsUpdateButton;}} private InputElement _ArticleOptionsUpdateButton;
		public jQueryObject ArticleOptionsUpdateButtonJ {get {if (_ArticleOptionsUpdateButtonJ == null) {_ArticleOptionsUpdateButtonJ = jQuery.Select("#" + clientId + "_ArticleOptionsUpdateButton");}; return _ArticleOptionsUpdateButtonJ;}} private jQueryObject _ArticleOptionsUpdateButtonJ;
		public Element WatchArticleTopicOptionsLabel {get {if (_WatchArticleTopicOptionsLabel == null) {_WatchArticleTopicOptionsLabel = (Element)Document.GetElementById(clientId + "_WatchArticleTopicOptionsLabel");}; return _WatchArticleTopicOptionsLabel;}} private Element _WatchArticleTopicOptionsLabel;
		public jQueryObject WatchArticleTopicOptionsLabelJ {get {if (_WatchArticleTopicOptionsLabelJ == null) {_WatchArticleTopicOptionsLabelJ = jQuery.Select("#" + clientId + "_WatchArticleTopicOptionsLabel");}; return _WatchArticleTopicOptionsLabelJ;}} private jQueryObject _WatchArticleTopicOptionsLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public DivElement WatchOtherThreadPanel {get {if (_WatchOtherThreadPanel == null) {_WatchOtherThreadPanel = (DivElement)Document.GetElementById(clientId + "_WatchOtherThreadPanel");}; return _WatchOtherThreadPanel;}} private DivElement _WatchOtherThreadPanel;
		public jQueryObject WatchOtherThreadPanelJ {get {if (_WatchOtherThreadPanelJ == null) {_WatchOtherThreadPanelJ = jQuery.Select("#" + clientId + "_WatchOtherThreadPanel");}; return _WatchOtherThreadPanelJ;}} private jQueryObject _WatchOtherThreadPanelJ;
		public Element NumberOfTopicsFromWatchingOtherThreadLabel {get {if (_NumberOfTopicsFromWatchingOtherThreadLabel == null) {_NumberOfTopicsFromWatchingOtherThreadLabel = (Element)Document.GetElementById(clientId + "_NumberOfTopicsFromWatchingOtherThreadLabel");}; return _NumberOfTopicsFromWatchingOtherThreadLabel;}} private Element _NumberOfTopicsFromWatchingOtherThreadLabel;
		public jQueryObject NumberOfTopicsFromWatchingOtherThreadLabelJ {get {if (_NumberOfTopicsFromWatchingOtherThreadLabelJ == null) {_NumberOfTopicsFromWatchingOtherThreadLabelJ = jQuery.Select("#" + clientId + "_NumberOfTopicsFromWatchingOtherThreadLabel");}; return _NumberOfTopicsFromWatchingOtherThreadLabelJ;}} private jQueryObject _NumberOfTopicsFromWatchingOtherThreadLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public DivElement WatchOtherTopicOptionsPanel {get {if (_WatchOtherTopicOptionsPanel == null) {_WatchOtherTopicOptionsPanel = (DivElement)Document.GetElementById(clientId + "_WatchOtherTopicOptionsPanel");}; return _WatchOtherTopicOptionsPanel;}} private DivElement _WatchOtherTopicOptionsPanel;
		public jQueryObject WatchOtherTopicOptionsPanelJ {get {if (_WatchOtherTopicOptionsPanelJ == null) {_WatchOtherTopicOptionsPanelJ = jQuery.Select("#" + clientId + "_WatchOtherTopicOptionsPanel");}; return _WatchOtherTopicOptionsPanelJ;}} private jQueryObject _WatchOtherTopicOptionsPanelJ;
		public SelectElement OtherTopicOptionsDropDownList {get {if (_OtherTopicOptionsDropDownList == null) {_OtherTopicOptionsDropDownList = (SelectElement)Document.GetElementById(clientId + "_OtherTopicOptionsDropDownList");}; return _OtherTopicOptionsDropDownList;}} private SelectElement _OtherTopicOptionsDropDownList;
		public jQueryObject OtherTopicOptionsDropDownListJ {get {if (_OtherTopicOptionsDropDownListJ == null) {_OtherTopicOptionsDropDownListJ = jQuery.Select("#" + clientId + "_OtherTopicOptionsDropDownList");}; return _OtherTopicOptionsDropDownListJ;}} private jQueryObject _OtherTopicOptionsDropDownListJ;
		public InputElement OtherOptionsUpdateButton {get {if (_OtherOptionsUpdateButton == null) {_OtherOptionsUpdateButton = (InputElement)Document.GetElementById(clientId + "_OtherOptionsUpdateButton");}; return _OtherOptionsUpdateButton;}} private InputElement _OtherOptionsUpdateButton;
		public jQueryObject OtherOptionsUpdateButtonJ {get {if (_OtherOptionsUpdateButtonJ == null) {_OtherOptionsUpdateButtonJ = jQuery.Select("#" + clientId + "_OtherOptionsUpdateButton");}; return _OtherOptionsUpdateButtonJ;}} private jQueryObject _OtherOptionsUpdateButtonJ;
		public Element WatchOtherTopicOptionsLabel {get {if (_WatchOtherTopicOptionsLabel == null) {_WatchOtherTopicOptionsLabel = (Element)Document.GetElementById(clientId + "_WatchOtherTopicOptionsLabel");}; return _WatchOtherTopicOptionsLabel;}} private Element _WatchOtherTopicOptionsLabel;
		public jQueryObject WatchOtherTopicOptionsLabelJ {get {if (_WatchOtherTopicOptionsLabelJ == null) {_WatchOtherTopicOptionsLabelJ = jQuery.Select("#" + clientId + "_WatchOtherTopicOptionsLabel");}; return _WatchOtherTopicOptionsLabelJ;}} private jQueryObject _WatchOtherTopicOptionsLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public InputElement RefreshButton {get {if (_RefreshButton == null) {_RefreshButton = (InputElement)Document.GetElementById(clientId + "_RefreshButton");}; return _RefreshButton;}} private InputElement _RefreshButton;
		public jQueryObject RefreshButtonJ {get {if (_RefreshButtonJ == null) {_RefreshButtonJ = jQuery.Select("#" + clientId + "_RefreshButton");}; return _RefreshButtonJ;}} private jQueryObject _RefreshButtonJ;
		public DivElement NoInboxSpamPanel {get {if (_NoInboxSpamPanel == null) {_NoInboxSpamPanel = (DivElement)Document.GetElementById(clientId + "_NoInboxSpamPanel");}; return _NoInboxSpamPanel;}} private DivElement _NoInboxSpamPanel;
		public jQueryObject NoInboxSpamPanelJ {get {if (_NoInboxSpamPanelJ == null) {_NoInboxSpamPanelJ = jQuery.Select("#" + clientId + "_NoInboxSpamPanel");}; return _NoInboxSpamPanelJ;}} private jQueryObject _NoInboxSpamPanelJ;
		public Element H1 {get {if (_H1 == null) {_H1 = (Element)Document.GetElementById(clientId + "_H1");}; return _H1;}} private Element _H1;
		public jQueryObject H1J {get {if (_H1J == null) {_H1J = jQuery.Select("#" + clientId + "_H1");}; return _H1J;}} private jQueryObject _H1J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public InputElement RefreshButton2 {get {if (_RefreshButton2 == null) {_RefreshButton2 = (InputElement)Document.GetElementById(clientId + "_RefreshButton2");}; return _RefreshButton2;}} private InputElement _RefreshButton2;
		public jQueryObject RefreshButton2J {get {if (_RefreshButton2J == null) {_RefreshButton2J = jQuery.Select("#" + clientId + "_RefreshButton2");}; return _RefreshButton2J;}} private jQueryObject _RefreshButton2J;
		public Element GenericContainerPage {get {if (_GenericContainerPage == null) {_GenericContainerPage = (Element)Document.GetElementById(clientId + "_GenericContainerPage");}; return _GenericContainerPage;}} private Element _GenericContainerPage;
		public jQueryObject GenericContainerPageJ {get {if (_GenericContainerPageJ == null) {_GenericContainerPageJ = jQuery.Select("#" + clientId + "_GenericContainerPage");}; return _GenericContainerPageJ;}} private jQueryObject _GenericContainerPageJ;//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
	}
}
