// MapControl.js
(function($){
Type.registerNamespace('Js.Controls.MapControl');Js.Controls.MapControl.Controller=function(view){this.$1={};this.$0=view;this.gmap2=new GMap2(view.get_map());this.gmap2.addControl(new GLargeMapControl());var $0=parseFloat(view.get_uiNorth().value);var $1=parseFloat(view.get_uiSouth().value);var $2=parseFloat(view.get_uiWest().value);var $3=parseFloat(view.get_uiEast().value);var $4=$0-$1;var $5=$3-$2;var $6=new GLatLng($0+$4/20,$3+$5/20,true);var $7=new GLatLng($1-$4/20,$2-$5/20,true);var $8=new GLatLngBounds($7,$6);$8.extend($7);$8.extend($6);var $9=this.gmap2.getBoundsZoomLevel($8);if($9>12){$9=12;}var $A=new GLatLng(($0+$1)/2,($3+$2)/2,true);this.gmap2.enableScrollWheelZoom();this.gmap2.setCenter($A,$9);this.gmap2.enableContinuousZoom();this.gmap2.enableDoubleClickZoom();this.gmap2.enableGoogleBar();this.gmap2.checkResize();}
Js.Controls.MapControl.Controller.prototype={$0:null,gmap2:null,addMapMarkers:function(items){if(items!=null){for(var $0=0;$0<items.length;$0++){var $1=this.$2(items[$0].lat,items[$0].lon);var $2=document.createElement('LI');$2.innerHTML=items[$0].hoverText;$1.$1.appendChild($2);}}},clearMarkers:function(){var $enum1=ss.IEnumerator.getEnumerator(Object.keys(this.$1));while($enum1.moveNext()){var $0=$enum1.current;var $1=this.$1[$0];$1.$2();}this.gmap2.clearOverlays();this.$1={};},$2:function($p0,$p1){var $0=$p0.toString()+','+$p1.toString();if(this.$1[$0]==null){var $1=new GMarker(new GLatLng($p0,$p1,true));this.gmap2.addOverlay($1);var $2=new Js.Controls.MapControl._Marker($1);this.$1[$0]=$2;return $2;}else{return this.$1[$0];}}}
Js.Controls.MapControl.View=function(clientId){this.clientId=clientId;}
Js.Controls.MapControl.View.prototype={clientId:null,get_map:function(){if(this.$0==null){this.$0=document.getElementById(this.clientId+'_map');}return this.$0;},$0:null,get_mapJ:function(){if(this.$1==null){this.$1=$('#'+this.clientId+'_map');}return this.$1;},$1:null,get_uiNorth:function(){if(this.$2==null){this.$2=document.getElementById(this.clientId+'_uiNorth');}return this.$2;},$2:null,get_uiNorthJ:function(){if(this.$3==null){this.$3=$('#'+this.clientId+'_uiNorth');}return this.$3;},$3:null,get_uiSouth:function(){if(this.$4==null){this.$4=document.getElementById(this.clientId+'_uiSouth');}return this.$4;},$4:null,get_uiSouthJ:function(){if(this.$5==null){this.$5=$('#'+this.clientId+'_uiSouth');}return this.$5;},$5:null,get_uiEast:function(){if(this.$6==null){this.$6=document.getElementById(this.clientId+'_uiEast');}return this.$6;},$6:null,get_uiEastJ:function(){if(this.$7==null){this.$7=$('#'+this.clientId+'_uiEast');}return this.$7;},$7:null,get_uiWest:function(){if(this.$8==null){this.$8=document.getElementById(this.clientId+'_uiWest');}return this.$8;},$8:null,get_uiWestJ:function(){if(this.$9==null){this.$9=$('#'+this.clientId+'_uiWest');}return this.$9;},$9:null}
Js.Controls.MapControl.MapItem=function(){}
Js.Controls.MapControl.MapItem.prototype={data:null,lat:0,lon:0,hoverText:null}
Js.Controls.MapControl._Marker=function(gMarker){this.$0=gMarker;this.$1=document.createElement('UL');GEvent.addListener(gMarker,'mouseout',function(){
try{htm();;}catch($1_0){}});GEvent.addListener(gMarker,'click',function(){
});GEvent.addListener(gMarker,'mouseover',ss.Delegate.create(this,function(){
stt(this.$1.innerHTML);;}));GEvent.addListener(gMarker,'mouseout',function(){
try{htm();;}catch($1_0){}});}
Js.Controls.MapControl._Marker.prototype={$0:null,$1:null,$2:function(){GEvent.clearListeners(this.$0,'click');GEvent.clearListeners(this.$0,'onmouseover');GEvent.clearListeners(this.$0,'onmouseout');}}
Js.Controls.MapControl.Controller.registerClass('Js.Controls.MapControl.Controller');Js.Controls.MapControl.View.registerClass('Js.Controls.MapControl.View');Js.Controls.MapControl.MapItem.registerClass('Js.Controls.MapControl.MapItem');Js.Controls.MapControl._Marker.registerClass('Js.Controls.MapControl._Marker');})(jQuery);// This script was generated using Script# v0.7.4.0
