// PlacesChooser.js
(function($){
Type.registerNamespace('Js.Controls.PlacesChooser');Js.Controls.PlacesChooser.Controller=function(view){this.view=view;view.get_uiAddRadiusButtonJ().click(ss.Delegate.create(this,this.$0));this.$1();GEvent.addListener(this.view.get_uiMap().gmap2,'moveend',ss.Delegate.create(this,this.$1));GEvent.addListener(this.view.get_uiMap().gmap2,'zoomend',ss.Delegate.create(this,this.$1));}
Js.Controls.PlacesChooser.Controller.prototype={view:null,$0:function($p0){try{Js.Controls.PlacesChooser.Service.getSurroundingPlaces(parseInt(this.view.get_uiRadiusPlaceAutoComplete().get_value()),parseInt(this.view.get_uiNumberOfSurroundingTownsDropDown().value),ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
for(var $1_0=0;$1_0<$p1_0.length;$1_0++){this.view.get_uiPlacesMultiSelector().addItem($p1_0[$1_0].name,$p1_0[$1_0].k.toString());}this.view.get_uiRadiusPlaceAutoComplete().clear();}),Js.Library.Trace.webServiceFailure,null,5000);}catch($0){}$p0.preventDefault();},$1:function(){var $0=this.view.get_uiMap().gmap2.getBounds();Js.Controls.PlacesChooser.Service.getPlaces($0.getNorthEast().lat(),$0.getSouthWest().lat(),$0.getNorthEast().lng(),$0.getSouthWest().lng(),20,ss.Delegate.create(this,this.$3),Js.Library.Trace.webServiceFailure,null,3000);},$2:null,$3:function($p0,$p1,$p2){if(this.$2!=null){for(var $0=0;$0<this.$2.length;$0++){GEvent.clearListeners(this.$2[$0],'click');GEvent.clearListeners(this.$2[$0],'onmouseover');GEvent.clearListeners(this.$2[$0],'onmouseout');}}this.view.get_uiMap().gmap2.clearOverlays();this.$2=[];for(var $1=0;$1<$p0.length;$1++){var $2=$p0[$1];this.$4($2.lat,$2.lng,$2.name,$2.k);}},$4:function($p0,$p1,$p2,$p3){var $0=new GLatLng($p0,$p1,true);var $1=new GMarker($0);$1.k = $p3;;$1.name = $p2;;GEvent.addListener($1,'click',ss.Delegate.create(this,function(){
this.view.get_uiPlacesMultiSelector().addItem($p2,$p3.toString());}));GEvent.addListener($1,'mouseover',function(){
stt($p2);;});GEvent.addListener($1,'mouseout',function(){
try{htm();;}catch($1_0){}});this.view.get_uiMap().gmap2.addOverlay($1);this.$2[this.$2.length]=$1;}}
Js.Controls.PlacesChooser.Service=function(){}
Js.Controls.PlacesChooser.Service.getPlaces=function(north,south,east,west,maximumNumber,success,failure,userContext,timeout){var $0={};$0['north']=north;$0['south']=south;$0['east']=east;$0['west']=west;$0['maximumNumber']=maximumNumber;var $1=Js.Library.WebServiceHelper.options('GetPlaces','/WebServices/Controls/PlacesChooser/Service.asmx',$0,failure,userContext,timeout);$1.success=function($p1_0,$p1_1,$p1_2){
success(($p1_0)['d'],userContext,'GetPlaces');};$.ajax($1);}
Js.Controls.PlacesChooser.Service.getSurroundingPlaces=function(centredOnPlaceK,numberOfPlacesToGet,success,failure,userContext,timeout){var $0={};$0['centredOnPlaceK']=centredOnPlaceK;$0['numberOfPlacesToGet']=numberOfPlacesToGet;var $1=Js.Library.WebServiceHelper.options('GetSurroundingPlaces','/WebServices/Controls/PlacesChooser/Service.asmx',$0,failure,userContext,timeout);$1.success=function($p1_0,$p1_1,$p1_2){
success(($p1_0)['d'],userContext,'GetSurroundingPlaces');};$.ajax($1);}
Js.Controls.PlacesChooser.View=function(clientId){this.clientId=clientId;}
Js.Controls.PlacesChooser.View.prototype={clientId:null,get_uiPlacesMultiSelector:function(){return eval(this.clientId+'_uiPlacesMultiSelectorBehaviour');},get_uiMap:function(){return eval(this.clientId+'_uiMapController');},get_uiPlacesRadius:function(){if(this.$0==null){this.$0=document.getElementById(this.clientId+'_uiPlacesRadius');}return this.$0;},$0:null,get_uiPlacesRadiusJ:function(){if(this.$1==null){this.$1=$('#'+this.clientId+'_uiPlacesRadius');}return this.$1;},$1:null,get_uiNumberOfSurroundingTownsDropDown:function(){if(this.$2==null){this.$2=document.getElementById(this.clientId+'_uiNumberOfSurroundingTownsDropDown');}return this.$2;},$2:null,get_uiNumberOfSurroundingTownsDropDownJ:function(){if(this.$3==null){this.$3=$('#'+this.clientId+'_uiNumberOfSurroundingTownsDropDown');}return this.$3;},$3:null,get_uiRadiusPlaceAutoComplete:function(){return eval(this.clientId+'_uiRadiusPlaceAutoCompleteBehaviour');},get_uiAddRadiusButton:function(){if(this.$4==null){this.$4=document.getElementById(this.clientId+'_uiAddRadiusButton');}return this.$4;},$4:null,get_uiAddRadiusButtonJ:function(){if(this.$5==null){this.$5=$('#'+this.clientId+'_uiAddRadiusButton');}return this.$5;},$5:null}
Js.Controls.PlacesChooser.PlaceStub=function(){}
Js.Controls.PlacesChooser.PlaceStub.prototype={k:0,name:null,lat:0,lng:0}
Js.Controls.PlacesChooser.Controller.registerClass('Js.Controls.PlacesChooser.Controller');Js.Controls.PlacesChooser.Service.registerClass('Js.Controls.PlacesChooser.Service');Js.Controls.PlacesChooser.View.registerClass('Js.Controls.PlacesChooser.View');Js.Controls.PlacesChooser.PlaceStub.registerClass('Js.Controls.PlacesChooser.PlaceStub');})(jQuery);// This script was generated using Script# v0.7.4.0
