using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using Bobs;
using System.IO;

using Common;



namespace Spotted.Admin
{
	public partial class Utility : AdminUserControl
	{
		protected PlaceHolder OutPh;

		#region Template
		public void Template(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting xxx...", 1);
			Query q = new Query();
			//q.QueryCondition=???
			CommentSet bs = new CommentSet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				Comment c = bs[count];

				try
				{
					// Do work here!
					c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region GenBannerStats_Click (removed)
		//protected void GenBannerStats_Click(object sender, EventArgs eventArgs)
		//{
		//    Banner.GeneratePositionStats();
		//}
		#endregion

		#region UpdateOldDBInvoices_Click
		public void UpdateOldDBInvoices_Click(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting xxx...", 1);

			Query InvoiceQuery = new Query();
			InvoiceQuery.OrderBy = new OrderBy(Invoice.Columns.K, OrderBy.OrderDirection.Ascending);

			InvoiceSet bs = new InvoiceSet(InvoiceQuery);

			for (int count = 0; count < bs.Count; count++)
			{
				Invoice invoice = bs[count];

				try
				{
					invoice.Type = Invoice.Types.Invoice;
					invoice.IsImmediateCreditCardPayment = true;
					invoice.ActionUsrK = invoice.UsrK;
					invoice.VatCode = Invoice.VATCodes.T1;
					decimal invoicePrice = 0;
					decimal invoiceVat = 0;
					decimal invoiceTotal = 0;

					foreach (InvoiceItem invoiceItem in invoice.Items)
					{
						//invoiceItem.Price = Math.Round(invoiceItem.Price, 2);
						//invoiceItem.Vat = Math.Round(invoiceItem.Vat, 2);
						//invoiceItem.Total = Math.Round(invoiceItem.Total, 2);

						invoicePrice += invoiceItem.Price;
						invoiceVat += invoiceItem.Vat;
						invoiceTotal += invoiceItem.Total;

						if (invoiceItem.Type == InvoiceItem.Types.CharityDonation)
							invoiceItem.VatCode = InvoiceItem.VATCodes.T9;
						else if(invoiceItem.Vat.Equals(0))
							invoiceItem.VatCode = InvoiceItem.VATCodes.T0;
						else
							invoiceItem.VatCode = InvoiceItem.VATCodes.T1;

						if (invoiceItem.Type == InvoiceItem.Types.Banner || invoiceItem.Type == InvoiceItem.Types.BannerEmail || invoiceItem.Type == InvoiceItem.Types.BannerHotbox
							|| invoiceItem.Type == InvoiceItem.Types.BannerPhoto || invoiceItem.Type == InvoiceItem.Types.BannerSkyscraper || invoiceItem.Type == InvoiceItem.Types.BannerTop)
						{
							try
							{
								Banner banner = new Banner(invoiceItem.KeyData);
								invoiceItem.RevenueStartDate = banner.FirstDay;
								invoiceItem.RevenueEndDate = banner.LastDay;
							}
							catch (Exception)
							{ }
						}
						else
						{
							invoiceItem.RevenueStartDate = invoice.CreatedDateTime;
							invoiceItem.RevenueEndDate = invoice.CreatedDateTime;
						}
						invoiceItem.Update();
					}

					invoice.Price = Math.Round(invoicePrice,2);
					invoice.Vat = Math.Round(invoiceVat,2);
					invoice.Total = Math.Round(invoiceTotal, 2);

					if (invoice.DueDateTime.Equals(DateTime.MinValue))
						invoice.DueDateTime = invoice.CreatedDateTime.AddDays(30);

					invoice.UpdateAndSetPaidStatus();

					// If there arent transfers paying for this invoices yet, then create them.
					decimal amountPaid = invoice.AmountPaid;
					if (Math.Round(invoice.Total,2) > Math.Round(amountPaid,2))
					{
						InvoiceTransferSet invoiceTransferSet = new InvoiceTransferSet(new Query(new Q(InvoiceTransfer.Columns.InvoiceK, invoice.K)));
						if (invoiceTransferSet.Count == 0)
						{
							Transfer transfer = new Transfer();
							transfer.ActionUsrK = invoice.UsrK;
							transfer.Amount = Math.Round(invoice.Total - amountPaid, 2);
							transfer.DateTimeComplete = invoice.CreatedDateTime;
							transfer.DateTimeCreated = invoice.CreatedDateTime;
							transfer.Method = Transfer.Methods.Card;
							transfer.AddNote("Autogenerated Transfer to create transfer for old system invoice.", "System");
							transfer.PromoterK = invoice.PromoterK;
							transfer.Status = Transfer.StatusEnum.Success;
							transfer.Type = Transfer.TransferTypes.Payment;
							transfer.UsrK = invoice.UsrK;
							// Will be fully applied
							transfer.IsFullyApplied = true;

							transfer.CardAddress1 = invoice.Address;
							transfer.CardName = invoice.Name;
							transfer.CardPostcode = invoice.Postcode;

							transfer.Update();

							InvoiceTransfer invoiceTransfer = new InvoiceTransfer();
							invoiceTransfer.InvoiceK = invoice.K;
							invoiceTransfer.TransferK = transfer.K;
							invoiceTransfer.Amount = transfer.Amount;

							invoiceTransfer.Update();

							invoice.UpdateAndSetPaidStatus();
						}
					}
					invoice.PaidDateTime = invoice.CreatedDateTime;
					invoice.Update();
					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);
				}
				catch (Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);
			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region FixPromoterQuestions
		public void FixPromoterQuestions(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting promoters...", 1);
			Query q = new Query();
			//q.QueryCondition=???
			PromoterSet bs = new PromoterSet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				Promoter c = bs[count];

				try
				{
					Thread t = new Thread(c.QuestionsThreadK);
					t.Subject = c.Name + " promoter questions";
					t.Update();
					// Do work here!
					//c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region AddMailNotes
		public void AddMailNotes(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting xxx...", 1);
			Query q = new Query();
			q.QueryCondition = new Q(Promoter.Columns.LetterStatus, Promoter.LetterStatusEnum.Posted);
			PromoterSet bs = new PromoterSet(q);
			Usr dsi = new Usr(8);
			for (int count = 0; count < bs.Count; count++)
			{
				Promoter c = bs[count];

				try
				{
					c.LetterStatus = Promoter.LetterStatusEnum.Posted;
					c.SalesHold = false;
					c.SalesNextCall = DateTime.Today.AddDays(7);
					c.Update();
					c.AddNote("Sent media pack (with " + c.LetterType + " letter)", Guid.NewGuid(), dsi);
				
					// Do work here!
					c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region UpdatePromoterRandom
		public void UpdatePromoterRandom(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting Promoters...", 1);
			Query q = new Query();
			PromoterSet bs = new PromoterSet(q);
			Random r = new Random();
			for (int count = 0; count < bs.Count; count++)
			{
				Promoter c = bs[count];

				try
				{
					// Do work here!
					c.OfferType = Promoter.OfferTypes.None;
					c.AccessCodeRandom = r.Next(1000, 9999).ToString() + r.Next(1000, 9999).ToString();
					c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region AddFabeDamola
		public void AddFabeDamola(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting promoters...", 1);
			Query q = new Query();
			//q.QueryCondition=???
			if (Vars.DevEnv)
				q.TopRecords = 50;
			PromoterSet bs = new PromoterSet(q);

			for (int count = 0; count < bs.Count; count++)
			{
				Promoter c = bs[count];

				try
				{
					Thread t = new Thread(c.QuestionsThreadK);

					try
					{
						ThreadUsr tu = new ThreadUsr(t.K, 4);
						tu.Delete();
					}
					catch { }

					try
					{
						ThreadUsr tu = new ThreadUsr(t.K, 294380);
						tu.Delete();
					}
					catch { }

					try
					{
						ThreadUsr tuFabe = new ThreadUsr(t.K, 339849);
					}
					catch
					{
						ThreadUsr tuFabe = new ThreadUsr();
						tuFabe.ThreadK = t.K;
						tuFabe.UsrK = 339849;
						tuFabe.InvitingUsrK = 1;
						tuFabe.Status = ThreadUsr.StatusEnum.Archived;
						tuFabe.DateTime = DateTime.Now;
						tuFabe.PrivateChatType = ThreadUsr.PrivateChatTypes.None;
						tuFabe.Favourite = false;
						tuFabe.Deleted = false;
						tuFabe.ViewDateTime = DateTime.Now;
						tuFabe.ViewDateTimeLatest = DateTime.Now;
						tuFabe.ViewComments = t.TotalComments;
						tuFabe.ViewCommentsLatest = t.TotalComments;
						tuFabe.StatusChangeDateTime = DateTime.Now;
						tuFabe.StatusChangeObjectType = Model.Entities.ObjectType.Usr;
						tuFabe.StatusChangeObjectK = 339849;
						tuFabe.Update();
					}


					try
					{
						ThreadUsr tuDamola = new ThreadUsr(t.K, 319215);
					}
					catch
					{
						ThreadUsr tuDamola = new ThreadUsr();
						tuDamola.ThreadK = t.K;
						tuDamola.UsrK = 319215;
						tuDamola.InvitingUsrK = 1;
						tuDamola.Status = ThreadUsr.StatusEnum.Archived;
						tuDamola.DateTime = DateTime.Now;
						tuDamola.PrivateChatType = ThreadUsr.PrivateChatTypes.None;
						tuDamola.Favourite = false;
						tuDamola.Deleted = false;
						tuDamola.ViewDateTime = DateTime.Now;
						tuDamola.ViewDateTimeLatest = DateTime.Now;
						tuDamola.ViewComments = t.TotalComments;
						tuDamola.ViewCommentsLatest = t.TotalComments;
						tuDamola.StatusChangeDateTime = DateTime.Now;
						tuDamola.StatusChangeObjectType = Model.Entities.ObjectType.Usr;
						tuDamola.StatusChangeObjectK = 319215;
						tuDamola.Update();
					}

					// Do work here!
					//c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + c.Name + " - " + count + "/" + bs.Count, 2);

				}
				catch (Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion
		#region SortPromoterNotes
		public void SortPromoterNotes(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting Promoters...", 1);
			Query q = new Query();
			//q.QueryCondition=???
			PromoterSet bs = new PromoterSet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				Promoter c = bs[count];

				try
				{
					if (c.ManualNote.Length > 0)
					{
						SalesCall scNote = new SalesCall();
						scNote.DuplicateGuid = Guid.NewGuid();
						scNote.UsrK = Usr.Current.K;
						scNote.PromoterK = c.K;
						scNote.DateTimeStart = DateTime.Now;
						scNote.DateTimeEnd = scNote.DateTimeStart;
						scNote.Duration = 0;
						scNote.Dismissed = true;
						scNote.InProgress = false;
						scNote.Direction = SalesCall.Directions.Outgoing;
						if (c.EffectiveSalesStatus.Equals(Promoter.SalesStatusEnum.Active))
							scNote.Type = SalesCall.Types.Active;
						else if (c.EffectiveSalesStatus.Equals(Promoter.SalesStatusEnum.Proactive))
							scNote.Type = SalesCall.Types.ProactiveFollowUp;
						else
							scNote.Type = SalesCall.Types.Cold;
						scNote.IsCall = false;
						scNote.Note = c.ManualNote;
						scNote.Effective = true;
						scNote.Update();
					}
					// Do work here!
					//c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region UpdateIpCountry
		public void UpdateIpCountry(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting IpCountry entries...", 1);
			Query q = new Query();
			IpCountrySet bs = new IpCountrySet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				IpCountry c = bs[count];

				try
				{

					Country country = null;
					CountrySet cs = new CountrySet(new Query(new Q(Country.Columns.Code2Letter, c.Code2Letter)));
					if (cs.Count == 1)
						country = cs[0];
					else
					{
						CountrySet cs1 = new CountrySet(new Query(new Q(Country.Columns.Code3Letter, c.Code3Letter)));
						if (cs1.Count == 1)
							country = cs1[0];
					}
					
					if (country != null)
						c.CountryK = country.K;
					else
						c.CountryK = 0;

					c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion
		
		#region CopyPageTimeLog
		public void CopyPageTimeLog(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting...", 1);

			DateTime d1 = DateTime.Today;
			DateTime d = DateTime.Today;
			int i = 0;
			int count = 0;
			System.Data.SqlClient.SqlDataReader dr = Cambro.Misc.Db.Dr("select Date, LogItem, sum(Impressions) from PageTime WHERE LogItem>0 group by Date, LogItem  order by Date, LogItem ");

			
				while (dr.Read())
				{
					try
					{
						d = (DateTime)dr[0];
						i = (int)dr[1];
						count = int.Parse(dr[2].ToString());
						if (count > 0)
						{
							Log.Increment((Log.Items)i, count, d);
						}

						if (d != d1)
						{
							Cambro.Web.Helpers.WriteAlert("Done " + d + " - " + ((Log.Items)i).ToString() + " - " + count, 2);
							d1 = d;
						}

					}
					catch(Exception ex)
					{
						Cambro.Web.Helpers.WriteAlert("Exception " + d + " - " + ex.ToString(), 3);
					}
				}

				



			
			Cambro.Web.Helpers.WriteAlert("Done!", 4);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region SendGlobalEmail
		public void SendGlobalEmail(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("SendGlobalEmail...", 1);
			Query q = new Query();
			if (Vars.DevEnv)
				q.TopRecords = 50;
			q.QueryCondition = new Q(UsrEventAttended.Columns.EventK, 25099);
			q.TableElement = new Join(Usr.Columns.K, UsrEventAttended.Columns.UsrK);
			UsrSet bs = new UsrSet(q);
			Event globalEvent = new Event(25099);
			for (int count = 0; count < bs.Count; count++)
			{
				Usr c = bs[count];

				try
				{
					Mailer m = new Mailer();
					m.Bulk = true;
					m.RedirectUrl = globalEvent.Url();
					m.Subject = "SUBJECT";
					m.Body = "<p>BODY</p>";
					m.UsrRecipient = c;
					m.Send();


					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion
		#region SendSpotterInvitesAll
		public void SendSpotterInvitesAll(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting spotters...", 1);
			Query q = new Query();
			q.QueryCondition = new Q(Usr.Columns.IsSpotter, true);
			UsrSet bs = new UsrSet(q);

			Usr dsiUsr = new Usr(8);
			Bobs.Group spottersGroup = new Bobs.Group(3480);
			Bobs.Group spottersGroupUsa = new Bobs.Group(4537);
			GroupUsr guDsi = spottersGroup.GetGroupUsr(dsiUsr);
			GroupUsr guDsiUsa = spottersGroupUsa.GetGroupUsr(dsiUsr);

			for (int count = 0; count < bs.Count && count<1000; count++)
			{
				Usr c = bs[count];

				try
				{

					GroupUsr guTarget = spottersGroup.GetGroupUsr(c);
					spottersGroup.Invite(c, guTarget, dsiUsr, guDsi, "Chat about being a Spotter and all things Spotting in the DontStayIn Spotters group!", false);

					if (c.AddressCountryK == 225)
					{
						GroupUsr guTargetUsa = spottersGroupUsa.GetGroupUsr(c);
						spottersGroupUsa.Invite(c, guTargetUsa, dsiUsr, guDsiUsa, "Chat about being a USA based DontStayIn Spotter in the USA Spotters group!", false);
					}
					if (count % 100 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region SendSpotterInvites
		public void SendSpotterInvites(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting spotters...", 1);
			Query q = new Query();
			q.QueryCondition = new And(
				new Q(Usr.Columns.IsSpotter, true),
				new Q(Usr.Columns.AddressCountryK, QueryOperator.NotEqualTo, 224),
				new Q(Usr.Columns.AddressCountryK, QueryOperator.NotEqualTo, 225)
			);
			UsrSet bs = new UsrSet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				Usr c = bs[count];

				try
				{

					Mailer m = new Mailer();
					m.UsrRecipient = c;
					m.Subject = "Calling all DontStayIn Spotters - cards now available!";
					m.RedirectUrl = "/pages/spotters";
					m.Body = @"<p>Calling all spotters!</p>

<p>You recently signed up as a Spotter on DontStayIn, but because you weren't based in the UK we couldn't send you a pack of cards. Spotter cards help people find their photos, and get the word out about DontStayIn!</p>

<p><b>We can now send spotter cards all over the world!</b></p>

<p>Just visit the <a href=""[LOGIN]"">Spotters page</a>, check your address is still correct, and click the 'request more cards' button. We'll send them out straight away.</p>

<p>Please note they will be sent airmail from the UK, so they may take about a week to arrive.</p>
";
					m.Send();

					// Do work here!
					c.Update();

					Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region SendPromoterIntros
		public void SendPromoterIntros(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting inactive promoters...", 1);
			Query q = new Query();
			q.QueryCondition = new Q(Promoter.Columns.Status, Promoter.StatusEnum.Enabled);
			//q.QueryCondition=???
			if (Vars.DevEnv)
				q.TopRecords = 100;
			PromoterSet bs = new PromoterSet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				Promoter c = bs[count];

				try
				{
					foreach (Usr u in c.AdminUsrs)
					{
						Mailer m = new Mailer();
						m.UsrRecipient = u;
						m.Subject = "We've enabled your DontStayIn promoter account!";
						m.RedirectUrl = c.Url();
						m.Body = @"
<p>
You recently signed up as a promoter on DontStayIn. We've now enabled your 
account, so all the features are now available!
</p>

<p>
<b>Just click the 'Promoters' button at the top of the page to see all the new options.</b>
</p>

<p>
We're still available if you get stuck or need something explained. Just give us a call on 
0207 835 5599.
</p>
";
						m.Send();
					}

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region SendSalesSummaryNow
		protected void SendSalesSummaryNow(object sender, EventArgs eventArgs)
		{
			Invoice.SendSalesSummaries();
		}
		#endregion

		#region AddGarethDarren
		public void AddGarethDarren(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting promoters...", 1);
			Query q = new Query();
			//q.QueryCondition=???
			PromoterSet bs = new PromoterSet(q);

			for (int count = 0; count < bs.Count; count++)
			{
				Promoter c = bs[count];

				try
				{
					Thread t = new Thread(c.QuestionsThreadK);

					try
					{
						ThreadUsr tu = new ThreadUsr(t.K, 4);
						tu.Delete();
					}
					catch { }

					try
					{
						ThreadUsr tu = new ThreadUsr(t.K, 78392);
						tu.Delete();
					}
					catch { }

					try
					{
						ThreadUsr tuDarren = new ThreadUsr(t.K, 289079);
					}
					catch
					{
						ThreadUsr tuDarren = new ThreadUsr();
						tuDarren.ThreadK = t.K;
						tuDarren.UsrK = 289079;
						tuDarren.InvitingUsrK = 1;
						tuDarren.Status = ThreadUsr.StatusEnum.Archived;
						tuDarren.DateTime = DateTime.Now;
						tuDarren.PrivateChatType = ThreadUsr.PrivateChatTypes.None;
						tuDarren.Favourite = false;
						tuDarren.Deleted = false;
						tuDarren.ViewDateTime = DateTime.Now;
						tuDarren.ViewDateTimeLatest = DateTime.Now;
						tuDarren.ViewComments = t.TotalComments;
						tuDarren.ViewCommentsLatest = t.TotalComments;
						tuDarren.StatusChangeDateTime = DateTime.Now;
						tuDarren.StatusChangeObjectType = Model.Entities.ObjectType.Usr;
						tuDarren.StatusChangeObjectK = 289079;
						tuDarren.Update();
					}


					try
					{
						ThreadUsr tuGareth = new ThreadUsr(t.K, 294380);
					}
					catch
					{
						ThreadUsr tuGareth = new ThreadUsr();
						tuGareth.ThreadK = t.K;
						tuGareth.UsrK = 294380;
						tuGareth.InvitingUsrK = 1;
						tuGareth.Status = ThreadUsr.StatusEnum.Archived;
						tuGareth.DateTime = DateTime.Now;
						tuGareth.PrivateChatType = ThreadUsr.PrivateChatTypes.None;
						tuGareth.Favourite = false;
						tuGareth.Deleted = false;
						tuGareth.ViewDateTime = DateTime.Now;
						tuGareth.ViewDateTimeLatest = DateTime.Now;
						tuGareth.ViewComments = t.TotalComments;
						tuGareth.ViewCommentsLatest = t.TotalComments;
						tuGareth.StatusChangeDateTime = DateTime.Now;
						tuGareth.StatusChangeObjectType = Model.Entities.ObjectType.Usr;
						tuGareth.StatusChangeObjectK = 294380;
						tuGareth.Update();
					}

					// Do work here!
					//c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + c.Name + " - " + count + "/" + bs.Count, 2);

				}
				catch (Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region FixAllPromoterQuestionsThreads
		public void FixAllPromoterQuestionsThreads(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting promoters...", 1);
			Query q = new Query(new Q(Promoter.Columns.K, QueryOperator.GreaterThan, 1));
			q.Columns = new ColumnSet(Promoter.Columns.K, Promoter.Columns.SalesUsrK, Promoter.Columns.QuestionsThreadK, Promoter.Columns.Name);
			//q.QueryCondition=???
			PromoterSet promoters = new PromoterSet(q);

			for (int count = 0; count < promoters.Count; count++)
			{
				try
				{
					promoters[count].FixQuestionsThreadUsrs();
					
					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + promoters[count].Name + " - " + count + "/" + promoters.Count, 2);
				}
				catch (Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + promoters.Count + " - " + ex.ToString(), 3);
				}
			}
			Cambro.Web.Helpers.WriteAlert("Done!", 4);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region FixAllCampaignCreditBalances
		public void FixAllCampaignCreditBalances(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting campaign credits...", 1);
			CampaignCreditSet allCampaignCredits = new CampaignCreditSet(new Query());
			int count = 0;
			foreach (CampaignCredit cc in allCampaignCredits)
			{
				count++;
					
				if (!cc.Enabled && cc.ActionDateTime < Time.Now.AddHours(-6))
					cc.Delete();
				else
				{
					cc.UpdateWithRecalculateBalance();
					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + cc.K.ToString() + " - " + count + "/" + allCampaignCredits.Count, 2);
				}
			}
			Cambro.Web.Helpers.WriteAlert("Done!", 4);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region EmailAfterEventFeedback
		public void EmailAfterEventFeedback(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting events...", 1);
				try
				{
					Utilities.EmailAfterEventTicketFeedback();
				}
				catch (Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception - " + ex.ToString(), 3);
				}
			Cambro.Web.Helpers.WriteAlert("Done!", 4);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region CampDsiEmails
		public void CampDsiEmails(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting users...", 1);
			Query q = new Query();
			q.TableElement = new JoinLeft(Usr.Columns.K, GroupUsr.Columns.UsrK);
			q.TableElement = new Join(q.TableElement, new TableElement(TablesEnum.UsrEventAttended), QueryJoinType.Left, Usr.Columns.K, UsrEventAttended.Columns.UsrK);
			
			q.QueryCondition = 
				new Or(
				new Q(GroupUsr.Columns.GroupK, 1060),
					new Q(UsrEventAttended.Columns.EventK, 29398),
					new Q(UsrEventAttended.Columns.EventK, 10597)
					);
			q.Distinct = true;
			q.DistinctColumn = Usr.Columns.K;
			UsrSet bs = new UsrSet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				Usr c = bs[count];

				try
				{

					Mailer m = new Mailer();
					m.UsrRecipient = c;
					m.RedirectUrl = "/event-29398";
					m.Subject = "DontStayIn 3rd birthday bash! - Camp DSI 2006!";
					m.Body = @"<p>
<div style=""font-size:33px; font-weight:bold; line-height:33px;"">
<center>DSI IS 3 YEARS OLD!</center>
</div>
</p>
<p>
<div style=""font-size:36px; font-weight:bold;line-height:36px;"">
<center>LETS GO CAMPING!</center>
</div>
</p>
<p>
<center>
Friday 16th June to Sunday 18th June 2006<br>
<a href=""[LOGIN]"">Camp DSI</a> @ <a href=""[LOGIN(/uk/barnstaple/little-roadway-farm-campsite)]"">Little Roadway Farm Campsite</a> in Woolacombe, North Devon
</center>
</p>
<table cellspacing=""10""><tr><td valign=""top"">
<p>
You are receiving this email because you are signed up to Camp DSI!
</p>
<p>
This year we are heading back to the beautiful Woolacombe in Devon to celebrate our third birthday! DSI will be 3 years old! Can you believe it?
</p>
<p> 
If you're not coming, please be so kind as to take your name off the <a href=""[LOGIN]"">event page</a>.
</p>
<p>
For those of you coming, <b>GET READY FOR A WEEKEND TO REMEMBER!</b>
</p>
<p>
This year you can expect a marquee playing music on Friday evening, Saturday daytime and evening and Sunday daytime.  We have lots of activities provided by some of our DSI regulars - currently we have:
</p>
<p>
<b>A dressing up tent, a giant BBQ, a tea tent, a break-dancing tent, a body painting tent, a casino / strip poker tent, a massage tent, a rubber dingy racing contest, a tequila drinking contest and photography lessons!!!</b>
</p>
<p>
If you think you could add anything to the fun, please put your name down on <a href=""[LOGIN(/chat/k-629074)]"">this topic</a> and we will be in contact.
</p>
<p>
Tickets are £20 for the whole weekend. That includes campsite fees etc.  The rest will be used to pay for marquees / sound rigs / all the other bits and bobs. 
</p>
<p>
<b>We've only got 300 tickets, but there are 400 of you signed up... Some of you might be disappointed if you don't buy your tickets early! The only way to get a ticket is to <a href=""[LOGIN]"">buy on the event page</a>. If you don't have a credit card, you can get one of your friends to buy one for you.</b>
</p>
<p>
Everyone who buys a ticket will get a little CAMP DSI icon on their profile!
</p>
<p>
We're really excited about this - it's going to be great to meet you all in the flesh! See you there!
</p>
</td>
<td valign=""top"">
<p>
<a href=""[LOGIN(/photo-503702)]""><img src=""[WEB-ROOT]gfx/camp-dsi-jump.jpg"" width=""100"" height=""133"" border=""0"" style=""border:1px solid #000000;""></a>
</p>
<p>
<a href=""[LOGIN(/photo-474887)]""><img src=""[WEB-ROOT]gfx/camp-dsi-matt.jpg"" width=""100"" height=""94"" border=""0"" style=""border:1px solid #000000;""></a>
</p>
<p>
<a href=""[LOGIN(/photo-476406)]""><img src=""[WEB-ROOT]gfx/camp-dsi-vw.jpg"" width=""100"" height=""133"" border=""0"" style=""border:1px solid #000000;""></a>
</p>
<p>
<a href=""[LOGIN(/photo-475245)]""><img src=""[WEB-ROOT]gfx/camp-dsi-girl.jpg"" width=""100"" height=""127"" border=""0"" style=""border:1px solid #000000;""></a>
</p>
</td></tr></table>
<p style=""margin-bottom:10px;"">
<center><a href=""[LOGIN]"" style=""font-size:20px; font-weight:bold;line-height:20px;"">CLICK HERE TO BUY YOUR TICKETS!</a></center>
</p>
";
					m.Send();
					//Response.Write(c.NickName + "<br>");

					// Do work here!
					//c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch (Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region CopyPics
		public void CopyPics(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting groups...", 1);
			Query q = new Query();

			q.TableElement = new Join(Group.Columns.BrandK, Brand.Columns.K);

			q.QueryCondition = new Or(
				new And(
					new Or(new Q(Group.Columns.Pic, QueryOperator.IsNull, null), new Q(Group.Columns.Pic, Guid.Empty)),
					new And(new Q(Brand.Columns.Pic, QueryOperator.IsNotNull, null), new Q(Brand.Columns.Pic, QueryOperator.NotEqualTo, Guid.Empty))
				),
				new And(
					new Or(new Q(Brand.Columns.Pic, QueryOperator.IsNull, null), new Q(Brand.Columns.Pic, Guid.Empty)),
					new And(new Q(Group.Columns.Pic, QueryOperator.IsNotNull, null), new Q(Group.Columns.Pic, QueryOperator.NotEqualTo, Guid.Empty))
				)
			);
			GroupSet bs = new GroupSet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				Group c = bs[count];

				try
				{
					if (c.HasPic && !c.Brand.HasPic)
					{
						Bobs.Utilities.CopyPic(c, c.Brand);
						Cambro.Web.Helpers.WriteAlert("Copying from " + c.UrlName + " to " + c.Brand.UrlName + " (" + count + "/" + bs.Count + ")", 2);
					}
					else if (!c.HasPic && c.Brand.HasPic)
					{
						Bobs.Utilities.CopyPic(c.Brand, c);
						Cambro.Web.Helpers.WriteAlert("Copying from " + c.Brand.UrlName + " to " + c.UrlName + " (" + count + "/" + bs.Count + ")", 2);
					}
					else
					{
						Cambro.Web.Helpers.WriteAlert("Not copying for " + c.Brand.UrlName + " / " + c.UrlName, 3);
					}
					// Do work here!
					//c.Update();

				}
				catch (Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception on " + c.UrlName + " - " + count + "/" + bs.Count + " - " + ex.ToString(), 4);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 5);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region SortArticleThreadK
		public void SortArticleThreadK(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting articles...", 1);
			Query q = new Query();
			ArticleSet bs = new ArticleSet(q);
			for (int count = 0; count < bs.Count; count++)
			{
				Article c = bs[count];

				try
				{
					Query q1 = new Query();
					q1.TopRecords=1;
					q1.OrderBy=new OrderBy(Thread.Columns.TotalComments, OrderBy.OrderDirection.Descending);
					q1.QueryCondition=new And(
						new Q(Thread.Columns.ArticleK, c.K), 
						new Q(Thread.Columns.Private, false),
						new Q(Thread.Columns.GroupK, 0));

					ThreadSet ts = new ThreadSet(q1);
					if (ts.Count == 0)
					{
						c.ThreadK = 0;
					}
					else
					{
						c.ThreadK = ts[0].K;
					}
					// Do work here!
					c.Update();

					if (count % 10 == 0)
						Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count, 2);

				}
				catch(Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
				}

				bs.Kill(count);

			}
			Cambro.Web.Helpers.WriteAlert("Done!", 3);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region SortIsPromoter
		public void SortIsPromoter(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting PromoterUsrs...", 1);
			Query q = new Query();
			q.QueryCondition = new Q(Promoter.Columns.Status, Promoter.StatusEnum.Active);
			q.TableElement = new Join(
				new Join(Usr.Columns.K, PromoterUsr.Columns.UsrK),
				Promoter.Columns.K,
				PromoterUsr.Columns.PromoterK);
			UsrSet bs = new UsrSet(q);

			Group g = new Group(3684); //DontStayIn Promoters group

			try
			{

				for (int count = 0; count < bs.Count; count++)
				{
					Usr u = bs[count];

					try
					{
						GroupUsr gu = u.GetGroupUsr(g.K);
						if (gu == null || !(gu.Status.Equals(GroupUsr.StatusEnum.Exited) || gu.Status.Equals(GroupUsr.StatusEnum.Barred)))
						{
							GroupUsr gu1 = g.ChangeUsr(false, u.K, false, false, false, false, Bobs.GroupUsr.StatusEnum.Member, u.DateTimeSignUp, false);
							gu1.Favourite = true;
							gu1.Update();
							CommentAlert.Enable(u, g.K, Model.Entities.ObjectType.Group);
						}


						if (count % 10 == 0)
							Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + bs.Count + " - " + u.NickName, 2);
					}
					catch (Exception ex)
					{
						Cambro.Web.Helpers.WriteAlert("Exception " + count + "/" + bs.Count + " - " + ex.ToString(), 3);
					}

					bs.Kill(count);

				}
			}
			finally
			{
				g.UpdateTotalMembers();
			}
			Cambro.Web.Helpers.WriteAlert("Done!", 4);
			Cambro.Web.Helpers.WriteAlertFooter();
			Response.End();
		}
		#endregion

		#region Test
		public void Test(object o, System.EventArgs e)
		{


			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting Test...", 1);
			for (int count = 0; count < 3; count++)
			{

				System.Threading.Thread.Sleep(500);
				Cambro.Web.Helpers.WriteAlert("Done " + count + "/3 - ", 2);


			}
			Cambro.Web.Helpers.WriteAlert("Done!", 4);
			Cambro.Web.Helpers.WriteAlertFooter();
			

		}
		#endregion

		#region EmailAllEndedTicketRuns
		public void EmailAllEndedTicketRuns(object o, System.EventArgs e)
		{
			Cambro.Web.Helpers.WriteAlertHeader();

			Cambro.Web.Helpers.WriteAlert("Selecting ended ticket runs...", 1);
				try
				{
					Utilities.EmailAllEndedTicketRuns();//DateTime.Now.AddHours(-1), DateTime.Now);
				}
				catch (Exception ex)
				{
					Cambro.Web.Helpers.WriteAlert("Exception - " + ex.ToString(), 3);
				}
			Cambro.Web.Helpers.WriteAlert("Done!", 4);
			Cambro.Web.Helpers.WriteAlertFooter();
		}
		#endregion

		#region AssignRandomTicketCodesToTicketRun
		public void AssignRandomTicketCodesToTicketRun(object o, System.EventArgs e)
		{
			try
			{
				int ticketRunK = Convert.ToInt32(TicketRunK.Text);
				TicketRun tr = new TicketRun(ticketRunK);
				foreach (Ticket t in tr.Tickets)
				{
					t.SetRandomCode();
					t.Update();
				}
			}
			catch { }
		}
		
		#endregion

		#region TestAsyncThreadStartForMailing
		public void TestAsyncThreadStartForMailing(object o, System.EventArgs e)
		{
            //if (Vars.DevEnv)
            //{
            //    Cambro.Web.Helpers.WriteAlertHeader();

            //    Cambro.Web.Helpers.WriteAlert("Selecting ended ticket runs...", 1);
            //    try
            //    {
            //        //Query q = new Query(new Q(Usr.Columns.FirstName, "Neil"));
            //        UsrSet usrs = new UsrSet(new Query(new And(new Q(Usr.Columns.FirstName, "Neil"),
            //                                                   new Q(Usr.Columns.IsEmailVerified, true))));
            //        int count = 0;
            //        foreach (Usr u in usrs)
            //        {
            //            Mailer mail = new Mailer();
            //            mail.Subject = "IGNORE: Test 10";
            //            mail.Body = mail.Subject + ". sdflkj lkjsdaf lkj sddbBBtrecv sfe  xcvsdf ewrwrr lafkjl sfksldakjwopeipwoe asdlkjm,sda sfdnmlsdfajkl m,sdfam,sdfasdfajkl sdfaklsdf m,paoi tm,ntelikm 4534m,5 23m,23 2123 1234 vd fg errt";
                    
            //            mail.UsrRecipient = u;
            //            mail.Send();
                        
            //            count++;

            //            if (count % 10 == 0)
            //                Cambro.Web.Helpers.WriteAlert("Done " + count + "/" + usrs.Count, 2);
            //        }
            //    }
            //    catch (Exception ex)
            //    {
            //        Cambro.Web.Helpers.WriteAlert("Exception - " + ex.ToString(), 3);
            //    }
            //    Cambro.Web.Helpers.WriteAlert("Done!", 4);
            //    Cambro.Web.Helpers.WriteAlertFooter();
            //}
		}
		#endregion        

		#region MailTicketMoneyReserveToAccounts
		public void MailTicketMoneyReserveToAccounts(object o, System.EventArgs e)
		{
			Utilities.EmailAccountsTicketFundsReserveAmount();
		}
		#endregion

		#region Web Form Designer generated code
		override protected void OnInit(EventArgs e)
		{
			//
			// CODEGEN: This call is required by the ASP.NET Web Form Designer.
			//
			InitializeComponent();
			base.OnInit(e);
		}

		/// <summary>
		///		Required method for Designer support - do not modify
		///		the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
		}
		#endregion
		
	}
}