//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using jQueryApi;
using Js.Library;

namespace Js.MixmagGreatest.Home
{
	public class Server {
		public Server(){}
		public void SetCookie(System.String signedRequest, Response response) { object[] paramArr = { signedRequest }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.MixmagGreatest.Home, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "SetCookie", paramArr, response, response); } catch (Exception e) { Dictionary<object, object> d = new Dictionary<object, object>(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
		public void VoteNow(System.Int32 mixmagGreatestDjK, System.String facebookSource, System.Boolean facebookMessage, Response response) { object[] paramArr = { mixmagGreatestDjK, facebookSource, facebookMessage }; ServerRequest req = (ServerRequest)Script.Eval("PageMethods.ClientRequest"); if (req != null) { try { req("Spotted.MixmagGreatest.Home, Spotted, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "VoteNow", paramArr, response, response); } catch (Exception e) { Dictionary<object, object> d = new Dictionary<object, object>(); d["Exception"] = true; d["ExceptionType"] = "ClientException"; d["Message"] = e.Message; d["StackTrace"] = ""; response(d); } } }
	}
	public partial class View
		 : Js.MixmagGreatestUserControl.View
	{
		public string clientId;
		public Server server;
		public View(string clientId)
			 : base(clientId)
		{
			this.clientId = clientId;
			this.server = new Server();
		}
		public InputElement PageIdToLike {get {if (_PageIdToLike == null) {_PageIdToLike = (InputElement)Document.GetElementById(clientId + "_PageIdToLike");}; return _PageIdToLike;}} private InputElement _PageIdToLike;
		public jQueryObject PageIdToLikeJ {get {if (_PageIdToLikeJ == null) {_PageIdToLikeJ = jQuery.Select("#" + clientId + "_PageIdToLike");}; return _PageIdToLikeJ;}} private jQueryObject _PageIdToLikeJ;
		public InputElement LikedPage {get {if (_LikedPage == null) {_LikedPage = (InputElement)Document.GetElementById(clientId + "_LikedPage");}; return _LikedPage;}} private InputElement _LikedPage;
		public jQueryObject LikedPageJ {get {if (_LikedPageJ == null) {_LikedPageJ = jQuery.Select("#" + clientId + "_LikedPage");}; return _LikedPageJ;}} private jQueryObject _LikedPageJ;
		public InputElement MixmagGreatestDjK {get {if (_MixmagGreatestDjK == null) {_MixmagGreatestDjK = (InputElement)Document.GetElementById(clientId + "_MixmagGreatestDjK");}; return _MixmagGreatestDjK;}} private InputElement _MixmagGreatestDjK;
		public jQueryObject MixmagGreatestDjKJ {get {if (_MixmagGreatestDjKJ == null) {_MixmagGreatestDjKJ = jQuery.Select("#" + clientId + "_MixmagGreatestDjK");}; return _MixmagGreatestDjKJ;}} private jQueryObject _MixmagGreatestDjKJ;
		public InputElement FacebookSource {get {if (_FacebookSource == null) {_FacebookSource = (InputElement)Document.GetElementById(clientId + "_FacebookSource");}; return _FacebookSource;}} private InputElement _FacebookSource;
		public jQueryObject FacebookSourceJ {get {if (_FacebookSourceJ == null) {_FacebookSourceJ = jQuery.Select("#" + clientId + "_FacebookSource");}; return _FacebookSourceJ;}} private jQueryObject _FacebookSourceJ;
		public InputElement SignedRequest {get {if (_SignedRequest == null) {_SignedRequest = (InputElement)Document.GetElementById(clientId + "_SignedRequest");}; return _SignedRequest;}} private InputElement _SignedRequest;
		public jQueryObject SignedRequestJ {get {if (_SignedRequestJ == null) {_SignedRequestJ = jQuery.Select("#" + clientId + "_SignedRequest");}; return _SignedRequestJ;}} private jQueryObject _SignedRequestJ;
		public InputElement DoneRefresh {get {if (_DoneRefresh == null) {_DoneRefresh = (InputElement)Document.GetElementById(clientId + "_DoneRefresh");}; return _DoneRefresh;}} private InputElement _DoneRefresh;
		public jQueryObject DoneRefreshJ {get {if (_DoneRefreshJ == null) {_DoneRefreshJ = jQuery.Select("#" + clientId + "_DoneRefresh");}; return _DoneRefreshJ;}} private jQueryObject _DoneRefreshJ;
		public InputElement SafariKludge {get {if (_SafariKludge == null) {_SafariKludge = (InputElement)Document.GetElementById(clientId + "_SafariKludge");}; return _SafariKludge;}} private InputElement _SafariKludge;
		public jQueryObject SafariKludgeJ {get {if (_SafariKludgeJ == null) {_SafariKludgeJ = jQuery.Select("#" + clientId + "_SafariKludge");}; return _SafariKludgeJ;}} private jQueryObject _SafariKludgeJ;
		public Element TestP {get {if (_TestP == null) {_TestP = (Element)Document.GetElementById(clientId + "_TestP");}; return _TestP;}} private Element _TestP;
		public jQueryObject TestPJ {get {if (_TestPJ == null) {_TestPJ = jQuery.Select("#" + clientId + "_TestP");}; return _TestPJ;}} private jQueryObject _TestPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element NominationsPanel {get {if (_NominationsPanel == null) {_NominationsPanel = (Element)Document.GetElementById(clientId + "_NominationsPanel");}; return _NominationsPanel;}} private Element _NominationsPanel;
		public jQueryObject NominationsPanelJ {get {if (_NominationsPanelJ == null) {_NominationsPanelJ = jQuery.Select("#" + clientId + "_NominationsPanel");}; return _NominationsPanelJ;}} private jQueryObject _NominationsPanelJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element NominationsLikeButtonHolder {get {if (_NominationsLikeButtonHolder == null) {_NominationsLikeButtonHolder = (Element)Document.GetElementById(clientId + "_NominationsLikeButtonHolder");}; return _NominationsLikeButtonHolder;}} private Element _NominationsLikeButtonHolder;
		public jQueryObject NominationsLikeButtonHolderJ {get {if (_NominationsLikeButtonHolderJ == null) {_NominationsLikeButtonHolderJ = jQuery.Select("#" + clientId + "_NominationsLikeButtonHolder");}; return _NominationsLikeButtonHolderJ;}} private jQueryObject _NominationsLikeButtonHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element NominationsHolder {get {if (_NominationsHolder == null) {_NominationsHolder = (Element)Document.GetElementById(clientId + "_NominationsHolder");}; return _NominationsHolder;}} private Element _NominationsHolder;
		public jQueryObject NominationsHolderJ {get {if (_NominationsHolderJ == null) {_NominationsHolderJ = jQuery.Select("#" + clientId + "_NominationsHolder");}; return _NominationsHolderJ;}} private jQueryObject _NominationsHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element NotRunningPanel {get {if (_NotRunningPanel == null) {_NotRunningPanel = (Element)Document.GetElementById(clientId + "_NotRunningPanel");}; return _NotRunningPanel;}} private Element _NotRunningPanel;
		public jQueryObject NotRunningPanelJ {get {if (_NotRunningPanelJ == null) {_NotRunningPanelJ = jQuery.Select("#" + clientId + "_NotRunningPanel");}; return _NotRunningPanelJ;}} private jQueryObject _NotRunningPanelJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element RunningPanel {get {if (_RunningPanel == null) {_RunningPanel = (Element)Document.GetElementById(clientId + "_RunningPanel");}; return _RunningPanel;}} private Element _RunningPanel;
		public jQueryObject RunningPanelJ {get {if (_RunningPanelJ == null) {_RunningPanelJ = jQuery.Select("#" + clientId + "_RunningPanel");}; return _RunningPanelJ;}} private jQueryObject _RunningPanelJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element PublicDjsHolder {get {if (_PublicDjsHolder == null) {_PublicDjsHolder = (Element)Document.GetElementById(clientId + "_PublicDjsHolder");}; return _PublicDjsHolder;}} private Element _PublicDjsHolder;
		public jQueryObject PublicDjsHolderJ {get {if (_PublicDjsHolderJ == null) {_PublicDjsHolderJ = jQuery.Select("#" + clientId + "_PublicDjsHolder");}; return _PublicDjsHolderJ;}} private jQueryObject _PublicDjsHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element VotePanel {get {if (_VotePanel == null) {_VotePanel = (Element)Document.GetElementById(clientId + "_VotePanel");}; return _VotePanel;}} private Element _VotePanel;
		public jQueryObject VotePanelJ {get {if (_VotePanelJ == null) {_VotePanelJ = jQuery.Select("#" + clientId + "_VotePanel");}; return _VotePanelJ;}} private jQueryObject _VotePanelJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public ImageElement VoteImg {get {if (_VoteImg == null) {_VoteImg = (ImageElement)Document.GetElementById(clientId + "_VoteImg");}; return _VoteImg;}} private ImageElement _VoteImg;
		public jQueryObject VoteImgJ {get {if (_VoteImgJ == null) {_VoteImgJ = jQuery.Select("#" + clientId + "_VoteImg");}; return _VoteImgJ;}} private jQueryObject _VoteImgJ;
		public Element VoteName {get {if (_VoteName == null) {_VoteName = (Element)Document.GetElementById(clientId + "_VoteName");}; return _VoteName;}} private Element _VoteName;
		public jQueryObject VoteNameJ {get {if (_VoteNameJ == null) {_VoteNameJ = jQuery.Select("#" + clientId + "_VoteName");}; return _VoteNameJ;}} private jQueryObject _VoteNameJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element VoteDescriptionP {get {if (_VoteDescriptionP == null) {_VoteDescriptionP = (Element)Document.GetElementById(clientId + "_VoteDescriptionP");}; return _VoteDescriptionP;}} private Element _VoteDescriptionP;
		public jQueryObject VoteDescriptionPJ {get {if (_VoteDescriptionPJ == null) {_VoteDescriptionPJ = jQuery.Select("#" + clientId + "_VoteDescriptionP");}; return _VoteDescriptionPJ;}} private jQueryObject _VoteDescriptionPJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element VoteLikeHolder {get {if (_VoteLikeHolder == null) {_VoteLikeHolder = (Element)Document.GetElementById(clientId + "_VoteLikeHolder");}; return _VoteLikeHolder;}} private Element _VoteLikeHolder;
		public jQueryObject VoteLikeHolderJ {get {if (_VoteLikeHolderJ == null) {_VoteLikeHolderJ = jQuery.Select("#" + clientId + "_VoteLikeHolder");}; return _VoteLikeHolderJ;}} private jQueryObject _VoteLikeHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element VoteFollowHolder {get {if (_VoteFollowHolder == null) {_VoteFollowHolder = (Element)Document.GetElementById(clientId + "_VoteFollowHolder");}; return _VoteFollowHolder;}} private Element _VoteFollowHolder;
		public jQueryObject VoteFollowHolderJ {get {if (_VoteFollowHolderJ == null) {_VoteFollowHolderJ = jQuery.Select("#" + clientId + "_VoteFollowHolder");}; return _VoteFollowHolderJ;}} private jQueryObject _VoteFollowHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element VoteFollowPrompt {get {if (_VoteFollowPrompt == null) {_VoteFollowPrompt = (Element)Document.GetElementById(clientId + "_VoteFollowPrompt");}; return _VoteFollowPrompt;}} private Element _VoteFollowPrompt;
		public jQueryObject VoteFollowPromptJ {get {if (_VoteFollowPromptJ == null) {_VoteFollowPromptJ = jQuery.Select("#" + clientId + "_VoteFollowPrompt");}; return _VoteFollowPromptJ;}} private jQueryObject _VoteFollowPromptJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement VoteFollowSkipLink {get {if (_VoteFollowSkipLink == null) {_VoteFollowSkipLink = (AnchorElement)Document.GetElementById(clientId + "_VoteFollowSkipLink");}; return _VoteFollowSkipLink;}} private AnchorElement _VoteFollowSkipLink;
		public jQueryObject VoteFollowSkipLinkJ {get {if (_VoteFollowSkipLinkJ == null) {_VoteFollowSkipLinkJ = jQuery.Select("#" + clientId + "_VoteFollowSkipLink");}; return _VoteFollowSkipLinkJ;}} private jQueryObject _VoteFollowSkipLinkJ;
		public InputElement VoteTwitterSkipButton {get {if (_VoteTwitterSkipButton == null) {_VoteTwitterSkipButton = (InputElement)Document.GetElementById(clientId + "_VoteTwitterSkipButton");}; return _VoteTwitterSkipButton;}} private InputElement _VoteTwitterSkipButton;
		public jQueryObject VoteTwitterSkipButtonJ {get {if (_VoteTwitterSkipButtonJ == null) {_VoteTwitterSkipButtonJ = jQuery.Select("#" + clientId + "_VoteTwitterSkipButton");}; return _VoteTwitterSkipButtonJ;}} private jQueryObject _VoteTwitterSkipButtonJ;
		public Element VoteTweetHolder {get {if (_VoteTweetHolder == null) {_VoteTweetHolder = (Element)Document.GetElementById(clientId + "_VoteTweetHolder");}; return _VoteTweetHolder;}} private Element _VoteTweetHolder;
		public jQueryObject VoteTweetHolderJ {get {if (_VoteTweetHolderJ == null) {_VoteTweetHolderJ = jQuery.Select("#" + clientId + "_VoteTweetHolder");}; return _VoteTweetHolderJ;}} private jQueryObject _VoteTweetHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element VoteTweetPrompt {get {if (_VoteTweetPrompt == null) {_VoteTweetPrompt = (Element)Document.GetElementById(clientId + "_VoteTweetPrompt");}; return _VoteTweetPrompt;}} private Element _VoteTweetPrompt;
		public jQueryObject VoteTweetPromptJ {get {if (_VoteTweetPromptJ == null) {_VoteTweetPromptJ = jQuery.Select("#" + clientId + "_VoteTweetPrompt");}; return _VoteTweetPromptJ;}} private jQueryObject _VoteTweetPromptJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public AnchorElement VoteTweetButton {get {if (_VoteTweetButton == null) {_VoteTweetButton = (AnchorElement)Document.GetElementById(clientId + "_VoteTweetButton");}; return _VoteTweetButton;}} private AnchorElement _VoteTweetButton;
		public jQueryObject VoteTweetButtonJ {get {if (_VoteTweetButtonJ == null) {_VoteTweetButtonJ = jQuery.Select("#" + clientId + "_VoteTweetButton");}; return _VoteTweetButtonJ;}} private jQueryObject _VoteTweetButtonJ;
		public AnchorElement VoteTweetSkipLink {get {if (_VoteTweetSkipLink == null) {_VoteTweetSkipLink = (AnchorElement)Document.GetElementById(clientId + "_VoteTweetSkipLink");}; return _VoteTweetSkipLink;}} private AnchorElement _VoteTweetSkipLink;
		public jQueryObject VoteTweetSkipLinkJ {get {if (_VoteTweetSkipLinkJ == null) {_VoteTweetSkipLinkJ = jQuery.Select("#" + clientId + "_VoteTweetSkipLink");}; return _VoteTweetSkipLinkJ;}} private jQueryObject _VoteTweetSkipLinkJ;
		public Element VoteButtonHolder {get {if (_VoteButtonHolder == null) {_VoteButtonHolder = (Element)Document.GetElementById(clientId + "_VoteButtonHolder");}; return _VoteButtonHolder;}} private Element _VoteButtonHolder;
		public jQueryObject VoteButtonHolderJ {get {if (_VoteButtonHolderJ == null) {_VoteButtonHolderJ = jQuery.Select("#" + clientId + "_VoteButtonHolder");}; return _VoteButtonHolderJ;}} private jQueryObject _VoteButtonHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element VoteButtonPrompt {get {if (_VoteButtonPrompt == null) {_VoteButtonPrompt = (Element)Document.GetElementById(clientId + "_VoteButtonPrompt");}; return _VoteButtonPrompt;}} private Element _VoteButtonPrompt;
		public jQueryObject VoteButtonPromptJ {get {if (_VoteButtonPromptJ == null) {_VoteButtonPromptJ = jQuery.Select("#" + clientId + "_VoteButtonPrompt");}; return _VoteButtonPromptJ;}} private jQueryObject _VoteButtonPromptJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement VoteButton {get {if (_VoteButton == null) {_VoteButton = (InputElement)Document.GetElementById(clientId + "_VoteButton");}; return _VoteButton;}} private InputElement _VoteButton;
		public jQueryObject VoteButtonJ {get {if (_VoteButtonJ == null) {_VoteButtonJ = jQuery.Select("#" + clientId + "_VoteButton");}; return _VoteButtonJ;}} private jQueryObject _VoteButtonJ;
		public CheckBoxElement VoteFacebookUpdateCheckbox1 {get {if (_VoteFacebookUpdateCheckbox1 == null) {_VoteFacebookUpdateCheckbox1 = (CheckBoxElement)Document.GetElementById(clientId + "_VoteFacebookUpdateCheckbox1");}; return _VoteFacebookUpdateCheckbox1;}} private CheckBoxElement _VoteFacebookUpdateCheckbox1;
		public jQueryObject VoteFacebookUpdateCheckbox1J {get {if (_VoteFacebookUpdateCheckbox1J == null) {_VoteFacebookUpdateCheckbox1J = jQuery.Select("#" + clientId + "_VoteFacebookUpdateCheckbox1");}; return _VoteFacebookUpdateCheckbox1J;}} private jQueryObject _VoteFacebookUpdateCheckbox1J;
		public Element VoteConfirmHolder {get {if (_VoteConfirmHolder == null) {_VoteConfirmHolder = (Element)Document.GetElementById(clientId + "_VoteConfirmHolder");}; return _VoteConfirmHolder;}} private Element _VoteConfirmHolder;
		public jQueryObject VoteConfirmHolderJ {get {if (_VoteConfirmHolderJ == null) {_VoteConfirmHolderJ = jQuery.Select("#" + clientId + "_VoteConfirmHolder");}; return _VoteConfirmHolderJ;}} private jQueryObject _VoteConfirmHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public ImageElement Confirm_Img {get {if (_Confirm_Img == null) {_Confirm_Img = (ImageElement)Document.GetElementById(clientId + "_Confirm_Img");}; return _Confirm_Img;}} private ImageElement _Confirm_Img;
		public jQueryObject Confirm_ImgJ {get {if (_Confirm_ImgJ == null) {_Confirm_ImgJ = jQuery.Select("#" + clientId + "_Confirm_Img");}; return _Confirm_ImgJ;}} private jQueryObject _Confirm_ImgJ;
		public AnchorElement Confirm_Link {get {if (_Confirm_Link == null) {_Confirm_Link = (AnchorElement)Document.GetElementById(clientId + "_Confirm_Link");}; return _Confirm_Link;}} private AnchorElement _Confirm_Link;
		public jQueryObject Confirm_LinkJ {get {if (_Confirm_LinkJ == null) {_Confirm_LinkJ = jQuery.Select("#" + clientId + "_Confirm_Link");}; return _Confirm_LinkJ;}} private jQueryObject _Confirm_LinkJ;
		public InputElement Confirm_YesButton {get {if (_Confirm_YesButton == null) {_Confirm_YesButton = (InputElement)Document.GetElementById(clientId + "_Confirm_YesButton");}; return _Confirm_YesButton;}} private InputElement _Confirm_YesButton;
		public jQueryObject Confirm_YesButtonJ {get {if (_Confirm_YesButtonJ == null) {_Confirm_YesButtonJ = jQuery.Select("#" + clientId + "_Confirm_YesButton");}; return _Confirm_YesButtonJ;}} private jQueryObject _Confirm_YesButtonJ;
		public InputElement Confirm_NoButton {get {if (_Confirm_NoButton == null) {_Confirm_NoButton = (InputElement)Document.GetElementById(clientId + "_Confirm_NoButton");}; return _Confirm_NoButton;}} private InputElement _Confirm_NoButton;
		public jQueryObject Confirm_NoButtonJ {get {if (_Confirm_NoButtonJ == null) {_Confirm_NoButtonJ = jQuery.Select("#" + clientId + "_Confirm_NoButton");}; return _Confirm_NoButtonJ;}} private jQueryObject _Confirm_NoButtonJ;
		public Element VoteLoggedOutHolder {get {if (_VoteLoggedOutHolder == null) {_VoteLoggedOutHolder = (Element)Document.GetElementById(clientId + "_VoteLoggedOutHolder");}; return _VoteLoggedOutHolder;}} private Element _VoteLoggedOutHolder;
		public jQueryObject VoteLoggedOutHolderJ {get {if (_VoteLoggedOutHolderJ == null) {_VoteLoggedOutHolderJ = jQuery.Select("#" + clientId + "_VoteLoggedOutHolder");}; return _VoteLoggedOutHolderJ;}} private jQueryObject _VoteLoggedOutHolderJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public InputElement LoggedOutButton {get {if (_LoggedOutButton == null) {_LoggedOutButton = (InputElement)Document.GetElementById(clientId + "_LoggedOutButton");}; return _LoggedOutButton;}} private InputElement _LoggedOutButton;
		public jQueryObject LoggedOutButtonJ {get {if (_LoggedOutButtonJ == null) {_LoggedOutButtonJ = jQuery.Select("#" + clientId + "_LoggedOutButton");}; return _LoggedOutButtonJ;}} private jQueryObject _LoggedOutButtonJ;
		public Element VoteVideo1 {get {if (_VoteVideo1 == null) {_VoteVideo1 = (Element)Document.GetElementById(clientId + "_VoteVideo1");}; return _VoteVideo1;}} private Element _VoteVideo1;
		public jQueryObject VoteVideo1J {get {if (_VoteVideo1J == null) {_VoteVideo1J = jQuery.Select("#" + clientId + "_VoteVideo1");}; return _VoteVideo1J;}} private jQueryObject _VoteVideo1J;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element VoteVideo2 {get {if (_VoteVideo2 == null) {_VoteVideo2 = (Element)Document.GetElementById(clientId + "_VoteVideo2");}; return _VoteVideo2;}} private Element _VoteVideo2;
		public jQueryObject VoteVideo2J {get {if (_VoteVideo2J == null) {_VoteVideo2J = jQuery.Select("#" + clientId + "_VoteVideo2");}; return _VoteVideo2J;}} private jQueryObject _VoteVideo2J;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element FacebookComments {get {if (_FacebookComments == null) {_FacebookComments = (Element)Document.GetElementById(clientId + "_FacebookComments");}; return _FacebookComments;}} private Element _FacebookComments;
		public jQueryObject FacebookCommentsJ {get {if (_FacebookCommentsJ == null) {_FacebookCommentsJ = jQuery.Select("#" + clientId + "_FacebookComments");}; return _FacebookCommentsJ;}} private jQueryObject _FacebookCommentsJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public DivElement VoteCompletePanel {get {if (_VoteCompletePanel == null) {_VoteCompletePanel = (DivElement)Document.GetElementById(clientId + "_VoteCompletePanel");}; return _VoteCompletePanel;}} private DivElement _VoteCompletePanel;
		public jQueryObject VoteCompletePanelJ {get {if (_VoteCompletePanelJ == null) {_VoteCompletePanelJ = jQuery.Select("#" + clientId + "_VoteCompletePanel");}; return _VoteCompletePanelJ;}} private jQueryObject _VoteCompletePanelJ;
		public Element FacebookComments2 {get {if (_FacebookComments2 == null) {_FacebookComments2 = (Element)Document.GetElementById(clientId + "_FacebookComments2");}; return _FacebookComments2;}} private Element _FacebookComments2;
		public jQueryObject FacebookComments2J {get {if (_FacebookComments2J == null) {_FacebookComments2J = jQuery.Select("#" + clientId + "_FacebookComments2");}; return _FacebookComments2J;}} private jQueryObject _FacebookComments2J;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element DebugOutput {get {if (_DebugOutput == null) {_DebugOutput = (Element)Document.GetElementById(clientId + "_DebugOutput");}; return _DebugOutput;}} private Element _DebugOutput;
		public jQueryObject DebugOutputJ {get {if (_DebugOutputJ == null) {_DebugOutputJ = jQuery.Select("#" + clientId + "_DebugOutput");}; return _DebugOutputJ;}} private jQueryObject _DebugOutputJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element LoadingLabel {get {if (_LoadingLabel == null) {_LoadingLabel = (Element)Document.GetElementById(clientId + "_LoadingLabel");}; return _LoadingLabel;}} private Element _LoadingLabel;
		public jQueryObject LoadingLabelJ {get {if (_LoadingLabelJ == null) {_LoadingLabelJ = jQuery.Select("#" + clientId + "_LoadingLabel");}; return _LoadingLabelJ;}} private jQueryObject _LoadingLabelJ;//mappings.Add("System.Web.UI.HtmlControls.HtmlGenericControl", ElementGetter("Element"));
		public Element GenericContainerPage {get {if (_GenericContainerPage == null) {_GenericContainerPage = (Element)Document.GetElementById(clientId + "_GenericContainerPage");}; return _GenericContainerPage;}} private Element _GenericContainerPage;
		public jQueryObject GenericContainerPageJ {get {if (_GenericContainerPageJ == null) {_GenericContainerPageJ = jQuery.Select("#" + clientId + "_GenericContainerPage");}; return _GenericContainerPageJ;}} private jQueryObject _GenericContainerPageJ;//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
	}
}
