
DELETE FROM MusicType
TRUNCATE TABLE MusicType
SET IDENTITY_INSERT MusicType ON

INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(1,'All Music',0,'All Music',1.0,'all','all-music',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(2,'Commercial Pop',42,'Commercial Pop',2.10,'com','pop',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(3,'Commercial Dance',42,'Commercial Dance',2.20,'com','chart-dance',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(4,'All House',1,'House',3.0,'house','house','funky house, soulful house, deep house etc...')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(5,'US House',4,'US House',3.40,'house','us-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(6,'Progressive House',4,'Progressive House',3.50,'house','prog-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(7,'Deep House',4,'Deep House',3.30,'house','deep-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(8,'Tech House',4,'Tech House',3.60,'house','tech-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(9,'Funky House',4,'Funky House',3.10,'house','funky-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(10,'All Hard Dance',1,'Hard Dance',4.0,'hard','hard-dance','hard house, trance, hardcore etc...')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(11,'Hard House',10,'Hard House',4.10,'hard','hard-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(12,'Trance',10,'Trance',4.20,'hard','trance',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(13,'Psy-Trance',10,'Psy-Trance',4.30,'hard','psy-trance',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(14,'Hardcore',10,'Hardcore',4.40,'hard','h/core',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(15,'All Alternative Dance',1,'Alternative Dance',5.0,'breaks','breaks','breaks, electro, big beat etc...')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(16,'Electro',15,'Electro',5.10,'breaks','electro',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(17,'Big Beat',15,'Big Beat',5.20,'breaks','big-beat',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(18,'Breaks',15,'Breaks',5.30,'breaks','breaks',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(20,'All Techno',1,'Techno',6.0,'techno','techno','electro techno, detroit techno etc...')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(21,'Detroit Techno',20,'Detroit Techno',6.10,'techno','detroit',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(22,'Acid Techno',20,'Acid Techno',6.20,'techno','acid',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(23,'Electro Techno',20,'Electro Techno',6.30,'techno','elec-techno',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(24,'All Drum and Bass',1,'Drum and Bass',7.0,'bass','drum-n-bass','drum''n''bass, jungle etc.')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(25,'Jazzy Drum and Bass',24,'Jazzy Drum and Bass',7.10,'bass','jazzy dnb',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(26,'Jump Up Drum and Bass',24,'Jump Up Drum and Bass',7.20,'bass','jump-up dnb',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(27,'Jungle',24,'Jungle',7.30,'bass','jungle',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(28,'All Urban',1,'Urban',8.0,'urban','urban','hip-hop, R&B, garage etc...')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(29,'Hip Hop',28,'Hip Hop',8.10,'urban','hip-hop',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(30,'R&B',28,'R&B',8.2,'urban','r&b',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(31,'Dancehall / Bashment',28,'Dancehall / Bashment',8.30,'urban','dancehall',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(32,'Reggae',28,'Reggae',8.40,'urban','reggae',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(33,'UK Garage',28,'UK Garage',8.50,'urban','uk-garage',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(34,'US Garage',4,'US Garage',3.450,'house','us-garage',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(35,'Chillout / Leftfield',1,'Chillout / Leftfield',1.00,'chill','chillout',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(36,'All Rock',1,'Rock',1.10,'rock','rock','indie, rock, metal etc...')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(37,'Indie',36,'Indie',1.11,'rock','indie',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(38,'Rock',36,'Rock',1.12,'rock','rock',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(39,'Metal',36,'Metal',1.13,'rock','metal',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(40,'Tribal House',4,'Tribal House',3.70,'house','tribal-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(41,'Soulful House',4,'Soulful House',3.20,'house','soulful-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(42,'All Commercial',1,'Commercial',2.0,'com','commercial','pop, chart dance, club classics etc...')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(43,'Club Classics',42,'Club Classics',2.30,'com','club-classics',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(44,'Old Skool House',4,'Old Skool House',3.80,'house','o/skool-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(45,'Old Skool Hardcore',10,'Old Skool Hardcore',4.50,'hard','o/skool-h/core',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(46,'All Retro',1,'Retro',9.0,'retro','retro','disco, soul, jazz, funk etc...')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(47,'Funk',46,'Funk',9.10,'retro','funk',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(48,'Disco',46,'Disco',9.2,'retro','disco',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(49,'Jazz-Funk',46,'Jazz-Funk',9.30,'retro','jazzfunk',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(50,'Soul',46,'Soul',9.40,'retro','soul',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(51,'Jazz',46,'Jazz',9.50,'retro','jazz',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(52,'Rare Groove',46,'Rare Groove',9.60,'retro','raregroove',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(54,'Acid House',4,'Acid House',3.850,'house','acid-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(55,'Electro House',4,'Electro House',3.1750,'house','electro-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(56,'Jackin House',4,'Jackin House',3.150,'house','jackin-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(57,'Dirty House',4,'Dirty House',3.180,'house','dirty-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(58,'Latin House',4,'Latin House',3.190,'house','latin-house',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(59,'Hardstyle',10,'Hardstyle',4.150,'hard','hardstyle',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(60,'Hard Trance',10,'Hard Trance',4.160,'hard','hard-trance',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(61,'Minimal Techno',20,'Minimal Techno',6.050,'techno','minimal-techno',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(62,'Funky Techno',20,'Funky Techno',6.150,'techno','funky-techno',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(63,'Punk',36,'Punk',1.140,'rock','punk',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(64,'Acoustic',36,'Acoustic',1.150,'rock','acoustic',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(65,'All Alternative Electronic',1,'Alternative Electronic',8.910,'alt','alt-electronic','industrial, ebm, powernoise etc.')
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(66,'Industrial',65,'Industrial',8.920,'alt','industrial',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(67,'Electronic Body Music',65,'Electronic Body Music',8.930,'alt','ebm',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(68,'Futurepop',65,'Futurepop',8.940,'alt','futurepop',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(69,'Powernoise',65,'Powernoise',8.95,'alt','powernoise',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(70,'Liquid Drum and Bass',24,'Liquid Drum and Bass',7.050,'bass','liquid-dnb',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(71,'Dubstep',28,'Dubstep',8.60,'urban','dubstep',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(72,'Reggaeton',28,'Reggaeton',8.7,'urban','reggaeton',NULL)
INSERT [dbo].[MusicType] ([K],[Name],[ParentK],[GenericName],[Order],[SmsCode],[SmsName],[Description])VALUES(73,'Bassline House',4,'Bassline House',3.860,'house','bassline-house',NULL)

SET IDENTITY_INSERT MusicType OFF
