//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.ObjectDataSource", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.CustomValidator", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.RangeValidator", ElementGetter("Element"));
//mappings.Add("Spotted.Controls.AddOnlyTextBox", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
//mappings.Add("System.Web.UI.WebControls.Button", ElementGetter("Element"));
//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
using System;
using System.Collections.Generic;
using System.Html;
using jQueryApi;
using Js.Library;

namespace Js.Admin.InsertionOrderScreen
{
	public partial class View
		 : Js.AdminUserControl.View
	{
		public string clientId;
		public View(string clientId)
			 : base(clientId)
		{
			this.clientId = clientId;
		}
		public Element H1 {get {if (_H1 == null) {_H1 = (Element)Document.GetElementById(clientId + "_H1");}; return _H1;}} private Element _H1;
		public jQueryObject H1J {get {if (_H1J == null) {_H1J = jQuery.Select("#" + clientId + "_H1");}; return _H1J;}} private jQueryObject _H1J;//mappings.Add("Spotted.CustomControls.h1", ElementGetter("Element"));
		public Element ObjectDataSource1 {get {if (_ObjectDataSource1 == null) {_ObjectDataSource1 = (Element)Document.GetElementById(clientId + "_ObjectDataSource1");}; return _ObjectDataSource1;}} private Element _ObjectDataSource1;
		public jQueryObject ObjectDataSource1J {get {if (_ObjectDataSource1J == null) {_ObjectDataSource1J = jQuery.Select("#" + clientId + "_ObjectDataSource1");}; return _ObjectDataSource1J;}} private jQueryObject _ObjectDataSource1J;//mappings.Add("System.Web.UI.WebControls.ObjectDataSource", ElementGetter("Element"));
		public DivElement MainPanel {get {if (_MainPanel == null) {_MainPanel = (DivElement)Document.GetElementById(clientId + "_MainPanel");}; return _MainPanel;}} private DivElement _MainPanel;
		public jQueryObject MainPanelJ {get {if (_MainPanelJ == null) {_MainPanelJ = jQuery.Select("#" + clientId + "_MainPanel");}; return _MainPanelJ;}} private jQueryObject _MainPanelJ;
		public Element uiInsertionOrderKLabel {get {if (_uiInsertionOrderKLabel == null) {_uiInsertionOrderKLabel = (Element)Document.GetElementById(clientId + "_uiInsertionOrderKLabel");}; return _uiInsertionOrderKLabel;}} private Element _uiInsertionOrderKLabel;
		public jQueryObject uiInsertionOrderKLabelJ {get {if (_uiInsertionOrderKLabelJ == null) {_uiInsertionOrderKLabelJ = jQuery.Select("#" + clientId + "_uiInsertionOrderKLabel");}; return _uiInsertionOrderKLabelJ;}} private jQueryObject _uiInsertionOrderKLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiInsertionOrderK {get {if (_uiInsertionOrderK == null) {_uiInsertionOrderK = (Element)Document.GetElementById(clientId + "_uiInsertionOrderK");}; return _uiInsertionOrderK;}} private Element _uiInsertionOrderK;
		public jQueryObject uiInsertionOrderKJ {get {if (_uiInsertionOrderKJ == null) {_uiInsertionOrderKJ = jQuery.Select("#" + clientId + "_uiInsertionOrderK");}; return _uiInsertionOrderKJ;}} private jQueryObject _uiInsertionOrderKJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiCreatedDateLabel {get {if (_uiCreatedDateLabel == null) {_uiCreatedDateLabel = (Element)Document.GetElementById(clientId + "_uiCreatedDateLabel");}; return _uiCreatedDateLabel;}} private Element _uiCreatedDateLabel;
		public jQueryObject uiCreatedDateLabelJ {get {if (_uiCreatedDateLabelJ == null) {_uiCreatedDateLabelJ = jQuery.Select("#" + clientId + "_uiCreatedDateLabel");}; return _uiCreatedDateLabelJ;}} private jQueryObject _uiCreatedDateLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiCreatedDate {get {if (_uiCreatedDate == null) {_uiCreatedDate = (Element)Document.GetElementById(clientId + "_uiCreatedDate");}; return _uiCreatedDate;}} private Element _uiCreatedDate;
		public jQueryObject uiCreatedDateJ {get {if (_uiCreatedDateJ == null) {_uiCreatedDateJ = jQuery.Select("#" + clientId + "_uiCreatedDate");}; return _uiCreatedDateJ;}} private jQueryObject _uiCreatedDateJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiCampaignNameLabel {get {if (_uiCampaignNameLabel == null) {_uiCampaignNameLabel = (Element)Document.GetElementById(clientId + "_uiCampaignNameLabel");}; return _uiCampaignNameLabel;}} private Element _uiCampaignNameLabel;
		public jQueryObject uiCampaignNameLabelJ {get {if (_uiCampaignNameLabelJ == null) {_uiCampaignNameLabelJ = jQuery.Select("#" + clientId + "_uiCampaignNameLabel");}; return _uiCampaignNameLabelJ;}} private jQueryObject _uiCampaignNameLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public InputElement uiCampaignName {get {if (_uiCampaignName == null) {_uiCampaignName = (InputElement)Document.GetElementById(clientId + "_uiCampaignName");}; return _uiCampaignName;}} private InputElement _uiCampaignName;
		public jQueryObject uiCampaignNameJ {get {if (_uiCampaignNameJ == null) {_uiCampaignNameJ = jQuery.Select("#" + clientId + "_uiCampaignName");}; return _uiCampaignNameJ;}} private jQueryObject _uiCampaignNameJ;
		public Element PromoterLabel {get {if (_PromoterLabel == null) {_PromoterLabel = (Element)Document.GetElementById(clientId + "_PromoterLabel");}; return _PromoterLabel;}} private Element _PromoterLabel;
		public jQueryObject PromoterLabelJ {get {if (_PromoterLabelJ == null) {_PromoterLabelJ = jQuery.Select("#" + clientId + "_PromoterLabel");}; return _PromoterLabelJ;}} private jQueryObject _PromoterLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Js.ClientControls.HtmlAutoCompleteBehaviour uiPromoterAutoComplete {get {return (Js.ClientControls.HtmlAutoCompleteBehaviour) Script.Eval(clientId + "_uiPromoterAutoCompleteBehaviour");}}
		public Element uiCampaignStartLabel {get {if (_uiCampaignStartLabel == null) {_uiCampaignStartLabel = (Element)Document.GetElementById(clientId + "_uiCampaignStartLabel");}; return _uiCampaignStartLabel;}} private Element _uiCampaignStartLabel;
		public jQueryObject uiCampaignStartLabelJ {get {if (_uiCampaignStartLabelJ == null) {_uiCampaignStartLabelJ = jQuery.Select("#" + clientId + "_uiCampaignStartLabel");}; return _uiCampaignStartLabelJ;}} private jQueryObject _uiCampaignStartLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Js.CustomControls.Cal.Controller uiCampaignStartCal {get {return (Js.CustomControls.Cal.Controller) Script.Eval(clientId + "_uiCampaignStartCalController");}}
		public Element UserLabel0 {get {if (_UserLabel0 == null) {_UserLabel0 = (Element)Document.GetElementById(clientId + "_UserLabel0");}; return _UserLabel0;}} private Element _UserLabel0;
		public jQueryObject UserLabel0J {get {if (_UserLabel0J == null) {_UserLabel0J = jQuery.Select("#" + clientId + "_UserLabel0");}; return _UserLabel0J;}} private jQueryObject _UserLabel0J;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public SelectElement uiUserDropDownList {get {if (_uiUserDropDownList == null) {_uiUserDropDownList = (SelectElement)Document.GetElementById(clientId + "_uiUserDropDownList");}; return _uiUserDropDownList;}} private SelectElement _uiUserDropDownList;
		public jQueryObject uiUserDropDownListJ {get {if (_uiUserDropDownListJ == null) {_uiUserDropDownListJ = jQuery.Select("#" + clientId + "_uiUserDropDownList");}; return _uiUserDropDownListJ;}} private jQueryObject _uiUserDropDownListJ;
		public InputElement uiUsrNameOverride {get {if (_uiUsrNameOverride == null) {_uiUsrNameOverride = (InputElement)Document.GetElementById(clientId + "_uiUsrNameOverride");}; return _uiUsrNameOverride;}} private InputElement _uiUsrNameOverride;
		public jQueryObject uiUsrNameOverrideJ {get {if (_uiUsrNameOverrideJ == null) {_uiUsrNameOverrideJ = jQuery.Select("#" + clientId + "_uiUsrNameOverride");}; return _uiUsrNameOverrideJ;}} private jQueryObject _uiUsrNameOverrideJ;
		public Element uiUsrValidator {get {if (_uiUsrValidator == null) {_uiUsrValidator = (Element)Document.GetElementById(clientId + "_uiUsrValidator");}; return _uiUsrValidator;}} private Element _uiUsrValidator;
		public jQueryObject uiUsrValidatorJ {get {if (_uiUsrValidatorJ == null) {_uiUsrValidatorJ = jQuery.Select("#" + clientId + "_uiUsrValidator");}; return _uiUsrValidatorJ;}} private jQueryObject _uiUsrValidatorJ;//mappings.Add("System.Web.UI.WebControls.CustomValidator", ElementGetter("Element"));
		public Element uiCampaignEndLabel {get {if (_uiCampaignEndLabel == null) {_uiCampaignEndLabel = (Element)Document.GetElementById(clientId + "_uiCampaignEndLabel");}; return _uiCampaignEndLabel;}} private Element _uiCampaignEndLabel;
		public jQueryObject uiCampaignEndLabelJ {get {if (_uiCampaignEndLabelJ == null) {_uiCampaignEndLabelJ = jQuery.Select("#" + clientId + "_uiCampaignEndLabel");}; return _uiCampaignEndLabelJ;}} private jQueryObject _uiCampaignEndLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Js.CustomControls.Cal.Controller uiCampaignEndCal {get {return (Js.CustomControls.Cal.Controller) Script.Eval(clientId + "_uiCampaignEndCalController");}}
		public Element uiCampaignEndDateAfterStartValidator {get {if (_uiCampaignEndDateAfterStartValidator == null) {_uiCampaignEndDateAfterStartValidator = (Element)Document.GetElementById(clientId + "_uiCampaignEndDateAfterStartValidator");}; return _uiCampaignEndDateAfterStartValidator;}} private Element _uiCampaignEndDateAfterStartValidator;
		public jQueryObject uiCampaignEndDateAfterStartValidatorJ {get {if (_uiCampaignEndDateAfterStartValidatorJ == null) {_uiCampaignEndDateAfterStartValidatorJ = jQuery.Select("#" + clientId + "_uiCampaignEndDateAfterStartValidator");}; return _uiCampaignEndDateAfterStartValidatorJ;}} private jQueryObject _uiCampaignEndDateAfterStartValidatorJ;//mappings.Add("System.Web.UI.WebControls.CustomValidator", ElementGetter("Element"));
		public Element uiActionUsrLabel {get {if (_uiActionUsrLabel == null) {_uiActionUsrLabel = (Element)Document.GetElementById(clientId + "_uiActionUsrLabel");}; return _uiActionUsrLabel;}} private Element _uiActionUsrLabel;
		public jQueryObject uiActionUsrLabelJ {get {if (_uiActionUsrLabelJ == null) {_uiActionUsrLabelJ = jQuery.Select("#" + clientId + "_uiActionUsrLabel");}; return _uiActionUsrLabelJ;}} private jQueryObject _uiActionUsrLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Js.ClientControls.HtmlAutoCompleteBehaviour uiActionUserAutoComplete {get {return (Js.ClientControls.HtmlAutoCompleteBehaviour) Script.Eval(clientId + "_uiActionUserAutoCompleteBehaviour");}}
		public Element uiActionUsrValidator {get {if (_uiActionUsrValidator == null) {_uiActionUsrValidator = (Element)Document.GetElementById(clientId + "_uiActionUsrValidator");}; return _uiActionUsrValidator;}} private Element _uiActionUsrValidator;
		public jQueryObject uiActionUsrValidatorJ {get {if (_uiActionUsrValidatorJ == null) {_uiActionUsrValidatorJ = jQuery.Select("#" + clientId + "_uiActionUsrValidator");}; return _uiActionUsrValidatorJ;}} private jQueryObject _uiActionUsrValidatorJ;//mappings.Add("System.Web.UI.WebControls.CustomValidator", ElementGetter("Element"));
		public Element uiNextInvoiceDueLabel {get {if (_uiNextInvoiceDueLabel == null) {_uiNextInvoiceDueLabel = (Element)Document.GetElementById(clientId + "_uiNextInvoiceDueLabel");}; return _uiNextInvoiceDueLabel;}} private Element _uiNextInvoiceDueLabel;
		public jQueryObject uiNextInvoiceDueLabelJ {get {if (_uiNextInvoiceDueLabelJ == null) {_uiNextInvoiceDueLabelJ = jQuery.Select("#" + clientId + "_uiNextInvoiceDueLabel");}; return _uiNextInvoiceDueLabelJ;}} private jQueryObject _uiNextInvoiceDueLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Js.CustomControls.Cal.Controller uiNextInvoiceDue {get {return (Js.CustomControls.Cal.Controller) Script.Eval(clientId + "_uiNextInvoiceDueController");}}
		public Element uiAgencyDiscountLabel {get {if (_uiAgencyDiscountLabel == null) {_uiAgencyDiscountLabel = (Element)Document.GetElementById(clientId + "_uiAgencyDiscountLabel");}; return _uiAgencyDiscountLabel;}} private Element _uiAgencyDiscountLabel;
		public jQueryObject uiAgencyDiscountLabelJ {get {if (_uiAgencyDiscountLabelJ == null) {_uiAgencyDiscountLabelJ = jQuery.Select("#" + clientId + "_uiAgencyDiscountLabel");}; return _uiAgencyDiscountLabelJ;}} private jQueryObject _uiAgencyDiscountLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public InputElement uiAgencyDiscount {get {if (_uiAgencyDiscount == null) {_uiAgencyDiscount = (InputElement)Document.GetElementById(clientId + "_uiAgencyDiscount");}; return _uiAgencyDiscount;}} private InputElement _uiAgencyDiscount;
		public jQueryObject uiAgencyDiscountJ {get {if (_uiAgencyDiscountJ == null) {_uiAgencyDiscountJ = jQuery.Select("#" + clientId + "_uiAgencyDiscount");}; return _uiAgencyDiscountJ;}} private jQueryObject _uiAgencyDiscountJ;
		public Element uiAgencyDiscountRangeValidator0 {get {if (_uiAgencyDiscountRangeValidator0 == null) {_uiAgencyDiscountRangeValidator0 = (Element)Document.GetElementById(clientId + "_uiAgencyDiscountRangeValidator0");}; return _uiAgencyDiscountRangeValidator0;}} private Element _uiAgencyDiscountRangeValidator0;
		public jQueryObject uiAgencyDiscountRangeValidator0J {get {if (_uiAgencyDiscountRangeValidator0J == null) {_uiAgencyDiscountRangeValidator0J = jQuery.Select("#" + clientId + "_uiAgencyDiscountRangeValidator0");}; return _uiAgencyDiscountRangeValidator0J;}} private jQueryObject _uiAgencyDiscountRangeValidator0J;//mappings.Add("System.Web.UI.WebControls.RangeValidator", ElementGetter("Element"));
		public Element uiAgencyDiscountRangeValidator1 {get {if (_uiAgencyDiscountRangeValidator1 == null) {_uiAgencyDiscountRangeValidator1 = (Element)Document.GetElementById(clientId + "_uiAgencyDiscountRangeValidator1");}; return _uiAgencyDiscountRangeValidator1;}} private Element _uiAgencyDiscountRangeValidator1;
		public jQueryObject uiAgencyDiscountRangeValidator1J {get {if (_uiAgencyDiscountRangeValidator1J == null) {_uiAgencyDiscountRangeValidator1J = jQuery.Select("#" + clientId + "_uiAgencyDiscountRangeValidator1");}; return _uiAgencyDiscountRangeValidator1J;}} private jQueryObject _uiAgencyDiscountRangeValidator1J;//mappings.Add("System.Web.UI.WebControls.RangeValidator", ElementGetter("Element"));
		public Element uiAgencyDiscountRangeValidator2 {get {if (_uiAgencyDiscountRangeValidator2 == null) {_uiAgencyDiscountRangeValidator2 = (Element)Document.GetElementById(clientId + "_uiAgencyDiscountRangeValidator2");}; return _uiAgencyDiscountRangeValidator2;}} private Element _uiAgencyDiscountRangeValidator2;
		public jQueryObject uiAgencyDiscountRangeValidator2J {get {if (_uiAgencyDiscountRangeValidator2J == null) {_uiAgencyDiscountRangeValidator2J = jQuery.Select("#" + clientId + "_uiAgencyDiscountRangeValidator2");}; return _uiAgencyDiscountRangeValidator2J;}} private jQueryObject _uiAgencyDiscountRangeValidator2J;//mappings.Add("System.Web.UI.WebControls.RangeValidator", ElementGetter("Element"));
		public Element uiCustomerRefLabel0 {get {if (_uiCustomerRefLabel0 == null) {_uiCustomerRefLabel0 = (Element)Document.GetElementById(clientId + "_uiCustomerRefLabel0");}; return _uiCustomerRefLabel0;}} private Element _uiCustomerRefLabel0;
		public jQueryObject uiCustomerRefLabel0J {get {if (_uiCustomerRefLabel0J == null) {_uiCustomerRefLabel0J = jQuery.Select("#" + clientId + "_uiCustomerRefLabel0");}; return _uiCustomerRefLabel0J;}} private jQueryObject _uiCustomerRefLabel0J;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public InputElement uiCustomerRef {get {if (_uiCustomerRef == null) {_uiCustomerRef = (InputElement)Document.GetElementById(clientId + "_uiCustomerRef");}; return _uiCustomerRef;}} private InputElement _uiCustomerRef;
		public jQueryObject uiCustomerRefJ {get {if (_uiCustomerRefJ == null) {_uiCustomerRefJ = jQuery.Select("#" + clientId + "_uiCustomerRef");}; return _uiCustomerRefJ;}} private jQueryObject _uiCustomerRefJ;
		public Element uiPaymentTermsLabel {get {if (_uiPaymentTermsLabel == null) {_uiPaymentTermsLabel = (Element)Document.GetElementById(clientId + "_uiPaymentTermsLabel");}; return _uiPaymentTermsLabel;}} private Element _uiPaymentTermsLabel;
		public jQueryObject uiPaymentTermsLabelJ {get {if (_uiPaymentTermsLabelJ == null) {_uiPaymentTermsLabelJ = jQuery.Select("#" + clientId + "_uiPaymentTermsLabel");}; return _uiPaymentTermsLabelJ;}} private jQueryObject _uiPaymentTermsLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public InputElement uiPaymentTerms {get {if (_uiPaymentTerms == null) {_uiPaymentTerms = (InputElement)Document.GetElementById(clientId + "_uiPaymentTerms");}; return _uiPaymentTerms;}} private InputElement _uiPaymentTerms;
		public jQueryObject uiPaymentTermsJ {get {if (_uiPaymentTermsJ == null) {_uiPaymentTermsJ = jQuery.Select("#" + clientId + "_uiPaymentTerms");}; return _uiPaymentTermsJ;}} private jQueryObject _uiPaymentTermsJ;
		public Element uiInvoicePeriodLabel {get {if (_uiInvoicePeriodLabel == null) {_uiInvoicePeriodLabel = (Element)Document.GetElementById(clientId + "_uiInvoicePeriodLabel");}; return _uiInvoicePeriodLabel;}} private Element _uiInvoicePeriodLabel;
		public jQueryObject uiInvoicePeriodLabelJ {get {if (_uiInvoicePeriodLabelJ == null) {_uiInvoicePeriodLabelJ = jQuery.Select("#" + clientId + "_uiInvoicePeriodLabel");}; return _uiInvoicePeriodLabelJ;}} private jQueryObject _uiInvoicePeriodLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public InputElement uiInvoicePeriod {get {if (_uiInvoicePeriod == null) {_uiInvoicePeriod = (InputElement)Document.GetElementById(clientId + "_uiInvoicePeriod");}; return _uiInvoicePeriod;}} private InputElement _uiInvoicePeriod;
		public jQueryObject uiInvoicePeriodJ {get {if (_uiInvoicePeriodJ == null) {_uiInvoicePeriodJ = jQuery.Select("#" + clientId + "_uiInvoicePeriod");}; return _uiInvoicePeriodJ;}} private jQueryObject _uiInvoicePeriodJ;
		public Element uiCampaignCreditsLabel {get {if (_uiCampaignCreditsLabel == null) {_uiCampaignCreditsLabel = (Element)Document.GetElementById(clientId + "_uiCampaignCreditsLabel");}; return _uiCampaignCreditsLabel;}} private Element _uiCampaignCreditsLabel;
		public jQueryObject uiCampaignCreditsLabelJ {get {if (_uiCampaignCreditsLabelJ == null) {_uiCampaignCreditsLabelJ = jQuery.Select("#" + clientId + "_uiCampaignCreditsLabel");}; return _uiCampaignCreditsLabelJ;}} private jQueryObject _uiCampaignCreditsLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiCampaignCredits {get {if (_uiCampaignCredits == null) {_uiCampaignCredits = (Element)Document.GetElementById(clientId + "_uiCampaignCredits");}; return _uiCampaignCredits;}} private Element _uiCampaignCredits;
		public jQueryObject uiCampaignCreditsJ {get {if (_uiCampaignCreditsJ == null) {_uiCampaignCreditsJ = jQuery.Select("#" + clientId + "_uiCampaignCredits");}; return _uiCampaignCreditsJ;}} private jQueryObject _uiCampaignCreditsJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public CheckBoxElement uiCampaignCreditsOverrideCheckBox {get {if (_uiCampaignCreditsOverrideCheckBox == null) {_uiCampaignCreditsOverrideCheckBox = (CheckBoxElement)Document.GetElementById(clientId + "_uiCampaignCreditsOverrideCheckBox");}; return _uiCampaignCreditsOverrideCheckBox;}} private CheckBoxElement _uiCampaignCreditsOverrideCheckBox;
		public jQueryObject uiCampaignCreditsOverrideCheckBoxJ {get {if (_uiCampaignCreditsOverrideCheckBoxJ == null) {_uiCampaignCreditsOverrideCheckBoxJ = jQuery.Select("#" + clientId + "_uiCampaignCreditsOverrideCheckBox");}; return _uiCampaignCreditsOverrideCheckBoxJ;}} private jQueryObject _uiCampaignCreditsOverrideCheckBoxJ;
		public InputElement uiCampaignCreditsOverride {get {if (_uiCampaignCreditsOverride == null) {_uiCampaignCreditsOverride = (InputElement)Document.GetElementById(clientId + "_uiCampaignCreditsOverride");}; return _uiCampaignCreditsOverride;}} private InputElement _uiCampaignCreditsOverride;
		public jQueryObject uiCampaignCreditsOverrideJ {get {if (_uiCampaignCreditsOverrideJ == null) {_uiCampaignCreditsOverrideJ = jQuery.Select("#" + clientId + "_uiCampaignCreditsOverride");}; return _uiCampaignCreditsOverrideJ;}} private jQueryObject _uiCampaignCreditsOverrideJ;
		public Element NotesLabel {get {if (_NotesLabel == null) {_NotesLabel = (Element)Document.GetElementById(clientId + "_NotesLabel");}; return _NotesLabel;}} private Element _NotesLabel;
		public jQueryObject NotesLabelJ {get {if (_NotesLabelJ == null) {_NotesLabelJ = jQuery.Select("#" + clientId + "_NotesLabel");}; return _NotesLabelJ;}} private jQueryObject _NotesLabelJ;//mappings.Add("System.Web.UI.WebControls.Label", ElementGetter("Element"));
		public Element uiNotesAddOnlyTextBox {get {if (_uiNotesAddOnlyTextBox == null) {_uiNotesAddOnlyTextBox = (Element)Document.GetElementById(clientId + "_uiNotesAddOnlyTextBox");}; return _uiNotesAddOnlyTextBox;}} private Element _uiNotesAddOnlyTextBox;
		public jQueryObject uiNotesAddOnlyTextBoxJ {get {if (_uiNotesAddOnlyTextBoxJ == null) {_uiNotesAddOnlyTextBoxJ = jQuery.Select("#" + clientId + "_uiNotesAddOnlyTextBox");}; return _uiNotesAddOnlyTextBoxJ;}} private jQueryObject _uiNotesAddOnlyTextBoxJ;//mappings.Add("Spotted.Controls.AddOnlyTextBox", ElementGetter("Element"));
		public Element uiInsertionOrderItemGridView {get {if (_uiInsertionOrderItemGridView == null) {_uiInsertionOrderItemGridView = (Element)Document.GetElementById(clientId + "_uiInsertionOrderItemGridView");}; return _uiInsertionOrderItemGridView;}} private Element _uiInsertionOrderItemGridView;
		public jQueryObject uiInsertionOrderItemGridViewJ {get {if (_uiInsertionOrderItemGridViewJ == null) {_uiInsertionOrderItemGridViewJ = jQuery.Select("#" + clientId + "_uiInsertionOrderItemGridView");}; return _uiInsertionOrderItemGridViewJ;}} private jQueryObject _uiInsertionOrderItemGridViewJ;//mappings.Add("System.Web.UI.WebControls.GridView", ElementGetter("Element"));
		public Element uiSaveButton {get {if (_uiSaveButton == null) {_uiSaveButton = (Element)Document.GetElementById(clientId + "_uiSaveButton");}; return _uiSaveButton;}} private Element _uiSaveButton;
		public jQueryObject uiSaveButtonJ {get {if (_uiSaveButtonJ == null) {_uiSaveButtonJ = jQuery.Select("#" + clientId + "_uiSaveButton");}; return _uiSaveButtonJ;}} private jQueryObject _uiSaveButtonJ;//mappings.Add("System.Web.UI.WebControls.Button", ElementGetter("Element"));
		public Element uiCancelButton {get {if (_uiCancelButton == null) {_uiCancelButton = (Element)Document.GetElementById(clientId + "_uiCancelButton");}; return _uiCancelButton;}} private Element _uiCancelButton;
		public jQueryObject uiCancelButtonJ {get {if (_uiCancelButtonJ == null) {_uiCancelButtonJ = jQuery.Select("#" + clientId + "_uiCancelButton");}; return _uiCancelButtonJ;}} private jQueryObject _uiCancelButtonJ;//mappings.Add("System.Web.UI.WebControls.Button", ElementGetter("Element"));
		public Element uiRaiseButton {get {if (_uiRaiseButton == null) {_uiRaiseButton = (Element)Document.GetElementById(clientId + "_uiRaiseButton");}; return _uiRaiseButton;}} private Element _uiRaiseButton;
		public jQueryObject uiRaiseButtonJ {get {if (_uiRaiseButtonJ == null) {_uiRaiseButtonJ = jQuery.Select("#" + clientId + "_uiRaiseButton");}; return _uiRaiseButtonJ;}} private jQueryObject _uiRaiseButtonJ;//mappings.Add("System.Web.UI.WebControls.Button", ElementGetter("Element"));
		public Element GenericContainerPage {get {if (_GenericContainerPage == null) {_GenericContainerPage = (Element)Document.GetElementById(clientId + "_GenericContainerPage");}; return _GenericContainerPage;}} private Element _GenericContainerPage;
		public jQueryObject GenericContainerPageJ {get {if (_GenericContainerPageJ == null) {_GenericContainerPageJ = jQuery.Select("#" + clientId + "_GenericContainerPage");}; return _GenericContainerPageJ;}} private jQueryObject _GenericContainerPageJ;//mappings.Add("Spotted.GenericPage", ElementGetter("Element"));
	}
}
