//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// <auto-generated>
//     This API code was generated by the DanDoes.NET Facebook API Generator.
//     Facebook.Api.Generator v1.0.3412.20062
//     
//     The following documents were used to generate this code:
//		Facebook API Object Schema:	http://api.facebook.com/1.0/facebook.xsd
//		Facebook API Wiki:			http://wiki.developers.facebook.com/index.php/API
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facebook {
    using System;
    using System.Collections.Generic;
    using System.Xml.Linq;
    using Facebook;
    using Facebook.Api.Controllers;
    
    
    public partial class FacebookContextBase<TCache, TSession>
        where TCache : ICacheWrapper, new()
        where TSession :  class, ISessionInfo {
        
        private AuthController _auth;
        
        private ConnectController _connect;
        
        private EventsController _events;
        
        private NotesController _notes;
        
        private StatusController _status;
        
        private StreamController _stream;
        
        private LinksController _links;
        
        private CommentsController _comments;
        
        private FbmlController _fbml;
        
        private FeedController _feed;
        
        private FriendsController _friends;
        
        private GroupsController _groups;
        
        private DataController _data;
        
        private LiveMessageController _liveMessage;
        
        private NotificationsController _notifications;

		private DashboardController _dashboard;
        
        private PhotosController _photos;
        
        private VideoController _video;
        
        private ProfileController _profile;
        
        private UsersController _users;
        
        private PagesController _pages;
        
        private AdminController _admin;
        
        private ApplicationController _application;
        
        public FacebookContextBase(ApplicationType appType, String apiKey, String secret) : 
                this(apiKey, secret) {
            this.InitControllers();
            this.ApplicationType = appType;
        }
        
        public FacebookContextBase(ApplicationType appType, String apiKey, String secret, String version) : 
                this(apiKey, secret, version) {
            this.InitControllers();
            this.ApplicationType = appType;
        }
        
        public virtual AuthController Auth {
            get {
                return this._auth;
            }
        }
        
        public virtual ConnectController Connect {
            get {
                return this._connect;
            }
        }
        
        public virtual EventsController Events {
            get {
                return this._events;
            }
        }
        
        public virtual NotesController Notes {
            get {
                return this._notes;
            }
        }
        
        public virtual StatusController Status {
            get {
                return this._status;
            }
        }
        
        public virtual StreamController Stream {
            get {
                return this._stream;
            }
        }
        
        public virtual LinksController Links {
            get {
                return this._links;
            }
        }
        
        public virtual CommentsController Comments {
            get {
                return this._comments;
            }
        }
        
        public virtual FbmlController Fbml {
            get {
                return this._fbml;
            }
        }
        
        public virtual FeedController Feed {
            get {
                return this._feed;
            }
        }
        
        public virtual FriendsController Friends {
            get {
                return this._friends;
            }
        }
        
        public virtual GroupsController Groups {
            get {
                return this._groups;
            }
        }
        
        public virtual DataController Data {
            get {
                return this._data;
            }
        }
        
        public virtual LiveMessageController LiveMessage {
            get {
                return this._liveMessage;
            }
        }
        
        public virtual NotificationsController Notifications {
            get {
                return this._notifications;
            }
        }

		public virtual DashboardController Dashboard
		{
			get
			{
				return this._dashboard;
			}
		}
        
        public virtual PhotosController Photos {
            get {
                return this._photos;
            }
        }
        
        public virtual VideoController Video {
            get {
                return this._video;
            }
        }
        
        public virtual ProfileController Profile {
            get {
                return this._profile;
            }
        }
        
        public virtual UsersController Users {
            get {
                return this._users;
            }
        }
        
        public virtual PagesController Pages {
            get {
                return this._pages;
            }
        }
        
        public virtual AdminController Admin {
            get {
                return this._admin;
            }
        }
        
        public virtual ApplicationController Application {
            get {
                return this._application;
            }
        }
        
        private void InitControllers() {
            this._auth = new AuthController(this);
            this._connect = new ConnectController(this);
            this._events = new EventsController(this);
            this._notes = new NotesController(this);
            this._status = new StatusController(this);
            this._stream = new StreamController(this);
            this._links = new LinksController(this);
            this._comments = new CommentsController(this);
            this._fbml = new FbmlController(this);
            this._feed = new FeedController(this);
            this._friends = new FriendsController(this);
            this._groups = new GroupsController(this);
            this._data = new DataController(this);
            this._liveMessage = new LiveMessageController(this);
            this._notifications = new NotificationsController(this);
			this._dashboard = new DashboardController(this);
            this._photos = new PhotosController(this);
            this._video = new VideoController(this);
            this._profile = new ProfileController(this);
            this._users = new UsersController(this);
            this._pages = new PagesController(this);
            this._admin = new AdminController(this);
            this._application = new ApplicationController(this);
        }
    }
}
